/**
 * Línea de Tiempo — configuración por defecto y textos en español, inglés y portugués.
 */
export const GAME_ID = 'linea-de-tiempo';
export const DEFAULT_CONFIG = { theme: 'historia', handSize: 5, shared: true, spread: true };
/** Cartas a la vista en el modo de pozo común (D-32). */
export const VISIBLE = 6;
/** Con todas a la vista se despliega el doble de la meta y no entra ninguna más (D-43). */
export const SPREAD_FACTOR = 2;
export const HAND_SIZES = [3, 5, 7];
export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 6;

const ES = {
  docTitle: 'Línea de Tiempo ⏳ · Juegos de Salón', gameChip: '⏳ Línea de Tiempo', menu: '‹ Menú',
  title: 'Línea de Tiempo',
  lead: 'Ubica cada hito en la línea de tiempo sin ver su año.',
  howTitle: '🧭 ¿Cómo se juega?',
  howText: 'En tu turno eliges una carta y el lugar de la línea donde crees que va. Si aciertas, la carta se queda en la línea. Si fallas, se descarta. Gana el primero en poner bien las cartas para ganar. La ronda se juega completa y, si empatan, gana el más rápido.',
  modeLocal: '📱 Un celular, hasta 6', modeLocalHint: 'Se pasan el celular por turnos.',
  modeOnline: '📡 Varios celulares', modeOnlineHint: 'Una sala con código para hasta 6 jugadores.',
  modeSolo: '🧍 Jugar solo', modeSoloHint: 'Ubica nueve hitos contra el reloj.',
  // setup
  setupTitle: '¿Cómo jugamos?', theme: 'Temática', handSize: 'Cartas en mano',
  cardsMode: 'Cartas', modeOwn: 'Mano propia', modeShared: 'Pozo común', modeAll: 'Todas a la vista',
  ownHint: 'Cada uno juega con su propia mano.',
  sharedHint: 'Todos eligen entre {n} cartas a la vista que se reponen del mazo.',
  allHint: 'Todos eligen entre {n} cartas a la vista que no se reponen.',
  toWin: 'Cartas para ganar', visibleTitle: 'Cartas a la vista',
  short: 'Corta', normal: 'Normal', long: 'Larga',
  players: 'Jugadores', playerPlaceholder: 'Jugador {n}', addPlayer: '+ Agregar jugador', maxPlayers: 'Máximo {n} jugadores', removePlayer: 'Quitar jugador',
  yourName: 'Tu nombre', start: '¡A jugar!',
  errName: 'Falta el nombre.', errNames: 'Faltan nombres o están repetidos.',
  create: 'Crear sala', joinTitle: '¿Tienes un código? ¡Únete!', codePlaceholder: 'CÓDIGO', join: 'Unirse', errCode: 'El código tiene 4 letras.',
  errNotFound: 'No existe esa sala. Revisa el código.', errFull: 'La sala ya está llena.', errExpired: 'Esa sala ya venció.', errOtherGame: 'Ese código es de otro juego.', errNet: 'No se pudo conectar. ¿Hay internet?',
  errOffline: 'No se pudo abrir la sala. Puede ser tu internet o que haya mucha gente jugando. Intenta nuevamente en unos minutos o jugar en modo de un solo celular sin conexión a internet.',
  errTooMany: 'Abriste muchas salas seguidas. Espera un ratito y prueba de nuevo.',
  invitedTitle: '¡Invitado a jugar!', invited: '📩 Sala {code}', invitedHint: 'Escribe tu nombre y entra. La partida la configura quien te invitó.',
  lobbyTitle: 'Sala creada', lobbyCode: 'Código', lobbyShare: 'Dile el código al resto o que escaneen el QR.', shareLink: '📤 Compartir link', copyLink: '📋 Copiar link', copied: '¡Copiado!',
  lobbyPlayers: 'En la sala', lobbyWaitHost: 'Esperando a que {name} empiece', lobbyStart: '🚀 ¡Empezar!', lobbyNeedMore: 'Faltan jugadores',
  lobbyCancel: 'Cancelar la sala', lobbyLeave: 'Salir de la sala',
  offline: '{name} se desconectó', waitingTurn: 'Esperando a {name}…', placedBy: '{name} colocó',
  // juego
  turnYou: '¡Te toca, {name}!', turnOther: 'Turno de {name}',
  yourHand: 'Tu mano', handOf: 'Mano de {name}', pickCard: 'Elige una carta', pickSlot: '¿Dónde va?', place: '📍 Colocar aquí',
  timeline: 'Línea de tiempo', cardsLeft: '{n}', poolLeft: 'Quedan {n} en el mazo',
  tableLeft: 'Quedan {n} cartas en la mesa', tableLeftOne: 'Queda 1 carta en la mesa',
  slotFirst: '↑ Antes de todo', slotLast: '↓ Después de todo', slotBetween: 'Aquí',
  correct: '¡Correcto!', wrong: '¡Te equivocaste!', correctOther: '¡{name} acertó!', wrongOther: '¡{name} se equivocó!',
  wasYear: 'Era {year}', goesHere: 'Iba aquí ↓', drewNew: 'La carta se descarta y robas una nueva.', drewNewOther: 'La carta se descarta y roba una nueva.',
  whyWrong: 'Fue en {year}: iba {where}.', wherePlaced: 'Tú la pusiste {where}.', wherePlacedOther: 'La puso {where}.', between: 'entre {a} y {b}', beforeOf: 'antes de {b}', afterOf: 'después de {a}', tapContinue: 'Toca para seguir',
  hoPass: 'Pásale el celular a', hoReady: '¡Listo, soy yo!', hoContinue: 'Seguir',
  // resultado
  winTitle: '¡Ganó {name}!', winTitleMany: '¡Empate!', youWin: '¡Ganaste!', youLose: 'Perdiste… esta vez.',
  wonOnTime: '⚡ Empataron sin cartas: ganó el más rápido', wonOnTimeShared: '⚡ Empataron: ganó el más rápido',
  stats: '{ok} de {total} aciertos', ranking: 'Cómo terminaron', cardsHeld: '{n} cartas', cardHeld: '1 carta', noCards: 'sin cartas',
  finalLine: 'La línea quedó así', rematch: '🔁 Revancha', changeMode: 'Cambiar modo', backMenu: 'Volver al menú',
  resumeTitle: '⏯ Hay una partida a medias', resume: 'Continuar', delete: 'Borrar',
  // jugar solo: la ⏳ Línea Relámpago de La Copa (D-142)
  soloTitle: '⏳ Línea Relámpago',
  soloHow: [
    'Hay 10 hitos: el primero ya está en la línea y los otros 9 en tu mano.',
    'Toca una carta y el lugar donde va (o arrástrala hasta ahí), y toca Colocar aquí.',
    'Si fallas, la carta va a su lugar correcto marcada en rojo.',
  ],
  soloScoreTitle: '🎯 Puntaje',
  soloScore: 'Las 9 cartas bien puestas son 100 puntos. A igual puntaje, tu récord es el de menor tiempo.',
  lineaLleva: 'vas {ok} de {n}', lineaQuedan: 'Quedan {n}', lineaFin: 'Pusiste bien {ok} de {n} cartas.', seeResults: 'Ver resultado',
  soloPerfect: '¡Línea perfecta!', soloDone: '¡Línea lista!', soloResult: 'Pusiste bien {ok} de {n} cartas en {t}.',
  newRecord: '🏆 ¡Nuevo récord!', prevRecord: 'Tu récord en {tema} es de {s} puntos en {t}.',
  playAgain: '🔁 Jugar otra vez',
  // chat de sala (solo varios celulares)
  chatTitle: 'Chat de la sala', chatOpen: 'Abrir el chat', chatClose: 'Cerrar el chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escribe algo…', chatEmpty: 'Acá pueden comentar la partida. Se borra cuando termina.',
};

const EN = {
  docTitle: 'Timeline ⏳ · Party Games', gameChip: '⏳ Timeline', menu: '‹ Menu',
  title: 'Timeline',
  lead: 'Place each milestone on the timeline without seeing its year.',
  howTitle: '🧭 How do you play?',
  howText: 'On your turn you pick a card and the spot on the timeline where you think it goes. Get it right and the card stays on the timeline. Get it wrong and it is discarded. The first one to correctly place the cards needed to win is the winner. The round is always played out and, if there is a tie, the fastest one wins.',
  modeLocal: '📱 One phone, up to 6', modeLocalHint: 'Pass the phone around, turn by turn.',
  modeOnline: '📡 Several phones', modeOnlineHint: 'A room with a code for up to 6 players.',
  modeSolo: '🧍 Play alone', modeSoloHint: 'Place nine milestones against the clock.',
  setupTitle: 'How do we play?', theme: 'Theme', handSize: 'Cards in hand',
  cardsMode: 'Cards', modeOwn: 'Own hand', modeShared: 'Shared pool', modeAll: 'All on the table',
  ownHint: 'Everyone plays their own hand.',
  sharedHint: 'Everyone picks from {n} open cards that are refilled from the deck.',
  allHint: 'Everyone picks from {n} open cards that are not refilled.',
  toWin: 'Cards to win', visibleTitle: 'Cards on the table',
  short: 'Short', normal: 'Normal', long: 'Long',
  players: 'Players', playerPlaceholder: 'Player {n}', addPlayer: '+ Add player', maxPlayers: 'Max {n} players', removePlayer: 'Remove player',
  yourName: 'Your name', start: 'Let\'s play!',
  errName: 'Name missing.', errNames: 'Names missing or repeated.',
  create: 'Create room', joinTitle: 'Got a code? Jump in!', codePlaceholder: 'CODE', join: 'Join', errCode: 'The code has 4 letters.',
  errNotFound: 'That room doesn\'t exist. Check the code.', errFull: 'That room is full.', errExpired: 'That room has expired.', errOtherGame: 'That code belongs to another game.', errNet: 'Could not connect. Is there internet?',
  errOffline: 'Couldn\'t open the room. It might be your connection or too many people playing. Try again in a few minutes, or play in one-phone mode, which needs no internet.',
  errTooMany: 'You\'ve opened a lot of rooms in a row. Wait a bit and try again.',
  invitedTitle: 'Invited to play!', invited: '📩 Room {code}', invitedHint: 'Type your name and jump in. Whoever invited you sets up the game.',
  lobbyTitle: 'Room created', lobbyCode: 'Code', lobbyShare: 'Tell the others the code or let them scan the QR.', shareLink: '📤 Share link', copyLink: '📋 Copy link', copied: 'Copied!',
  lobbyPlayers: 'In the room', lobbyWaitHost: 'Waiting for {name} to start', lobbyStart: '🚀 Start!', lobbyNeedMore: 'Need more players',
  lobbyCancel: 'Cancel the room', lobbyLeave: 'Leave the room',
  offline: '{name} disconnected', waitingTurn: 'Waiting for {name}…', placedBy: '{name} placed',
  turnYou: 'Your turn, {name}!', turnOther: '{name}\'s turn',
  yourHand: 'Your hand', handOf: '{name}\'s hand', pickCard: 'Pick a card', pickSlot: 'Where does it go?', place: '📍 Place it here',
  timeline: 'Timeline', cardsLeft: '{n}', poolLeft: '{n} left in the deck',
  tableLeft: '{n} cards left on the table', tableLeftOne: '1 card left on the table',
  slotFirst: '↑ Before everything', slotLast: '↓ After everything', slotBetween: 'Here',
  correct: 'Correct!', wrong: 'Wrong!', correctOther: '{name} nailed it!', wrongOther: '{name} got it wrong!',
  wasYear: 'It was {year}', goesHere: 'It goes here ↓', drewNew: 'The card is discarded and you draw a new one.', drewNewOther: 'The card is discarded and they draw a new one.',
  whyWrong: 'It happened in {year}: it belongs {where}.', wherePlaced: 'You put it {where}.', wherePlacedOther: 'They put it {where}.', between: 'between {a} and {b}', beforeOf: 'before {b}', afterOf: 'after {a}', tapContinue: 'Tap to continue',
  hoPass: 'Pass the phone to', hoReady: 'Ready, it\'s me!', hoContinue: 'Continue',
  winTitle: '{name} wins!', winTitleMany: 'It\'s a tie!', youWin: 'You win!', youLose: 'You lose… this time.',
  wonOnTime: '⚡ Tied with no cards: the fastest one wins', wonOnTimeShared: '⚡ Tied: the fastest one wins',
  stats: '{ok} of {total} correct', ranking: 'How it ended', cardsHeld: '{n} cards', cardHeld: '1 card', noCards: 'no cards',
  finalLine: 'The timeline ended like this', rematch: '🔁 Rematch', changeMode: 'Change mode', backMenu: 'Back to menu',
  resumeTitle: '⏯ There\'s an unfinished game', resume: 'Continue', delete: 'Delete',
  // play alone: the ⏳ Timeline Flash from La Copa (D-142)
  soloTitle: '⏳ Timeline Flash',
  soloHow: [
    'There are 10 milestones: the first one is already on the timeline and the other 9 are in your hand.',
    'Tap a card and the spot where it goes (or drag it there), and tap Place it here.',
    'If you get it wrong, the card goes to its right spot marked in red.',
  ],
  soloScoreTitle: '🎯 Score',
  soloScore: 'All 9 cards placed correctly are 100 points. With the same score, your record is the faster time.',
  lineaLleva: '{ok} of {n} right', lineaQuedan: '{n} left', lineaFin: 'You placed {ok} of {n} cards correctly.', seeResults: 'See the result',
  soloPerfect: 'Perfect timeline!', soloDone: 'Timeline done!', soloResult: 'You placed {ok} of {n} cards correctly in {t}.',
  newRecord: '🏆 New record!', prevRecord: 'Your record for {tema} is {s} points in {t}.',
  playAgain: '🔁 Play again',
  // room chat (several phones only)
  chatTitle: 'Room chat', chatOpen: 'Open the chat', chatClose: 'Close the chat', chatSend: 'Send',
  chatPlaceholder: 'Say something…', chatEmpty: 'Talk trash about the game here. It disappears when the game ends.',
};


const PT = {
  docTitle: 'Linha do Tempo ⏳ · Jogos de Salão', gameChip: '⏳ Linha do Tempo', menu: '‹ Menu',
  title: 'Linha do Tempo',
  lead: 'Coloque cada marco na linha do tempo sem ver o ano.',
  howTitle: '🧭 Como se joga?',
  howText: 'Na sua vez você escolhe uma carta e o lugar da linha onde acha que ela vai. Se acertar, a carta fica na linha. Se errar, ela é descartada. Ganha o primeiro a colocar certo as cartas necessárias para ganhar. A rodada sempre vai até o fim e, se houver empate, ganha o mais rápido.',
  modeLocal: '📱 Um celular, até 6', modeLocalHint: 'Vocês passam o celular a cada turno.',
  modeOnline: '📡 Vários celulares', modeOnlineHint: 'Uma sala com código para até 6 jogadores.',
  modeSolo: '🧍 Jogar sozinho', modeSoloHint: 'Coloque nove marcos contra o relógio.',
  // configuração
  setupTitle: 'Como vamos jogar?', theme: 'Tema', handSize: 'Cartas na mão',
  cardsMode: 'Cartas', modeOwn: 'Mão própria', modeShared: 'Monte comum', modeAll: 'Todas na mesa',
  ownHint: 'Cada um joga com a própria mão.',
  sharedHint: 'Todos escolhem entre {n} cartas à vista que são repostas do baralho.',
  allHint: 'Todos escolhem entre {n} cartas à vista que não são repostas.',
  toWin: 'Cartas para ganhar', visibleTitle: 'Cartas à vista',
  short: 'Curta', normal: 'Normal', long: 'Longa',
  players: 'Jogadores', playerPlaceholder: 'Jogador {n}', addPlayer: '+ Adicionar jogador', maxPlayers: 'No máximo {n} jogadores', removePlayer: 'Remover jogador',
  yourName: 'Seu nome', start: 'Bora jogar!',
  errName: 'Falta o nome.', errNames: 'Faltam nomes ou estão repetidos.',
  create: 'Criar sala', joinTitle: 'Tem um código? Entre!', codePlaceholder: 'CÓDIGO', join: 'Entrar', errCode: 'O código tem 4 letras.',
  errNotFound: 'Essa sala não existe. Confira o código.', errFull: 'A sala já está cheia.', errExpired: 'Essa sala já expirou.', errOtherGame: 'Esse código é de outro jogo.', errNet: 'Não foi possível conectar. Tem internet?',
  errOffline: 'Não foi possível abrir a sala. Pode ser a sua internet ou muita gente jogando ao mesmo tempo. Tente de novo em alguns minutos ou jogue no modo de um celular só, que não precisa de internet.',
  errTooMany: 'Você abriu muitas salas seguidas. Espere um pouquinho e tente de novo.',
  invitedTitle: 'Convidado para jogar!', invited: '📩 Sala {code}', invitedHint: 'Escreva seu nome e entre. Quem te convidou configura a partida.',
  lobbyTitle: 'Sala criada', lobbyCode: 'Código', lobbyShare: 'Diga o código aos outros ou deixe eles escanearem o QR.', shareLink: '📤 Compartilhar link', copyLink: '📋 Copiar link', copied: 'Copiado!',
  lobbyPlayers: 'Na sala', lobbyWaitHost: 'Esperando {name} começar', lobbyStart: '🚀 Começar!', lobbyNeedMore: 'Faltam jogadores',
  lobbyCancel: 'Cancelar a sala', lobbyLeave: 'Sair da sala',
  offline: '{name} se desconectou', waitingTurn: 'Esperando {name}…', placedBy: '{name} colocou',
  // jogo
  turnYou: 'Sua vez, {name}!', turnOther: 'Vez de {name}',
  yourHand: 'Sua mão', handOf: 'Mão de {name}', pickCard: 'Escolha uma carta', pickSlot: 'Onde ela vai?', place: '📍 Colocar aqui',
  timeline: 'Linha do tempo', cardsLeft: '{n}', poolLeft: 'Faltam {n} no baralho',
  tableLeft: 'Faltam {n} cartas na mesa', tableLeftOne: 'Falta 1 carta na mesa',
  slotFirst: '↑ Antes de tudo', slotLast: '↓ Depois de tudo', slotBetween: 'Aqui',
  correct: 'Correto!', wrong: 'Você errou!', correctOther: '{name} acertou!', wrongOther: '{name} errou!',
  wasYear: 'Foi em {year}', goesHere: 'Ia aqui ↓', drewNew: 'A carta é descartada e você compra uma nova.', drewNewOther: 'A carta é descartada e quem jogou compra uma nova.',
  whyWrong: 'Foi em {year}: ia {where}.', wherePlaced: 'Você colocou {where}.', wherePlacedOther: 'Foi colocada {where}.', between: 'entre {a} e {b}', beforeOf: 'antes de {b}', afterOf: 'depois de {a}', tapContinue: 'Toque para continuar',
  hoPass: 'Passe o celular para', hoReady: 'Pronto, sou eu!', hoContinue: 'Continuar',
  // resultado
  winTitle: '{name} ganhou!', winTitleMany: 'Empate!', youWin: 'Você ganhou!', youLose: 'Você perdeu… desta vez.',
  wonOnTime: '⚡ Empataram sem cartas: ganhou o mais rápido', wonOnTimeShared: '⚡ Empataram: ganhou o mais rápido',
  stats: '{ok} de {total} acertos', ranking: 'Como terminaram', cardsHeld: '{n} cartas', cardHeld: '1 carta', noCards: 'sem cartas',
  finalLine: 'A linha ficou assim', rematch: '🔁 Revanche', changeMode: 'Mudar o modo', backMenu: 'Voltar ao menu',
  resumeTitle: '⏯ Tem uma partida pela metade', resume: 'Continuar', delete: 'Apagar',
  // jogar sozinho: a ⏳ Linha Relâmpago da Copa (D-142)
  soloTitle: '⏳ Linha Relâmpago',
  soloHow: [
    'São 10 marcos: o primeiro já está na linha e os outros 9 na sua mão.',
    'Toque numa carta e no lugar onde ela vai (ou arraste até lá), e toque em Colocar aqui.',
    'Se errar, a carta vai para o lugar certo marcada em vermelho.',
  ],
  soloScoreTitle: '🎯 Pontuação',
  soloScore: 'As 9 cartas bem colocadas valem 100 pontos. Com a mesma pontuação, seu recorde é o de menor tempo.',
  lineaLleva: '{ok} de {n} certas', lineaQuedan: 'Faltam {n}', lineaFin: 'Você acertou {ok} de {n} cartas.', seeResults: 'Ver o resultado',
  soloPerfect: 'Linha perfeita!', soloDone: 'Linha pronta!', soloResult: 'Você acertou {ok} de {n} cartas em {t}.',
  newRecord: '🏆 Novo recorde!', prevRecord: 'Seu recorde em {tema} é de {s} pontos em {t}.',
  playAgain: '🔁 Jogar de novo',
  // chat da sala (só com vários celulares)
  chatTitle: 'Chat da sala', chatOpen: 'Abrir o chat', chatClose: 'Fechar o chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escreva algo…', chatEmpty: 'Aqui vocês podem comentar a partida. Some quando ela termina.',
};

export const LOCALES = { es: ES, en: EN, pt: PT };
