/**
 * El Ahorcado — configuración por defecto y textos en español, inglés y portugués.
 * Las tres listas tienen exactamente las mismas claves (canon C-3).
 */
export const GAME_ID = 'ahorcado';
export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 6;
/** `source`: de dónde sale la palabra, cadena (la escribe el jugador anterior) o mazo (D-53). */
export const DEFAULT_CONFIG = { source: 'chain', theme: 'mezcla', lives: 6, buy: true };
export const MAX_HINT = 40;

/**
 * El dibujo, en trazos. La horca está desde el principio, apagada; cada error dibuja
 * una parte del monito. El último trazo, en las tres dificultades, son los ojos en X.
 * Coordenadas del viewBox "0 0 120 150".
 */
export const GALLOWS = ['M8,142 H72', 'M26,142 V10', 'M26,10 H86', 'M86,10 V28'];
const P = {
  cabeza: 'M86,28 A10,10 0 1 1 85.9,28',
  cuerpo: 'M86,48 V88',
  brazoI: 'M86,58 L70,74', brazoD: 'M86,58 L102,74', brazos: 'M70,74 L86,58 L102,74',
  piernaI: 'M86,88 L72,110', piernaD: 'M86,88 L100,110', piernas: 'M72,110 L86,88 L100,110',
  manos: 'M67,71 L73,77 M99,71 L105,77',
  cara: 'M81,34 L85,38 M85,34 L81,38 M87,34 L91,38 M91,34 L87,38',
};
export const PARTS = {
  5: [P.cabeza, P.cuerpo, P.brazos, P.piernas, P.cara],
  6: [P.cabeza, P.cuerpo, P.brazoI, P.brazoD, P.piernas, P.cara],
  8: [P.cabeza, P.cuerpo, P.brazoI, P.brazoD, P.piernaI, P.piernaD, P.manos, P.cara],
};

const ES = {
  docTitle: 'El Ahorcado 🪢 · Juegos de Salón', gameChip: '🪢 El Ahorcado', menu: '‹ Menú',
  title: 'El Ahorcado',
  lead: 'Adivina tu palabra antes de que se te acaben los errores. Acá nadie se queda mirando: todos adivinan.',
  howTitle: '🧠 Cómo se juega',
  howText: 'Cada jugador tiene una palabra tapada y va probando letras. Si la letra está, aparece en todos sus lugares; si no está, se dibuja un trazo del ahorcado. Cuando se completa el dibujo, te colgaron. <b>Gana quien adivina su palabra con más errores de margen</b>, así que no basta con sacarla: hay que sacarla barata.',
  example: 'Poner una palabra imposible no te suma ni un punto: el puntaje se lo lleva el que adivina.',
  modeLocal: '📱 Un celular', modeLocalHint: 'Se pasan el celular. Cada uno prueba una letra y le toca al siguiente.',
  modeOnline: '📡 Varios celulares', modeOnlineHint: 'Sala con código de 4 letras. Todos adivinan al mismo tiempo.',
  modeSolo: '🧍 Jugar solo', modeSoloHint: 'La app elige una palabra de la temática y la sacas tú, sin nadie más.',
  // configuración
  setupTitle: '¿Cómo jugamos?', theme: 'Temática', wordSource: 'La palabra',
  srcNeedsHttps: 'La cadena guarda la palabra en secreto y para eso hace falta abrir el juego con https o desde localhost. Desde esta dirección solo se puede jugar con el mazo.',
  srcChain: 'Cadena', srcChainHint: 'Cada uno le escribe la palabra al siguiente, con una pista.',
  srcDeck: 'Mazo de la app', srcDeckHint: 'La app reparte de la temática elegida, con su pista.',
  lives: 'Errores permitidos', livesHard: 'Difícil', livesNormal: 'Normal', livesEasy: 'Fácil',
  buyLabel: 'Dejar comprar letras', buyHint: 'Revela la letra que falta más rara y cuesta un error.',
  players: 'Jugadores', playerPlaceholder: 'Jugador {n}', addPlayer: '＋ Agregar jugador', removePlayer: 'Quitar jugador', maxPlayers: 'Máximo {n} jugadores',
  yourName: 'Tu nombre', start: '¡A jugar!', create: 'Crear sala', joinTitle: 'Unirse a una sala', codePlaceholder: 'CÓDIGO', join: 'Unirse',
  errName: 'Falta el nombre.', errNames: 'Faltan nombres o están repetidos.', errCode: 'El código tiene 4 letras.',
  errNotFound: 'No existe esa sala. Revisa el código.', errFull: 'La sala ya está llena.', errExpired: 'Esa sala ya venció.', errOtherGame: 'Ese código es de otro juego.', errNet: 'No se pudo conectar. ¿Hay internet?',
  errOffline: 'No se pudo abrir la sala. Puede ser tu internet o que haya mucha gente jugando. Intenta nuevamente en unos minutos o juega en modo de un solo celular sin conexión a internet.',
  errTooMany: 'Abriste muchas salas seguidas. Espera un ratito y prueba de nuevo.',
  // sala
  lobbyTitle: 'Sala creada', lobbyCode: 'Código', lobbyShare: 'Dile el código al resto o que escaneen el QR.',
  lobbyPlayers: 'En la sala', lobbyStart: '¡Empezar!', lobbyNeedMore: 'Faltan jugadores…', lobbyWaitHost: 'Esperando a que {name} empiece…',
  shareLink: '📤 Compartir link', shareText: 'Únete a mi sala de {game}. Temática: {theme}. Código: {code}', copyLink: '📋 Copiar link', copied: '¡Copiado!',
  lobbyCancel: 'Cancelar la sala', lobbyLeave: 'Salir de la sala',
  invitedTitle: '¡Invitado a jugar!', invited: '📩 Sala {code}', invitedHint: 'Escribe tu nombre y entra. La partida la configura quien te invitó.',
  // escribir la palabra
  wordTitle: 'Una palabra para {name}', wordHint: 'De 3 a 14 letras. También vale una frase corta: los espacios van regalados.',
  wordPlaceholder: 'La palabra', hintLabel: 'La pista', hintPlaceholder: 'Una pista corta y honesta', wordSave: 'Listo, guardarla',
  wordSaved: 'Palabra guardada 🔒', waitingWords: 'Esperando a que {name} escriba su palabra…', waitingWordsMany: 'Faltan {n} palabras por escribir…',
  errWordShort: 'Muy corta: mínimo 3 letras.', errWordLong: 'Muy larga: máximo 14 letras.',
  errWordLetters: 'Solo letras, sin números ni signos.', errWordPoor: 'Con una sola letra distinta no hay juego.',
  errHint: 'Falta la pista. Sin pista no es justo.',
  suggestLabel: 'Sugerencias de {theme}',
  suggestHint: 'Toca una y se llenan los dos campos. Después puedes cambiar la palabra o la pista.',
  errSecure: 'Para escribir la palabra en secreto hace falta abrir el juego con https o desde localhost.',
  coverLabel: 'Le toca escribir a', coverTap: 'Toca para escribir', hide: 'Tapar pantalla',
  // partida
  turnYou: '¡Te toca, {name}!', turnOther: 'Le toca a {name}…', yourWord: 'Tu palabra, {name}', waitingTurn: 'Esperando a {name}…',
  wordOf: 'La palabra de {name}', hintIs: 'Pista', livesLeft: 'Te quedan {n}', oneLifeLeft: '¡Te queda uno!',
  pickLetter: 'Elige una letra del teclado.', tryLetter: '🔤 Probar la {letter}',
  buyBtn: '💡 Comprar una letra', buyCost: 'cuesta un error', buyTitle: '¿Comprar una letra?',
  buyText: 'Se revela la letra que falta más rara y pierdes un error de margen. ¿Lo hacemos?', buyYes: 'Sí, cómprala', buyNo: 'Mejor no',
  bought: '💡 {name} compró la letra {letter}.', rivalsTitle: 'Los demás',
  offline: '{name} se desconectó. Esperando que vuelva…',
  // veredictos
  hitTitle: '¡Va!', missTitle: 'No está', buyDone: 'Comprada', hitOther: '{name} acertó', missOther: '{name} falló',
  letterIn: 'La {letter} aparece {n} veces.', letterInOne: 'La {letter} está.', letterOut: 'La {letter} no está en la palabra.',
  solvedTitle: '¡La sacaste!', hangedTitle: 'Te colgaron', solvedOther: '¡{name} la sacó!', hangedOther: 'Colgaron a {name}',
  wordWas: 'La palabra era', scoreWas: 'Te quedaron {n} de margen', scoreZero: 'Sin margen',
  // pase del celular
  hoPass: 'Pásale el celular a', hoReady: '¡Listo, soy yo!', hoContinue: 'Seguir', tapContinue: 'Toca para seguir',
  // resultado
  soloWordWas: 'La palabra era', soloScore: 'Te sobraron {n} y la sacaste en {letters} letras.',
  winTitle: '¡Ganó {name}!', winTitleMany: '¡Empate!', winTitleNone: 'No la sacó nadie', youWin: '¡Ganaste!', youLose: 'Perdiste… esta vez.',
  rankLine: '{n} de margen · {letters} letras', rankHanged: 'Colgado · {letters} letras', rankBought: 'compradas: {n}',
  wordsWere: 'Las palabras eran', verified: 'verificado ✅', notVerified: '⚠️ no coincide (¿trampa?)',
  rematch: '🔁 Revancha', rematchWaiting: 'Esperando a {name} para la revancha…', changeMode: 'Cambiar modo', backMenu: 'Volver al menú',
  resumeTitle: '⏯ Hay una partida a medias', resume: 'Continuar', delete: 'Borrar',
  // chat de sala
  chatTitle: 'Chat de la sala', chatOpen: 'Abrir el chat', chatClose: 'Cerrar el chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escribe algo…', chatEmpty: 'Acá pueden picarse mientras adivinan. Se borra cuando termina la sala.',
};

const EN = {
  docTitle: 'Hangman 🪢 · Party Games', gameChip: '🪢 Hangman', menu: '‹ Menu',
  title: 'Hangman',
  lead: 'Crack your word before you run out of mistakes. Nobody sits this one out: everyone guesses.',
  howTitle: '🧠 How to play',
  howText: 'Every player gets a hidden word and tries letters. A letter that is in there shows up in every spot; one that is not draws a stroke of the gallows. Finish the drawing and you hang. <b>Whoever cracks their word with the most mistakes to spare wins</b>, so getting it is not enough: you have to get it cheap.',
  example: 'Setting an impossible word earns you nothing: the points go to whoever guesses.',
  modeLocal: '📱 One phone', modeLocalHint: 'Pass the phone around. Each player tries one letter, then the next one goes.',
  modeOnline: '📡 Several phones', modeOnlineHint: 'Room with a 4-letter code. Everyone guesses at once.',
  modeSolo: '🧍 Play alone', modeSoloHint: 'The app picks a word from the theme and you crack it, on your own.',
  setupTitle: 'How are we playing?', theme: 'Theme', wordSource: 'The word',
  srcNeedsHttps: 'The chain keeps the word secret, and that needs the game opened over https or from localhost. From this address only the deck works.',
  srcChain: 'Chain', srcChainHint: 'Each player writes the word for the next one, with a hint.',
  srcDeck: 'App deck', srcDeckHint: 'The app deals from the chosen theme, hint included.',
  lives: 'Mistakes allowed', livesHard: 'Hard', livesNormal: 'Normal', livesEasy: 'Easy',
  buyLabel: 'Allow buying letters', buyHint: 'Reveals the rarest missing letter and costs one mistake.',
  players: 'Players', playerPlaceholder: 'Player {n}', addPlayer: '＋ Add player', removePlayer: 'Remove player', maxPlayers: 'Up to {n} players',
  yourName: 'Your name', start: 'Play!', create: 'Create room', joinTitle: 'Join a room', codePlaceholder: 'CODE', join: 'Join',
  errName: 'Your name is missing.', errNames: 'Names are missing or repeated.', errCode: 'The code is 4 letters.',
  errNotFound: 'No such room. Check the code.', errFull: 'That room is full.', errExpired: 'That room has expired.', errOtherGame: 'That code belongs to another game.', errNet: 'Could not connect. Is there internet?',
  errOffline: 'The room could not be opened. It may be your connection or a lot of people playing. Try again in a few minutes or play on a single phone with no internet.',
  errTooMany: 'You opened a lot of rooms in a row. Wait a bit and try again.',
  lobbyTitle: 'Room created', lobbyCode: 'Code', lobbyShare: 'Tell the others the code or let them scan the QR.',
  lobbyPlayers: 'In the room', lobbyStart: 'Start!', lobbyNeedMore: 'Waiting for players…', lobbyWaitHost: 'Waiting for {name} to start…',
  shareLink: '📤 Share link', shareText: 'Join my {game} room. Theme: {theme}. Code: {code}', copyLink: '📋 Copy link', copied: 'Copied!',
  lobbyCancel: 'Cancel the room', lobbyLeave: 'Leave the room',
  invitedTitle: 'You are invited!', invited: '📩 Room {code}', invitedHint: 'Type your name and come in. Whoever invited you sets the game up.',
  wordTitle: 'A word for {name}', wordHint: '3 to 14 letters. A short phrase works too: spaces come free.',
  wordPlaceholder: 'The word', hintLabel: 'The hint', hintPlaceholder: 'A short, honest hint', wordSave: 'Done, save it',
  wordSaved: 'Word saved 🔒', waitingWords: 'Waiting for {name} to write their word…', waitingWordsMany: '{n} words still to be written…',
  errWordShort: 'Too short: 3 letters minimum.', errWordLong: 'Too long: 14 letters maximum.',
  errWordLetters: 'Letters only, no digits or symbols.', errWordPoor: 'One single letter is not a game.',
  errHint: 'The hint is missing. No hint is not fair.',
  suggestLabel: 'Ideas from {theme}',
  suggestHint: 'Tap one and both fields fill in. You can still change the word or the hint.',
  errSecure: 'To write the word in secret, open the game over https or from localhost.',
  coverLabel: 'Now writing:', coverTap: 'Tap to write', hide: 'Cover the screen',
  turnYou: 'Your turn, {name}!', turnOther: '{name} is up…', yourWord: 'Your word, {name}', waitingTurn: 'Waiting for {name}…',
  wordOf: "{name}'s word", hintIs: 'Hint', livesLeft: '{n} to spare', oneLifeLeft: 'Just one left!',
  pickLetter: 'Pick a letter from the keyboard.', tryLetter: '🔤 Try the {letter}',
  buyBtn: '💡 Buy a letter', buyCost: 'costs one mistake', buyTitle: 'Buy a letter?',
  buyText: 'The rarest missing letter shows up and you lose one mistake of margin. Go ahead?', buyYes: 'Yes, buy it', buyNo: 'Never mind',
  bought: '💡 {name} bought the letter {letter}.', rivalsTitle: 'The others',
  offline: '{name} went offline. Waiting for them…',
  hitTitle: 'It is in!', missTitle: 'Not there', buyDone: 'Bought', hitOther: '{name} got one', missOther: '{name} missed',
  letterIn: 'The {letter} shows up {n} times.', letterInOne: 'The {letter} is in there.', letterOut: 'There is no {letter} in the word.',
  solvedTitle: 'You cracked it!', hangedTitle: 'You hanged', solvedOther: '{name} cracked it!', hangedOther: '{name} hanged',
  wordWas: 'The word was', scoreWas: '{n} mistakes to spare', scoreZero: 'No margin left',
  hoPass: 'Pass the phone to', hoReady: 'Got it, my turn!', hoContinue: 'Keep going', tapContinue: 'Tap to continue',
  soloWordWas: 'The word was', soloScore: 'You had {n} to spare and cracked it in {letters} letters.',
  winTitle: '{name} wins!', winTitleMany: 'It is a tie!', winTitleNone: 'Nobody cracked it', youWin: 'You win!', youLose: 'You lost… this time.',
  rankLine: '{n} to spare · {letters} letters', rankHanged: 'Hanged · {letters} letters', rankBought: 'bought: {n}',
  wordsWere: 'The words were', verified: 'verified ✅', notVerified: '⚠️ does not match (cheating?)',
  rematch: '🔁 Rematch', rematchWaiting: 'Waiting for {name} for a rematch…', changeMode: 'Change mode', backMenu: 'Back to menu',
  resumeTitle: '⏯ There is a game in progress', resume: 'Continue', delete: 'Delete',
  chatTitle: 'Room chat', chatOpen: 'Open the chat', chatClose: 'Close the chat', chatSend: 'Send',
  chatPlaceholder: 'Say something…', chatEmpty: 'Trash talk while you guess. It disappears when the room closes.',
};

const PT = {
  docTitle: 'Forca 🪢 · Jogos de Salão', gameChip: '🪢 Forca', menu: '‹ Menu',
  title: 'Forca',
  lead: 'Descubra sua palavra antes que os erros acabem. Aqui ninguém fica só olhando: todo mundo adivinha.',
  howTitle: '🧠 Como se joga',
  howText: 'Cada um recebe uma palavra escondida e vai testando letras. A letra que está aparece em todos os lugares; a que não está desenha um traço da forca. Quando o desenho termina, você foi enforcado. <b>Ganha quem descobre a palavra com mais erros de sobra</b>, então não basta acertar: tem que acertar barato.',
  example: 'Colocar uma palavra impossível não te dá nenhum ponto: quem pontua é quem adivinha.',
  modeLocal: '📱 Um celular', modeLocalHint: 'Vocês passam o celular. Cada um tenta uma letra e já passa a vez.',
  modeOnline: '📡 Vários celulares', modeOnlineHint: 'Sala com código de 4 letras. Todo mundo adivinha ao mesmo tempo.',
  modeSolo: '🧍 Jogar sozinho', modeSoloHint: 'O app escolhe uma palavra do tema e você descobre sozinho.',
  setupTitle: 'Como vamos jogar?', theme: 'Tema', wordSource: 'A palavra',
  srcNeedsHttps: 'A corrente guarda a palavra em segredo, e para isso o jogo precisa estar aberto por https ou pelo localhost. Deste endereço só dá para jogar com o baralho.',
  srcChain: 'Corrente', srcChainHint: 'Cada um escreve a palavra do seguinte, com uma dica.',
  srcDeck: 'Baralho do app', srcDeckHint: 'O app distribui do tema escolhido, com a dica junto.',
  lives: 'Erros permitidos', livesHard: 'Difícil', livesNormal: 'Normal', livesEasy: 'Fácil',
  buyLabel: 'Deixar comprar letras', buyHint: 'Revela a letra que falta mais rara e custa um erro.',
  players: 'Jogadores', playerPlaceholder: 'Jogador {n}', addPlayer: '＋ Adicionar jogador', removePlayer: 'Tirar jogador', maxPlayers: 'No máximo {n} jogadores',
  yourName: 'Seu nome', start: 'Bora jogar!', create: 'Criar sala', joinTitle: 'Entrar numa sala', codePlaceholder: 'CÓDIGO', join: 'Entrar',
  errName: 'Falta o nome.', errNames: 'Faltam nomes ou estão repetidos.', errCode: 'O código tem 4 letras.',
  errNotFound: 'Essa sala não existe. Confere o código.', errFull: 'A sala já está cheia.', errExpired: 'Essa sala já venceu.', errOtherGame: 'Esse código é de outro jogo.', errNet: 'Não deu para conectar. Tem internet?',
  errOffline: 'Não deu para abrir a sala. Pode ser a sua internet ou muita gente jogando. Tente de novo daqui a alguns minutos ou jogue no modo de um celular só, sem internet.',
  errTooMany: 'Você abriu muitas salas seguidas. Espera um pouquinho e tenta de novo.',
  lobbyTitle: 'Sala criada', lobbyCode: 'Código', lobbyShare: 'Passe o código para o resto ou deixe escanear o QR.',
  lobbyPlayers: 'Na sala', lobbyStart: 'Começar!', lobbyNeedMore: 'Faltam jogadores…', lobbyWaitHost: 'Esperando {name} começar…',
  shareLink: '📤 Compartilhar link', shareText: 'Entra na minha sala de {game}. Tema: {theme}. Código: {code}', copyLink: '📋 Copiar link', copied: 'Copiado!',
  lobbyCancel: 'Cancelar a sala', lobbyLeave: 'Sair da sala',
  invitedTitle: 'Você foi convidado!', invited: '📩 Sala {code}', invitedHint: 'Escreve seu nome e entra. Quem te convidou é que configura a partida.',
  wordTitle: 'Uma palavra para {name}', wordHint: 'De 3 a 14 letras. Uma frase curta também vale: os espaços são de graça.',
  wordPlaceholder: 'A palavra', hintLabel: 'A dica', hintPlaceholder: 'Uma dica curta e honesta', wordSave: 'Pronto, salvar',
  wordSaved: 'Palavra salva 🔒', waitingWords: 'Esperando {name} escrever a palavra…', waitingWordsMany: 'Faltam {n} palavras para escrever…',
  errWordShort: 'Curta demais: no mínimo 3 letras.', errWordLong: 'Longa demais: no máximo 14 letras.',
  errWordLetters: 'Só letras, sem números nem símbolos.', errWordPoor: 'Com uma letra só não tem jogo.',
  errHint: 'Falta a dica. Sem dica não é justo.',
  suggestLabel: 'Sugestões de {theme}',
  suggestHint: 'Toque em uma e os dois campos se preenchem. Depois você pode mudar a palavra ou a dica.',
  errSecure: 'Para escrever a palavra em segredo, abra o jogo por https ou pelo localhost.',
  coverLabel: 'Agora escreve:', coverTap: 'Toque para escrever', hide: 'Tapar a tela',
  turnYou: 'É a sua vez, {name}!', turnOther: 'É a vez de {name}…', yourWord: 'Sua palavra, {name}', waitingTurn: 'Esperando {name}…',
  wordOf: 'A palavra de {name}', hintIs: 'Dica', livesLeft: 'Sobram {n}', oneLifeLeft: 'Sobra um só!',
  pickLetter: 'Escolha uma letra do teclado.', tryLetter: '🔤 Testar o {letter}',
  buyBtn: '💡 Comprar uma letra', buyCost: 'custa um erro', buyTitle: 'Comprar uma letra?',
  buyText: 'Aparece a letra que falta mais rara e você perde um erro de margem. Vamos nessa?', buyYes: 'Sim, compra', buyNo: 'Deixa pra lá',
  bought: '💡 {name} comprou a letra {letter}.', rivalsTitle: 'Os outros',
  offline: '{name} caiu. Esperando voltar…',
  hitTitle: 'Tem!', missTitle: 'Não tem', buyDone: 'Comprada', hitOther: '{name} acertou', missOther: '{name} errou',
  letterIn: 'O {letter} aparece {n} vezes.', letterInOne: 'O {letter} está lá.', letterOut: 'Não tem {letter} na palavra.',
  solvedTitle: 'Você tirou!', hangedTitle: 'Te enforcaram', solvedOther: '{name} tirou!', hangedOther: 'Enforcaram {name}',
  wordWas: 'A palavra era', scoreWas: 'Sobraram {n} de margem', scoreZero: 'Sem margem',
  hoPass: 'Passa o celular para', hoReady: 'Pronto, sou eu!', hoContinue: 'Seguir', tapContinue: 'Toque para seguir',
  soloWordWas: 'A palavra era', soloScore: 'Sobraram {n} e você tirou em {letters} letras.',
  winTitle: '{name} ganhou!', winTitleMany: 'Empate!', winTitleNone: 'Ninguém tirou', youWin: 'Você ganhou!', youLose: 'Você perdeu… dessa vez.',
  rankLine: '{n} de margem · {letters} letras', rankHanged: 'Enforcado · {letters} letras', rankBought: 'compradas: {n}',
  wordsWere: 'As palavras eram', verified: 'verificado ✅', notVerified: '⚠️ não bate (trapaça?)',
  rematch: '🔁 Revanche', rematchWaiting: 'Esperando {name} para a revanche…', changeMode: 'Mudar de modo', backMenu: 'Voltar ao menu',
  resumeTitle: '⏯ Tem uma partida pela metade', resume: 'Continuar', delete: 'Apagar',
  chatTitle: 'Chat da sala', chatOpen: 'Abrir o chat', chatClose: 'Fechar o chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escreve algo…', chatEmpty: 'Aqui dá para zoar enquanto adivinham. Some quando a sala fecha.',
};

export const LOCALES = { es: ES, en: EN, pt: PT };
