/**
 * Dudo — datos y textos en español, inglés y portugués.
 * Solo datos, sin lógica. Ver docs/juegos/dudo.md.
 */

export const GAME_ID = 'dudo';
export const DEFAULT_CONFIG = { dice: 5, calzar: true, chileno: true };

/**
 * Como se nombran las pintas en una mesa chilena. Van aparte de LOCALES porque son de un solo
 * idioma: en inglés y en portugués no hay un juego de nombres equivalente instalado, así que ahí
 * las pintas se dicen por su número y el interruptor ni se ofrece (D-71).
 */
export const CHILENO = {
  one: { 1: 'as', 2: 'tonto', 3: 'tren', 4: 'cuadra', 5: 'quinta', 6: 'sexta' },
  many: { 1: 'ases', 2: 'tontos', 3: 'trenes', 4: 'cuadras', 5: 'quintas', 6: 'sextas' },
  label: 'Nombres chilenos',
  hint: 'Ases, tontos, trenes, cuadras, quintas y sextas.',
};

/* ================================================================== */
/* ESPAÑOL                                                             */
/* ================================================================== */
const ES = {
  // Los nombres de cada pinta, en singular y en plural ("un as", "cuatro cincos")
  pintaOne: { 1: 'as', 2: 'dos', 3: 'tres', 4: 'cuatro', 5: 'cinco', 6: 'seis' },
  pintaMany: { 1: 'ases', 2: 'doses', 3: 'treses', 4: 'cuatros', 5: 'cincos', 6: 'seises' },
  ui: {
    // estáticos (index.html)
    docTitle: 'Dudo 🎲 · Juegos de Salón', gameChip: '🎲 Dudo', menu: '‹ Menú',
    title: 'Dudo', lead: 'Apuesta cuántos dados hay en toda la mesa viendo solo los tuyos.',
    rulesSummary: '🎲 ¿Cómo se juega?',
    modesTitle: '¿Cómo van a jugar?',
    modeLocal: '📱 Un celular', modeLocalHint: 'Se pasan el celular y cada uno mira sus dados a escondidas.',
    modeOnline: '📡 Varios celulares', modeOnlineHint: 'Cada uno juega en su celular y nadie ve los dados ajenos.',
    modeCpu: '🤖 Contra el celular', modeCpuHint: 'Un duelo contra el celular, que solo mira sus propios dados.',
    // Sala (varios celulares)
    setupOnline: 'Sala de Dudo', invitedTitle: '¡Invitado a jugar!',
    yourNameLabel: 'Tu nombre', create: '🎲 Crear sala', join: 'Unirse',
    joinTitle: '¿Te pasaron un código?', codePlaceholder: 'CÓDIGO',
    invited: '📩 Sala {code}', invitedHint: 'Escribe tu nombre y entra. La partida la arma quien creó la sala.',
    lobbyTitle: 'Sala creada', lobbyCode: 'Código', lobbyShare: 'Dile el código al resto o que escaneen el QR.',
    lobbyPlayers: 'En la sala', lobbyStart: '¡A jugar!', lobbyNeedMore: 'Faltan jugadores',
    lobbyWaitHost: 'Esperando a que {name} parta la partida', lobbyCancel: 'Cancelar la sala', lobbyLeave: 'Salir de la sala',
    shareLink: '📤 Compartir link', copyLink: '📋 Copiar link', copied: '¡Copiado!',
    rematch: '🔁 Revancha', changeMode: 'Cambiar de modo',
    waitDice: 'Esperando los dados de {name}…', waitRoll: 'Tirando los dados…',
    errName: 'Escribe tu nombre.', errCode: 'El código son cuatro letras.',
    errNotFound: 'No existe esa sala. Revisa el código.', errFull: 'La sala ya está llena.',
    errExpired: 'Esa sala ya venció.', errOtherGame: 'Ese código es de otro juego.',
    errNet: 'No se pudo conectar. ¿Hay internet?',
    errOffline: 'No se pudo abrir la sala. Puede ser tu internet o que haya mucha gente jugando. Intenta nuevamente en unos minutos o juega en modo de un solo celular sin conexión a internet.',
    errTooMany: 'Abriste muchas salas seguidas. Espera un ratito y prueba de nuevo.',
    errSecure: 'Para jugar en varios celulares hace falta una conexión segura (https).',
    chatTitle: 'Chat de la sala', chatOpen: 'Abrir el chat', chatClose: 'Cerrar el chat', chatSend: 'Enviar',
    chatPlaceholder: 'Escribe algo…', chatEmpty: 'Acá pueden picarse mientras apuestan. Se borra cuando termina la sala.',
    whoPlays: '¿Quiénes juegan?',
    setupHint: 'Anótense en el orden en que están sentados, hacia la derecha.',
    addPlayer: '+ Agregar jugador', start: '¡A jugar!',
    calzarLabel: 'Se puede calzar', calzarHint: 'Acertar la cantidad exacta recupera un dado.',
    endAgain: '¡Otra partida!', changePlayers: 'Cambiar jugadores', backMenu: 'Volver al menú',
    historyTitle: '🎲 Cómo se fue dando',
    // dinámicos (game.js)
    resumeTitle: '⏯ Hay una partida a medias', resumeText: 'Ronda {round}. Le tocaba a {name}.', resume: 'Continuar', delete: 'Borrar',
    playerPlaceholder: 'Jugador {n}', removePlayer: 'Quitar jugador', maxPlayers: 'Máximo {n} jugadores',
    errMin: 'Se necesitan al menos {n} jugadores.', errNames: 'Todos los jugadores necesitan un nombre.', errDup: 'Hay nombres repetidos. Pónganse apodos.',
    yourName: 'Tu nombre', cpuName: 'Celular',
    rules: [
      'Cada uno tiene cinco dados y ve solo los suyos.',
      'Se apuesta cuántos dados de una pinta hay <b>en toda la mesa</b>, como "cuatro quintas".',
      'Los <b>ases son comodín</b>: cuentan como la pinta apostada.',
      'El siguiente sube la apuesta (más dados, o los mismos con pinta mayor) o dice "dudo".',
      'Pasar a ases pide la mitad de los dados, y salir de ases, el doble más uno.',
      'Al dudar se cuentan los dados: si hay los apostados o más, pierde un dado quien dudó, y si no, quien apostó.',
      '<b>Calzar</b> es decir que la cantidad es exacta: si aciertas recuperas un dado y si no, pierdes uno. Se puede con tres jugadores o más y desde la mitad de los dados.',
      'Quien se queda sin dados sale. Gana el último con dados.',
    ],
    diceLeft: '{n} dados', diceLeftOne: '1 dado',
    tableDice: '{n} dados en la mesa',
    yourDice: 'Tus dados', turnOf: 'Le toca a', yourTurn: '¡Te toca!',
    aceWild: 'Los ases son comodín',
    opens: 'Abre la ronda: apuesta lo que quieras.',
    standing: '{name} dijo', standingYou: 'Dijiste',
    pickPinta: 'Elige la pinta', pickAmount: '¿Cuántos hay en la mesa?',
    bidDo: 'Apuesto {n} {pinta}', bidNothing: 'Apostar', dudoDo: '¡Dudo!', calzaDo: '¡Calzo!',
    dudoHint: 'Dudar de {n} {pinta}', calzaHint: 'Decir que son {n} justos',
    round: 'Ronda {n}',
    // Destape
    revealTitle: 'Se destapa la mesa', revealCount: 'Había {n} {pinta}', revealCountOne: 'Había 1 {pinta}',
    saidDudo: '{name} dudó de {n} {pinta}', saidCalza: '{name} calzó {n} {pinta}',
    losesDie: '{name} pierde un dado', gainsDie: '{name} recupera un dado',
    isOut: '{name} se quedó sin dados', exactYes: '¡Justo!', exactNo: 'No era exacto',
    goOn: 'Toca para seguir',
    verified: 'Dados verificados ✅', notVerified: '⚠️ Los dados de {name} no coinciden',
    // Pase y pantalla tapada
    hoPass: 'Pásale el celular a', hoReady: '¡Listo, soy yo!',
    coverLabel: 'Que nadie más mire. Son los dados de', coverTap: 'Ver mis dados',
    // Final
    winner: '¡Ganó {name}!', winnerYou: '¡Ganaste!', loserYou: 'Te quedaste sin dados',
    endStats: '{rounds} rondas', endStatsOne: 'Una sola ronda',
    histDudo: '{who} dudó de {n} {pinta} · había {count}', histCalza: '{who} calzó {n} {pinta} · había {count}',
    histLost: '{name} −1', histGained: '{name} +1',
  },
};

/* ================================================================== */
/* ENGLISH                                                             */
/* ================================================================== */
const EN = {
  pintaOne: { 1: 'ace', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six' },
  pintaMany: { 1: 'aces', 2: 'twos', 3: 'threes', 4: 'fours', 5: 'fives', 6: 'sixes' },
  ui: {
    docTitle: 'Liar\'s Dice 🎲 · Party Games', gameChip: '🎲 Liar\'s Dice', menu: '‹ Menu',
    title: 'Liar\'s Dice', lead: 'Bid how many dice are on the whole table while seeing only your own.',
    rulesSummary: '🎲 How do you play?',
    modesTitle: 'How are you playing?',
    modeLocal: '📱 One phone', modeLocalHint: 'Pass the phone around and each player peeks at their dice in secret.',
    modeOnline: '📡 Several phones', modeOnlineHint: 'Everyone plays on their own phone and nobody sees anyone else\'s dice.',
    modeCpu: '🤖 Versus the phone', modeCpuHint: 'A duel against the phone, which only looks at its own dice.',
    setupOnline: 'Liar\'s Dice room', invitedTitle: 'You\'re invited!',
    yourNameLabel: 'Your name', create: '🎲 Create room', join: 'Join',
    joinTitle: 'Got a code?', codePlaceholder: 'CODE',
    invited: '📩 Room {code}', invitedHint: 'Type your name and join. Whoever created the room starts the game.',
    lobbyTitle: 'Room created', lobbyCode: 'Code', lobbyShare: 'Tell the others the code or let them scan the QR.',
    lobbyPlayers: 'In the room', lobbyStart: 'Play!', lobbyNeedMore: 'Need more players',
    lobbyWaitHost: 'Waiting for {name} to start the game', lobbyCancel: 'Cancel the room', lobbyLeave: 'Leave the room',
    shareLink: '📤 Share link', copyLink: '📋 Copy link', copied: 'Copied!',
    rematch: '🔁 Rematch', changeMode: 'Change mode',
    waitDice: 'Waiting for {name}\'s dice…', waitRoll: 'Rolling the dice…',
    errName: 'Type your name.', errCode: 'The code is four letters.',
    errNotFound: 'No such room. Check the code.', errFull: 'The room is full.',
    errExpired: 'That room has expired.', errOtherGame: 'That code belongs to another game.',
    errNet: 'Couldn\'t connect. Is there internet?',
    errOffline: 'The room couldn\'t be opened. It may be your internet or a lot of people playing. Try again in a few minutes, or play on one phone with no internet at all.',
    errTooMany: 'You opened too many rooms in a row. Wait a bit and try again.',
    errSecure: 'Playing on several phones needs a secure connection (https).',
    chatTitle: 'Room chat', chatOpen: 'Open the chat', chatClose: 'Close the chat', chatSend: 'Send',
    chatPlaceholder: 'Say something…', chatEmpty: 'Talk trash while you bid. It goes away when the room ends.',
    whoPlays: 'Who\'s playing?',
    setupHint: 'Sign up in the order you\'re sitting, going to the right.',
    addPlayer: '+ Add player', start: 'Play!',
    calzarLabel: 'Spot on allowed', calzarHint: 'Calling the exact count wins a die back.',
    endAgain: 'Another game!', changePlayers: 'Change players', backMenu: 'Back to menu',
    historyTitle: '🎲 How it went',
    resumeTitle: '⏯ There\'s a game in progress', resumeText: 'Round {round}. It was {name}\'s turn.', resume: 'Continue', delete: 'Delete',
    playerPlaceholder: 'Player {n}', removePlayer: 'Remove player', maxPlayers: 'Up to {n} players',
    errMin: 'You need at least {n} players.', errNames: 'Every player needs a name.', errDup: 'Some names are repeated. Use nicknames.',
    yourName: 'Your name', cpuName: 'Phone',
    rules: [
      'Everyone has five dice and sees only their own.',
      'You bid how many dice of a face there are <b>on the whole table</b>, like "four fives".',
      '<b>Aces are wild</b>: they count as the face that was bid.',
      'The next player raises the bid (more dice, or the same count on a higher face) or calls "liar".',
      'Switching to aces takes half the dice, and switching back from aces, double plus one.',
      'On a call the dice are counted: if there are as many as bid or more, the caller loses a die, and if not, the bidder does.',
      '<b>Spot on</b> means the count is exact: get it right and you win a die back, and if not, you lose one. It takes three players or more and a bid of at least half the dice.',
      'Run out of dice and you\'re out. The last one with dice wins.',
    ],
    diceLeft: '{n} dice', diceLeftOne: '1 die',
    tableDice: '{n} dice on the table',
    yourDice: 'Your dice', turnOf: 'It\'s on', yourTurn: 'Your turn!',
    aceWild: 'Aces are wild',
    opens: 'You open the round: bid whatever you like.',
    standing: '{name} said', standingYou: 'You said',
    pickPinta: 'Pick the face', pickAmount: 'How many on the table?',
    bidDo: 'Bid {n} {pinta}', bidNothing: 'Bid', dudoDo: 'Liar!', calzaDo: 'Spot on!',
    dudoHint: 'Call {n} {pinta}', calzaHint: 'Say it\'s exactly {n}',
    round: 'Round {n}',
    revealTitle: 'Open them up', revealCount: 'There were {n} {pinta}', revealCountOne: 'There was 1 {pinta}',
    saidDudo: '{name} called {n} {pinta}', saidCalza: '{name} said {n} {pinta} exactly',
    losesDie: '{name} loses a die', gainsDie: '{name} wins a die back',
    isOut: '{name} is out of dice', exactYes: 'Exactly!', exactNo: 'Not exact',
    goOn: 'Tap to go on',
    verified: 'Dice verified ✅', notVerified: '⚠️ {name}\'s dice don\'t match',
    hoPass: 'Pass the phone to', hoReady: 'Got it, that\'s me!',
    coverLabel: 'Nobody else look. These dice belong to', coverTap: 'See my dice',
    winner: '{name} wins!', winnerYou: 'You win!', loserYou: 'You ran out of dice',
    endStats: '{rounds} rounds', endStatsOne: 'A single round',
    histDudo: '{who} called {n} {pinta} · there were {count}', histCalza: '{who} said {n} {pinta} exactly · there were {count}',
    histLost: '{name} −1', histGained: '{name} +1',
  },
};

/* ================================================================== */
/* PORTUGUÊS (BR)                                                      */
/* ================================================================== */
const PT = {
  pintaOne: { 1: 'ás', 2: 'dois', 3: 'três', 4: 'quatro', 5: 'cinco', 6: 'seis' },
  pintaMany: { 1: 'ases', 2: 'dois', 3: 'três', 4: 'quatros', 5: 'cincos', 6: 'seis' },
  ui: {
    docTitle: 'Dado Mentiroso 🎲 · Jogos de Salão', gameChip: '🎲 Dado Mentiroso', menu: '‹ Menu',
    title: 'Dado Mentiroso', lead: 'Aposte quantos dados tem na mesa inteira vendo só os seus.',
    rulesSummary: '🎲 Como se joga?',
    modesTitle: 'Como vocês vão jogar?',
    modeLocal: '📱 Um celular', modeLocalHint: 'Vocês passam o celular e cada um olha seus dados escondido.',
    modeOnline: '📡 Vários celulares', modeOnlineHint: 'Cada um joga no seu celular e ninguém vê os dados dos outros.',
    modeCpu: '🤖 Contra o celular', modeCpuHint: 'Um duelo contra o celular, que só olha os próprios dados.',
    setupOnline: 'Sala de Dado Mentiroso', invitedTitle: 'Você foi convidado!',
    yourNameLabel: 'Seu nome', create: '🎲 Criar sala', join: 'Entrar',
    joinTitle: 'Te passaram um código?', codePlaceholder: 'CÓDIGO',
    invited: '📩 Sala {code}', invitedHint: 'Escreva seu nome e entre. Quem criou a sala é quem começa a partida.',
    lobbyTitle: 'Sala criada', lobbyCode: 'Código', lobbyShare: 'Diga o código aos outros ou deixe eles escanearem o QR.',
    lobbyPlayers: 'Na sala', lobbyStart: 'Bora jogar!', lobbyNeedMore: 'Faltam jogadores',
    lobbyWaitHost: 'Esperando {name} começar a partida', lobbyCancel: 'Cancelar a sala', lobbyLeave: 'Sair da sala',
    shareLink: '📤 Compartilhar link', copyLink: '📋 Copiar link', copied: 'Copiado!',
    rematch: '🔁 Revanche', changeMode: 'Trocar de modo',
    waitDice: 'Esperando os dados de {name}…', waitRoll: 'Jogando os dados…',
    errName: 'Escreva seu nome.', errCode: 'O código são quatro letras.',
    errNotFound: 'Essa sala não existe. Confira o código.', errFull: 'A sala já está cheia.',
    errExpired: 'Essa sala já venceu.', errOtherGame: 'Esse código é de outro jogo.',
    errNet: 'Não deu pra conectar. Tem internet?',
    errOffline: 'Não deu pra abrir a sala. Pode ser sua internet ou muita gente jogando. Tente de novo em alguns minutos, ou jogue em um celular só, sem internet.',
    errTooMany: 'Você abriu muitas salas seguidas. Espere um pouco e tente de novo.',
    errSecure: 'Pra jogar em vários celulares precisa de conexão segura (https).',
    chatTitle: 'Chat da sala', chatOpen: 'Abrir o chat', chatClose: 'Fechar o chat', chatSend: 'Enviar',
    chatPlaceholder: 'Escreva algo…', chatEmpty: 'Provoquem à vontade enquanto apostam. Some quando a sala acabar.',
    whoPlays: 'Quem vai jogar?',
    setupHint: 'Cadastrem-se na ordem em que estão sentados, para a direita.',
    addPlayer: '+ Adicionar jogador', start: 'Bora jogar!',
    calzarLabel: 'Pode cravar', calzarHint: 'Acertar a quantidade exata devolve um dado.',
    endAgain: 'Mais uma partida!', changePlayers: 'Trocar jogadores', backMenu: 'Voltar ao menu',
    historyTitle: '🎲 Como foi',
    resumeTitle: '⏯ Tem uma partida pela metade', resumeText: 'Rodada {round}. Era a vez de {name}.', resume: 'Continuar', delete: 'Apagar',
    playerPlaceholder: 'Jogador {n}', removePlayer: 'Tirar jogador', maxPlayers: 'No máximo {n} jogadores',
    errMin: 'São necessários pelo menos {n} jogadores.', errNames: 'Todo jogador precisa de um nome.', errDup: 'Tem nomes repetidos. Usem apelidos.',
    yourName: 'Seu nome', cpuName: 'Celular',
    rules: [
      'Cada um tem cinco dados e vê só os seus.',
      'Aposta-se quantos dados de uma face tem <b>na mesa inteira</b>, como "quatro cincos".',
      'Os <b>ases são curinga</b>: contam como a face apostada.',
      'O próximo aumenta a aposta (mais dados, ou os mesmos com face maior) ou fala "duvido".',
      'Passar para ases pede a metade dos dados, e sair dos ases, o dobro mais um.',
      'Na dúvida contam-se os dados: se tem o apostado ou mais, perde um dado quem duvidou, e se não, quem apostou.',
      '<b>Cravar</b> é dizer que a quantidade é exata: se acertar, ganha um dado de volta, e se não, perde um. Pode com três jogadores ou mais e a partir da metade dos dados.',
      'Quem fica sem dados sai. Ganha o último com dados.',
    ],
    diceLeft: '{n} dados', diceLeftOne: '1 dado',
    tableDice: '{n} dados na mesa',
    yourDice: 'Seus dados', turnOf: 'É a vez de', yourTurn: 'É a sua vez!',
    aceWild: 'Os ases são curinga',
    opens: 'Você abre a rodada: aposte o que quiser.',
    standing: '{name} falou', standingYou: 'Você falou',
    pickPinta: 'Escolha a face', pickAmount: 'Quantos tem na mesa?',
    bidDo: 'Aposto {n} {pinta}', bidNothing: 'Apostar', dudoDo: 'Duvido!', calzaDo: 'Cravo!',
    dudoHint: 'Duvidar de {n} {pinta}', calzaHint: 'Dizer que são {n} certinhos',
    round: 'Rodada {n}',
    revealTitle: 'Abre a mesa', revealCount: 'Tinha {n} {pinta}', revealCountOne: 'Tinha 1 {pinta}',
    saidDudo: '{name} duvidou de {n} {pinta}', saidCalza: '{name} cravou {n} {pinta}',
    losesDie: '{name} perde um dado', gainsDie: '{name} ganha um dado',
    isOut: '{name} ficou sem dados', exactYes: 'Certinho!', exactNo: 'Não era exato',
    goOn: 'Toque para seguir',
    verified: 'Dados verificados ✅', notVerified: '⚠️ Os dados de {name} não batem',
    hoPass: 'Passe o celular para', hoReady: 'Pronto, sou eu!',
    coverLabel: 'Ninguém mais olhe. Os dados são de', coverTap: 'Ver meus dados',
    winner: '{name} ganhou!', winnerYou: 'Você ganhou!', loserYou: 'Você ficou sem dados',
    endStats: '{rounds} rodadas', endStatsOne: 'Uma rodada só',
    histDudo: '{who} duvidou de {n} {pinta} · tinha {count}', histCalza: '{who} cravou {n} {pinta} · tinha {count}',
    histLost: '{name} −1', histGained: '{name} +1',
  },
};

/* ================================================================== */
/* DEUTSCH                                                             */
/* ================================================================== */
const DE = {
  // Las caras como se dicen en la mesa ("ein Fünfer", "drei Fünfer"); los ases son comodines
  pintaOne: { 1: 'Ass', 2: 'Zweier', 3: 'Dreier', 4: 'Vierer', 5: 'Fünfer', 6: 'Sechser' },
  pintaMany: { 1: 'Asse', 2: 'Zweier', 3: 'Dreier', 4: 'Vierer', 5: 'Fünfer', 6: 'Sechser' },
  ui: {
    docTitle: 'Lügenwürfel 🎲 · Salonspiele', gameChip: '🎲 Lügenwürfel', menu: '‹ Menü',
    title: 'Lügenwürfel', lead: 'Wette, wie viele Würfel auf dem ganzen Tisch liegen – du siehst nur deine eigenen.',
    rulesSummary: '🎲 Wie spielt man?',
    modesTitle: 'Wie wollt ihr spielen?',
    modeLocal: '📱 Ein Handy', modeLocalHint: 'Ihr gebt das Handy herum und jeder schaut heimlich auf seine Würfel.',
    modeOnline: '📡 Mehrere Handys', modeOnlineHint: 'Jeder spielt auf seinem Handy und niemand sieht die Würfel der anderen.',
    modeCpu: '🤖 Gegen das Handy', modeCpuHint: 'Ein Duell gegen das Handy, das nur seine eigenen Würfel sieht.',
    setupOnline: 'Lügenwürfel-Raum', invitedTitle: 'Du bist eingeladen!',
    yourNameLabel: 'Dein Name', create: '🎲 Raum erstellen', join: 'Beitreten',
    joinTitle: 'Hast du einen Code?', codePlaceholder: 'CODE',
    invited: '📩 Raum {code}', invitedHint: 'Gib deinen Namen ein und komm rein. Wer den Raum erstellt hat, startet das Spiel.',
    lobbyTitle: 'Raum erstellt', lobbyCode: 'Code', lobbyShare: 'Sag den anderen den Code oder lass sie den QR-Code scannen.',
    lobbyPlayers: 'Im Raum', lobbyStart: 'Los geht’s!', lobbyNeedMore: 'Zu wenig Spieler',
    lobbyWaitHost: 'Warte, bis {name} das Spiel startet', lobbyCancel: 'Raum auflösen', lobbyLeave: 'Raum verlassen',
    shareLink: '📤 Link teilen', copyLink: '📋 Link kopieren', copied: 'Kopiert!',
    rematch: '🔁 Revanche', changeMode: 'Modus wechseln',
    waitDice: 'Warte auf die Würfel von {name}…', waitRoll: 'Die Würfel rollen…',
    errName: 'Gib deinen Namen ein.', errCode: 'Der Code hat vier Buchstaben.',
    errNotFound: 'Diesen Raum gibt es nicht. Prüf den Code.', errFull: 'Der Raum ist schon voll.',
    errExpired: 'Dieser Raum ist abgelaufen.', errOtherGame: 'Dieser Code gehört zu einem anderen Spiel.',
    errNet: 'Keine Verbindung. Hast du Internet?',
    errOffline: 'Der Raum ließ sich nicht öffnen. Vielleicht liegt es an deinem Internet oder es spielen gerade sehr viele. Versuch es in ein paar Minuten nochmal oder spiel auf einem Handy ganz ohne Internet.',
    errTooMany: 'Du hast zu viele Räume hintereinander geöffnet. Warte kurz und versuch es nochmal.',
    errSecure: 'Für mehrere Handys braucht es eine sichere Verbindung (https).',
    chatTitle: 'Raum-Chat', chatOpen: 'Chat öffnen', chatClose: 'Chat schließen', chatSend: 'Senden',
    chatPlaceholder: 'Schreib was…', chatEmpty: 'Hier dürft ihr euch beim Wetten necken. Alles wird gelöscht, wenn der Raum endet.',
    whoPlays: 'Wer spielt mit?',
    setupHint: 'Tragt euch in der Sitzreihenfolge ein, nach rechts herum.',
    addPlayer: '+ Spieler hinzufügen', start: 'Los geht’s!',
    calzarLabel: 'Punktlandung erlaubt', calzarHint: 'Wer die genaue Anzahl trifft, bekommt einen Würfel zurück.',
    endAgain: 'Noch eine Runde!', changePlayers: 'Spieler ändern', backMenu: 'Zurück zum Menü',
    historyTitle: '🎲 So lief es',
    resumeTitle: '⏯ Da ist noch ein Spiel offen', resumeText: 'Runde {round}. {name} war dran.', resume: 'Weiter', delete: 'Löschen',
    playerPlaceholder: 'Spieler {n}', removePlayer: 'Spieler entfernen', maxPlayers: 'Höchstens {n} Spieler',
    errMin: 'Ihr braucht mindestens {n} Spieler.', errNames: 'Alle Spieler brauchen einen Namen.', errDup: 'Manche Namen sind doppelt. Nehmt Spitznamen.',
    yourName: 'Dein Name', cpuName: 'Handy',
    rules: [
      'Jeder hat fünf Würfel und sieht nur seine eigenen.',
      'Man wettet, wie viele Würfel einer Augenzahl <b>auf dem ganzen Tisch</b> liegen, etwa „vier Fünfer“.',
      '<b>Asse sind Joker</b>: Sie zählen als die gewettete Augenzahl.',
      'Der Nächste erhöht (mehr Würfel oder gleich viele mit höherer Zahl) oder zweifelt an.',
      'Wer auf Asse wechselt, braucht nur die Hälfte der Würfel, und wer von Assen zurückwechselt, das Doppelte plus eins.',
      'Beim Anzweifeln wird gezählt: Liegen so viele oder mehr da, verliert der Zweifler einen Würfel, sonst der, der gewettet hat.',
      'Bei der <b>Punktlandung</b> sagst du, dass die Zahl genau stimmt: Liegst du richtig, bekommst du einen Würfel zurück, sonst verlierst du einen. Das geht ab drei Spielern und ab der Hälfte der Würfel.',
      'Wer keine Würfel mehr hat, scheidet aus. Der Letzte mit Würfeln gewinnt.',
    ],
    diceLeft: '{n} Würfel', diceLeftOne: '1 Würfel',
    tableDice: '{n} Würfel auf dem Tisch',
    yourDice: 'Deine Würfel', turnOf: 'Dran ist', yourTurn: 'Du bist dran!',
    aceWild: 'Asse sind Joker',
    opens: 'Du eröffnest die Runde: Wette, was du willst.',
    standing: '{name} sagte', standingYou: 'Du sagtest',
    pickPinta: 'Wähle die Zahl', pickAmount: 'Wie viele liegen da?',
    bidDo: 'Ich sage {n} {pinta}', bidNothing: 'Wetten', dudoDo: 'Zweifeln!', calzaDo: 'Genau!',
    dudoHint: '{n} {pinta} anzweifeln', calzaHint: 'Sagen, dass es genau {n} sind',
    round: 'Runde {n}',
    revealTitle: 'Würfel aufdecken', revealCount: 'Es waren {n} {pinta}', revealCountOne: 'Es war 1 {pinta}',
    saidDudo: '{name} zweifelte {n} {pinta} an', saidCalza: '{name} sagte genau {n} {pinta}',
    losesDie: '{name} verliert einen Würfel', gainsDie: '{name} bekommt einen Würfel zurück',
    isOut: '{name} hat keine Würfel mehr', exactYes: 'Genau!', exactNo: 'Nicht genau',
    goOn: 'Tippen für weiter',
    verified: 'Würfel geprüft ✅', notVerified: '⚠️ Die Würfel von {name} stimmen nicht',
    hoPass: 'Gib das Handy an', hoReady: 'Okay, das bin ich!',
    coverLabel: 'Alle anderen wegschauen. Das sind die Würfel von', coverTap: 'Meine Würfel',
    winner: '{name} gewinnt!', winnerYou: 'Du gewinnst!', loserYou: 'Du hast keine Würfel mehr',
    endStats: '{rounds} Runden', endStatsOne: 'Nur eine Runde',
    histDudo: '{who} zweifelte {n} {pinta} an · es waren {count}', histCalza: '{who} sagte genau {n} {pinta} · es waren {count}',
    histLost: '{name} −1', histGained: '{name} +1',
  },
};

export const LOCALES = { es: ES, en: EN, pt: PT, de: DE };
