/**
 * Mazo Brasil: hitos del país, del descubrimiento a la COP30, mezclando historia,
 * tele, música, cine, farándula y vida cotidiana. Formato: { id, year, emoji, es, en, pt }.
 * Solo van años indiscutibles: si la fecha se discute, la carta no entra.
 */
export const BRASIL = [
  { id: 'br-cabral', year: 1500, emoji: '⛵', es: 'Pedro Álvares Cabral llega a Brasil', en: 'Pedro Álvares Cabral reaches Brazil', pt: 'Pedro Álvares Cabral chega ao Brasil' },
  { id: 'br-salvador', year: 1549, emoji: '🏙️', es: 'Se funda Salvador, la primera capital', en: 'Salvador, the first capital, is founded', pt: 'É fundada Salvador, a primeira capital' },
  { id: 'br-sao-paulo', year: 1554, emoji: '⛪', es: 'Los jesuitas fundan São Paulo', en: 'Jesuits found São Paulo', pt: 'Os jesuítas fundam São Paulo' },
  { id: 'br-rio', year: 1565, emoji: '🏖️', es: 'Se funda Río de Janeiro', en: 'Rio de Janeiro is founded', pt: 'É fundado o Rio de Janeiro' },
  { id: 'br-holandeses', year: 1630, emoji: '🇳🇱', es: 'Los holandeses toman Pernambuco', en: 'The Dutch seize Pernambuco', pt: 'Os holandeses tomam Pernambuco' },
  { id: 'br-zumbi', year: 1695, emoji: '✊🏿', es: 'Muere Zumbi, el líder del quilombo de Palmares', en: 'Zumbi, leader of the Palmares quilombo, is killed', pt: 'Morre Zumbi, o líder do quilombo dos Palmares' },
  { id: 'br-capital-rio', year: 1763, emoji: '👑', es: 'Río de Janeiro pasa a ser la capital de la colonia', en: 'Rio de Janeiro becomes the colonial capital', pt: 'O Rio de Janeiro vira a capital da colônia' },
  { id: 'br-tiradentes', year: 1792, emoji: '🪢', es: 'Ejecutan a Tiradentes en Río', en: 'Tiradentes is executed in Rio', pt: 'Tiradentes é executado no Rio' },
  { id: 'br-familia-real', year: 1808, emoji: '🚢', es: 'La familia real portuguesa se instala en Río', en: 'The Portuguese royal family settles in Rio', pt: 'A família real portuguesa se instala no Rio' },
  { id: 'br-independencia', year: 1822, emoji: '🇧🇷', es: 'Pedro I grita la independencia a orillas del Ipiranga', en: 'Pedro I proclaims independence on the banks of the Ipiranga', pt: 'Dom Pedro I dá o grito do Ipiranga' },
  { id: 'br-constitucion-1824', year: 1824, emoji: '📜', es: 'Se otorga la primera Constitución de Brasil', en: 'Brazil gets its first Constitution', pt: 'É outorgada a primeira Constituição do Brasil' },
  { id: 'br-pedro-ii', year: 1840, emoji: '👑', es: 'Pedro II asume el trono con 14 años', en: 'Pedro II takes the throne at 14', pt: 'Dom Pedro II assume o trono aos 14 anos' },
  { id: 'br-guarani', year: 1870, emoji: '🎼', es: 'Carlos Gomes estrena la ópera O Guarani en Milán', en: 'Carlos Gomes premieres the opera O Guarani in Milan', pt: 'Carlos Gomes estreia a ópera O Guarani em Milão' },
  { id: 'br-paraguay', year: 1870, emoji: '⚔️', es: 'Termina la Guerra del Paraguay', en: 'The Paraguayan War ends', pt: 'Termina a Guerra do Paraguai' },
  { id: 'br-corcovado', year: 1884, emoji: '🚞', es: 'Se inaugura el tren del Corcovado', en: 'The Corcovado railway opens', pt: 'É inaugurado o trem do Corcovado' },
  { id: 'br-lei-aurea', year: 1888, emoji: '⛓️', es: 'La princesa Isabel firma la Ley Áurea y abole la esclavitud', en: 'Princess Isabel signs the Golden Law abolishing slavery', pt: 'A princesa Isabel assina a Lei Áurea e abole a escravidão' },
  { id: 'br-republica', year: 1889, emoji: '🎖️', es: 'Se proclama la República', en: 'The Republic is proclaimed', pt: 'É proclamada a República' },
  { id: 'br-canudos', year: 1897, emoji: '🔥', es: 'El ejército destruye Canudos', en: 'The army destroys Canudos', pt: 'O exército destrói Canudos' },
  { id: 'br-dom-casmurro', year: 1899, emoji: '📖', es: 'Machado de Assis publica Dom Casmurro', en: 'Machado de Assis publishes Dom Casmurro', pt: 'Machado de Assis publica Dom Casmurro' },
  { id: 'br-vacina', year: 1904, emoji: '💉', es: 'La Revuelta de la Vacuna sacude Río', en: 'The Vaccine Revolt shakes Rio', pt: 'A Revolta da Vacina sacode o Rio' },
  { id: 'br-santos-dumont', year: 1906, emoji: '✈️', es: 'Santos Dumont vuela el 14-bis en París', en: 'Santos Dumont flies the 14-bis in Paris', pt: 'Santos Dumont voa com o 14-bis em Paris' },
  { id: 'br-kasato-maru', year: 1908, emoji: '🇯🇵', es: 'Llega el Kasato Maru con los primeros inmigrantes japoneses', en: 'The Kasato Maru brings the first Japanese immigrants', pt: 'Chega o Kasato Maru com os primeiros imigrantes japoneses' },
  { id: 'br-bondinho', year: 1912, emoji: '🚡', es: 'Empieza a funcionar el teleférico del Pan de Azúcar', en: 'The Sugarloaf cable car starts running', pt: 'Começa a funcionar o bondinho do Pão de Açúcar' },
  { id: 'br-pelo-telefone', year: 1917, emoji: '📞', es: 'Se graba Pelo Telefone, el primer samba', en: 'Pelo Telefone, the first recorded samba, is cut', pt: 'É gravado Pelo Telefone, o primeiro samba' },
  { id: 'br-narizinho', year: 1920, emoji: '🌽', es: 'Monteiro Lobato publica el primer libro del Sítio do Picapau Amarelo', en: 'Monteiro Lobato publishes the first Sítio do Picapau Amarelo book', pt: 'Monteiro Lobato publica o primeiro livro do Sítio do Picapau Amarelo' },
  { id: 'br-guarana', year: 1921, emoji: '🥤', es: 'Sale a la venta el Guaraná Antarctica', en: 'Guaraná Antarctica goes on sale', pt: 'O Guaraná Antarctica chega às prateleiras' },
  { id: 'br-semana-22', year: 1922, emoji: '🎨', es: 'La Semana de Arte Moderno revoluciona São Paulo', en: 'The Modern Art Week shakes up São Paulo', pt: 'A Semana de Arte Moderna revoluciona São Paulo' },
  { id: 'br-copacabana-palace', year: 1923, emoji: '🏨', es: 'Abre el Copacabana Palace', en: 'The Copacabana Palace opens', pt: 'Abre o Copacabana Palace' },
  { id: 'br-vargas', year: 1930, emoji: '🎩', es: 'Getúlio Vargas llega al poder con una revolución', en: 'Getúlio Vargas takes power in a revolution', pt: 'Getúlio Vargas chega ao poder com uma revolução' },
  { id: 'br-cristo', year: 1931, emoji: '🗽', es: 'Se inaugura el Cristo Redentor', en: 'Christ the Redeemer is inaugurated', pt: 'É inaugurado o Cristo Redentor' },
  { id: 'br-1932', year: 1932, emoji: '🪖', es: 'São Paulo se levanta en la Revolución Constitucionalista', en: 'São Paulo rises in the Constitutionalist Revolution', pt: 'São Paulo se levanta na Revolução Constitucionalista' },
  { id: 'br-estado-novo', year: 1937, emoji: '📻', es: 'Vargas instaura el Estado Novo', en: 'Vargas establishes the Estado Novo', pt: 'Vargas instaura o Estado Novo' },
  { id: 'br-aquarela', year: 1939, emoji: '🎶', es: 'Ary Barroso compone Aquarela do Brasil', en: 'Ary Barroso writes Aquarela do Brasil', pt: 'Ary Barroso compõe Aquarela do Brasil' },
  { id: 'br-carmen-miranda', year: 1939, emoji: '🍌', es: 'Carmen Miranda se va a conquistar Hollywood', en: 'Carmen Miranda leaves to conquer Hollywood', pt: 'Carmen Miranda vai conquistar Hollywood' },
  { id: 'br-pacaembu', year: 1940, emoji: '🏟️', es: 'Se inaugura el estadio Pacaembu', en: 'The Pacaembu stadium opens', pt: 'É inaugurado o estádio do Pacaembu' },
  { id: 'br-guerra', year: 1942, emoji: '🎖️', es: 'Brasil entra en la Segunda Guerra Mundial', en: 'Brazil enters World War II', pt: 'O Brasil entra na Segunda Guerra Mundial' },
  { id: 'br-clt', year: 1943, emoji: '📋', es: 'Vargas firma la CLT, las leyes del trabajo', en: 'Vargas signs the CLT labour code', pt: 'Vargas assina a CLT' },
  { id: 'br-asa-branca', year: 1947, emoji: '🪗', es: 'Luiz Gonzaga graba Asa Branca', en: 'Luiz Gonzaga records Asa Branca', pt: 'Luiz Gonzaga grava Asa Branca' },
  { id: 'br-tv-tupi', year: 1950, emoji: '📺', es: 'TV Tupi enciende la primera televisión de Brasil', en: 'TV Tupi switches on Brazil’s first television', pt: 'A TV Tupi liga a primeira televisão do Brasil' },
  { id: 'br-maracana', year: 1950, emoji: '🏟️', es: 'Se inaugura el Maracaná para el Mundial', en: 'The Maracanã opens for the World Cup', pt: 'O Maracanã é inaugurado para a Copa' },
  { id: 'br-petrobras', year: 1953, emoji: '🛢️', es: 'Nace Petrobras', en: 'Petrobras is founded', pt: 'Nasce a Petrobras' },
  { id: 'br-vargas-muerte', year: 1954, emoji: '🕯️', es: 'Getúlio Vargas se quita la vida en el Palacio del Catete', en: 'Getúlio Vargas takes his own life at the Catete Palace', pt: 'Getúlio Vargas tira a própria vida no Palácio do Catete' },
  { id: 'br-jk', year: 1956, emoji: '🎩', es: 'Juscelino Kubitschek asume con la promesa de 50 años en 5', en: 'Juscelino Kubitschek takes office promising 50 years in 5', pt: 'Juscelino Kubitschek assume prometendo 50 anos em 5' },
  { id: 'br-bossa-nova', year: 1958, emoji: '🎸', es: 'João Gilberto graba Chega de Saudade y nace la bossa nova', en: 'João Gilberto records Chega de Saudade and bossa nova is born', pt: 'João Gilberto grava Chega de Saudade e nasce a bossa nova' },
  { id: 'br-fusca', year: 1959, emoji: '🚗', es: 'Volkswagen empieza a fabricar el Fusca en Brasil', en: 'Volkswagen starts building the Beetle in Brazil', pt: 'A Volkswagen começa a fabricar o Fusca no Brasil' },
  { id: 'br-brasilia', year: 1960, emoji: '🏛️', es: 'Se inaugura Brasilia, la nueva capital', en: 'Brasília, the new capital, is inaugurated', pt: 'É inaugurada Brasília, a nova capital' },
  { id: 'br-ipanema', year: 1962, emoji: '🌊', es: 'Tom Jobim y Vinicius componen Garota de Ipanema', en: 'Tom Jobim and Vinicius write The Girl from Ipanema', pt: 'Tom Jobim e Vinicius compõem Garota de Ipanema' },
  { id: 'br-pagador', year: 1962, emoji: '🎬', es: 'O Pagador de Promessas gana la Palma de Oro en Cannes', en: 'The Given Word wins the Palme d’Or at Cannes', pt: 'O Pagador de Promessas ganha a Palma de Ouro em Cannes' },
  { id: 'br-havaianas', year: 1962, emoji: '🩴', es: 'Salen a la venta las primeras Havaianas', en: 'The first Havaianas go on sale', pt: 'As primeiras Havaianas chegam às lojas' },
  { id: 'br-monica', year: 1963, emoji: '🐰', es: 'Mauricio de Sousa dibuja a Mônica por primera vez', en: 'Mauricio de Sousa draws Mônica for the first time', pt: 'Mauricio de Sousa desenha a Mônica pela primeira vez' },
  { id: 'br-golpe', year: 1964, emoji: '🪖', es: 'Un golpe militar derroca a João Goulart', en: 'A military coup ousts João Goulart', pt: 'Um golpe militar derruba João Goulart' },
  { id: 'br-globo', year: 1965, emoji: '📺', es: 'Sale al aire TV Globo', en: 'TV Globo goes on air', pt: 'A TV Globo entra no ar' },
  { id: 'br-jovem-guarda', year: 1965, emoji: '🕶️', es: 'Roberto Carlos estrena el programa Jovem Guarda', en: 'Roberto Carlos launches the show Jovem Guarda', pt: 'Roberto Carlos estreia o programa Jovem Guarda' },
  { id: 'br-tropicalia', year: 1968, emoji: '🌴', es: 'Caetano y Gil lanzan el disco Tropicália', en: 'Caetano and Gil release the album Tropicália', pt: 'Caetano e Gil lançam o disco Tropicália' },
  { id: 'br-sanremo', year: 1968, emoji: '🏆', es: 'Roberto Carlos gana el festival de San Remo', en: 'Roberto Carlos wins the Sanremo festival', pt: 'Roberto Carlos vence o festival de San Remo' },
  { id: 'br-ai5', year: 1968, emoji: '🔒', es: 'La dictadura decreta el AI-5', en: 'The dictatorship issues the AI-5 decree', pt: 'A ditadura decreta o AI-5' },
  { id: 'br-jornal-nacional', year: 1969, emoji: '🗞️', es: 'Debuta el Jornal Nacional', en: 'The Jornal Nacional newscast debuts', pt: 'Estreia o Jornal Nacional' },
  { id: 'br-embraer', year: 1969, emoji: '🛩️', es: 'Se crea Embraer', en: 'Embraer is created', pt: 'É criada a Embraer' },
  { id: 'br-transamazonica', year: 1970, emoji: '🛣️', es: 'Empieza la construcción de la Transamazónica', en: 'Construction of the Trans-Amazonian Highway begins', pt: 'Começa a construção da Transamazônica' },
  { id: 'br-tv-color', year: 1972, emoji: '🌈', es: 'Llega la televisión a color a Brasil', en: 'Colour television arrives in Brazil', pt: 'Chega a televisão em cores ao Brasil' },
  { id: 'br-fittipaldi', year: 1972, emoji: '🏎️', es: 'Emerson Fittipaldi, primer brasileño campeón de Fórmula 1', en: 'Emerson Fittipaldi becomes Brazil’s first F1 champion', pt: 'Emerson Fittipaldi é o primeiro brasileiro campeão da Fórmula 1' },
  { id: 'br-fantastico', year: 1973, emoji: '🎪', es: 'Estrena Fantástico, el show de la vida', en: 'Fantástico, the show of life, premieres', pt: 'Estreia o Fantástico, o show da vida' },
  { id: 'br-rio-niteroi', year: 1974, emoji: '🌉', es: 'Se inaugura el puente Río-Niterói', en: 'The Rio–Niterói bridge opens', pt: 'É inaugurada a ponte Rio-Niterói' },
  { id: 'br-metro-sp', year: 1974, emoji: '🚇', es: 'Abre el metro de São Paulo', en: 'The São Paulo metro opens', pt: 'Abre o metrô de São Paulo' },
  { id: 'br-escrava-isaura', year: 1976, emoji: '🎭', es: 'Escrava Isaura, la telenovela que dio la vuelta al mundo', en: 'Escrava Isaura, the telenovela that went around the world', pt: 'Escrava Isaura, a novela que deu a volta ao mundo' },
  { id: 'br-divorcio', year: 1977, emoji: '💔', es: 'Brasil aprueba el divorcio', en: 'Brazil legalises divorce', pt: 'O Brasil aprova o divórcio' },
  { id: 'br-trapalhoes', year: 1977, emoji: '🤡', es: 'Os Trapalhões llegan a Globo', en: 'Os Trapalhões arrive at Globo', pt: 'Os Trapalhões chegam à Globo' },
  { id: 'br-dancin-days', year: 1978, emoji: '🪩', es: 'Dancin’ Days llena las discotecas', en: 'Dancin’ Days packs the discos', pt: 'Dancin’ Days lota as discotecas' },
  { id: 'br-amnistia', year: 1979, emoji: '🕊️', es: 'Se aprueba la Ley de Amnistía y vuelven los exiliados', en: 'The Amnesty Law passes and the exiles return', pt: 'É aprovada a Lei da Anistia e os exilados voltam' },
  { id: 'br-sbt', year: 1981, emoji: '📺', es: 'Silvio Santos funda el SBT', en: 'Silvio Santos founds SBT', pt: 'Silvio Santos funda o SBT' },
  { id: 'br-piquet', year: 1981, emoji: '🏎️', es: 'Nelson Piquet gana su primer título de Fórmula 1', en: 'Nelson Piquet wins his first F1 title', pt: 'Nelson Piquet ganha seu primeiro título na Fórmula 1' },
  { id: 'br-chaves', year: 1984, emoji: '🛢️', es: 'El Chavo del 8 llega a Brasil por el SBT', en: 'El Chavo del 8 arrives in Brazil on SBT', pt: 'Chaves chega ao Brasil pelo SBT' },
  { id: 'br-diretas', year: 1984, emoji: '✊', es: 'Las Diretas Já llenan las plazas', en: 'The Diretas Já rallies fill the squares', pt: 'As Diretas Já enchem as praças' },
  { id: 'br-sambodromo', year: 1984, emoji: '🥁', es: 'Se inaugura el Sambódromo de Río', en: 'The Rio Sambadrome opens', pt: 'É inaugurado o Sambódromo do Rio' },
  { id: 'br-itaipu', year: 1984, emoji: '⚡', es: 'Itaipú genera su primera electricidad', en: 'Itaipu generates its first electricity', pt: 'Itaipu gera sua primeira eletricidade' },
  { id: 'br-rock-in-rio', year: 1985, emoji: '🎸', es: 'Primer Rock in Rio, con Queen e Iron Maiden', en: 'The first Rock in Rio, with Queen and Iron Maiden', pt: 'Primeiro Rock in Rio, com Queen e Iron Maiden' },
  { id: 'br-fin-dictadura', year: 1985, emoji: '🕊️', es: 'Termina la dictadura: Sarney asume tras la muerte de Tancredo', en: 'The dictatorship ends: Sarney takes office after Tancredo’s death', pt: 'Acaba a ditadura: Sarney assume após a morte de Tancredo' },
  { id: 'br-roque-santeiro', year: 1985, emoji: '🎭', es: 'Se estrena Roque Santeiro, diez años después de la censura', en: 'Roque Santeiro finally airs, ten years after being censored', pt: 'Estreia Roque Santeiro, dez anos depois da censura' },
  { id: 'br-legiao', year: 1985, emoji: '🎤', es: 'Legião Urbana lanza su primer disco', en: 'Legião Urbana releases its first album', pt: 'A Legião Urbana lança seu primeiro disco' },
  { id: 'br-xuxa', year: 1986, emoji: '🚀', es: 'Estrena el Xou da Xuxa en Globo', en: 'Xou da Xuxa premieres on Globo', pt: 'Estreia o Xou da Xuxa na Globo' },
  { id: 'br-cruzado', year: 1986, emoji: '💸', es: 'El Plan Cruzado congela los precios', en: 'The Cruzado Plan freezes prices', pt: 'O Plano Cruzado congela os preços' },
  { id: 'br-constitucion', year: 1988, emoji: '📜', es: 'Se promulga la Constitución Ciudadana', en: 'The Citizen Constitution is enacted', pt: 'É promulgada a Constituição Cidadã' },
  { id: 'br-vale-tudo', year: 1988, emoji: '🔫', es: 'Vale Tudo: el país quiere saber quién mató a Odete Roitman', en: 'Vale Tudo: the country wants to know who killed Odete Roitman', pt: 'Vale Tudo: o país quer saber quem matou Odete Roitman' },
  { id: 'br-chico-mendes', year: 1988, emoji: '🌳', es: 'Asesinan al ambientalista Chico Mendes', en: 'Environmentalist Chico Mendes is murdered', pt: 'Assassinam o ambientalista Chico Mendes' },
  { id: 'br-senna-campeon', year: 1988, emoji: '🏎️', es: 'Ayrton Senna gana su primer título de Fórmula 1', en: 'Ayrton Senna wins his first F1 title', pt: 'Ayrton Senna ganha seu primeiro título na Fórmula 1' },
  { id: 'br-collor', year: 1989, emoji: '🗳️', es: 'Collor gana la primera elección directa en 29 años', en: 'Collor wins the first direct election in 29 years', pt: 'Collor vence a primeira eleição direta em 29 anos' },
  { id: 'br-faustao', year: 1989, emoji: '🎉', es: 'Estrena el Domingão do Faustão', en: 'Domingão do Faustão premieres', pt: 'Estreia o Domingão do Faustão' },
  { id: 'br-plano-collor', year: 1990, emoji: '🏦', es: 'El Plan Collor congela los ahorros de todo el país', en: 'The Collor Plan freezes the whole country’s savings', pt: 'O Plano Collor congela a poupança do país inteiro' },
  { id: 'br-pantanal', year: 1990, emoji: '🐆', es: 'Manchete estrena Pantanal', en: 'Manchete premieres Pantanal', pt: 'A Manchete estreia Pantanal' },
  { id: 'br-cazuza', year: 1990, emoji: '🌹', es: 'Muere Cazuza', en: 'Cazuza dies', pt: 'Morre Cazuza' },
  { id: 'br-evidencias', year: 1990, emoji: '🤠', es: 'Chitãozinho & Xororó lanzan Evidências', en: 'Chitãozinho & Xororó release Evidências', pt: 'Chitãozinho & Xororó lançam Evidências' },
  { id: 'br-eco-92', year: 1992, emoji: '🌍', es: 'Río recibe la cumbre de la Tierra, la Eco-92', en: 'Rio hosts the Earth Summit, Eco-92', pt: 'O Rio recebe a Cúpula da Terra, a Eco-92' },
  { id: 'br-impeachment-collor', year: 1992, emoji: '🎨', es: 'Los caras pintadas sacan a Collor del poder', en: 'The painted faces drive Collor from office', pt: 'Os caras-pintadas tiram Collor do poder' },
  { id: 'br-canto-cidade', year: 1992, emoji: '🥁', es: 'Daniela Mercury lleva el axé a todo Brasil con O Canto da Cidade', en: 'Daniela Mercury takes axé nationwide with O Canto da Cidade', pt: 'Daniela Mercury leva o axé ao Brasil inteiro com O Canto da Cidade' },
  { id: 'br-ratimbum', year: 1994, emoji: '🏰', es: 'Estrena Castelo Rá-Tim-Bum', en: 'Castelo Rá-Tim-Bum premieres', pt: 'Estreia o Castelo Rá-Tim-Bum' },
  { id: 'br-plano-real', year: 1994, emoji: '💵', es: 'Nace el real y termina la hiperinflación', en: 'The real is born and hyperinflation ends', pt: 'Nasce o real e acaba a hiperinflação' },
  { id: 'br-senna-muerte', year: 1994, emoji: '🏁', es: 'Ayrton Senna muere en Ímola', en: 'Ayrton Senna dies at Imola', pt: 'Ayrton Senna morre em Ímola' },
  { id: 'br-tom-jobim', year: 1994, emoji: '🎹', es: 'Muere Tom Jobim', en: 'Tom Jobim dies', pt: 'Morre Tom Jobim' },
  { id: 'br-malhacao', year: 1995, emoji: '🎒', es: 'Estrena Malhação', en: 'Malhação premieres', pt: 'Estreia Malhação' },
  { id: 'br-mamonas', year: 1995, emoji: '🤪', es: 'Mamonas Assassinas lanzan su único disco', en: 'Mamonas Assassinas release their only album', pt: 'Mamonas Assassinas lançam seu único disco' },
  { id: 'br-mamonas-accidente', year: 1996, emoji: '🕯️', es: 'Los Mamonas Assassinas mueren en un accidente aéreo', en: 'Mamonas Assassinas die in a plane crash', pt: 'Os Mamonas Assassinas morrem em um acidente de avião' },
  { id: 'br-sai-de-baixo', year: 1996, emoji: '🛋️', es: 'Estrena Sai de Baixo', en: 'Sai de Baixo premieres', pt: 'Estreia Sai de Baixo' },
  { id: 'br-tic-tic-tac', year: 1996, emoji: '🛶', es: 'Tic Tic Tac de Carrapicho suena en toda Europa', en: 'Carrapicho’s Tic Tic Tac plays all over Europe', pt: 'Tic Tic Tac, do Carrapicho, toca na Europa inteira' },
  { id: 'br-central', year: 1998, emoji: '🚂', es: 'Central do Brasil gana el Oso de Oro en Berlín', en: 'Central Station wins the Golden Bear in Berlin', pt: 'Central do Brasil ganha o Urso de Ouro em Berlim' },
  { id: 'br-sandy-junior', year: 1999, emoji: '👫', es: 'Sandy & Junior estrenan su serie en Globo', en: 'Sandy & Junior premiere their TV series on Globo', pt: 'Sandy & Junior estreiam sua série na Globo' },
  { id: 'br-o-clone', year: 2001, emoji: '🧬', es: 'O Clone pone a bailar danza árabe a todo el país', en: 'O Clone gets the whole country belly dancing', pt: 'O Clone põe o país inteiro para fazer dança do ventre' },
  { id: 'br-bbb', year: 2002, emoji: '👁️', es: 'Empieza el primer Big Brother Brasil', en: 'The first Big Brother Brasil begins', pt: 'Começa o primeiro Big Brother Brasil' },
  { id: 'br-cidade-de-deus', year: 2002, emoji: '🎬', es: 'Se estrena Cidade de Deus', en: 'City of God is released', pt: 'Estreia Cidade de Deus' },
  { id: 'br-lula', year: 2002, emoji: '🗳️', es: 'Lula es electo presidente', en: 'Lula is elected president', pt: 'Lula é eleito presidente' },
  { id: 'br-mensalao', year: 2005, emoji: '💼', es: 'Estalla el escándalo del Mensalão', en: 'The Mensalão scandal breaks', pt: 'Estoura o escândalo do Mensalão' },
  { id: 'br-tropa-elite', year: 2007, emoji: '🚔', es: 'Tropa de Elite se ve pirata antes de llegar al cine', en: 'Elite Squad is watched pirated before it hits cinemas', pt: 'Tropa de Elite é visto pirata antes de chegar ao cinema' },
  { id: 'br-pan-rio', year: 2007, emoji: '🏅', es: 'Río organiza los Juegos Panamericanos', en: 'Rio hosts the Pan American Games', pt: 'O Rio sedia os Jogos Pan-Americanos' },
  { id: 'br-caminho-indias', year: 2009, emoji: '🐘', es: 'Caminho das Índias gana el Emmy internacional', en: 'Caminho das Índias wins the International Emmy', pt: 'Caminho das Índias ganha o Emmy internacional' },
  { id: 'br-rio-2016-eleccion', year: 2009, emoji: '🎊', es: 'Río es elegida sede de los Juegos Olímpicos', en: 'Rio is chosen to host the Olympic Games', pt: 'O Rio é escolhido para sediar os Jogos Olímpicos' },
  { id: 'br-dilma', year: 2010, emoji: '🗳️', es: 'Dilma Rousseff, primera mujer presidenta', en: 'Dilma Rousseff becomes the first woman president', pt: 'Dilma Rousseff é a primeira mulher presidente' },
  { id: 'br-ai-se-eu-te-pego', year: 2011, emoji: '💃', es: 'Ai Se Eu Te Pego de Michel Teló conquista el mundo', en: 'Michel Teló’s Ai Se Eu Te Pego conquers the world', pt: 'Ai Se Eu Te Pego, de Michel Teló, conquista o mundo' },
  { id: 'br-avenida-brasil', year: 2012, emoji: '🍗', es: 'Avenida Brasil para el país con Carminha', en: 'Avenida Brasil stops the country with Carminha', pt: 'Avenida Brasil para o país com a Carminha' },
  { id: 'br-poderosas', year: 2013, emoji: '👑', es: 'Anitta se hace famosa con Show das Poderosas', en: 'Anitta hits it big with Show das Poderosas', pt: 'Anitta estoura com Show das Poderosas' },
  { id: 'br-junio-2013', year: 2013, emoji: '📣', es: 'Las protestas de junio sacan a millones a la calle', en: 'The June protests bring millions onto the streets', pt: 'As jornadas de junho levam milhões às ruas' },
  { id: 'br-papa', year: 2013, emoji: '⛪', es: 'El papa Francisco reúne a millones en Copacabana', en: 'Pope Francis gathers millions on Copacabana', pt: 'O papa Francisco reúne milhões em Copacabana' },
  { id: 'br-mundial-2014', year: 2014, emoji: '⚽', es: 'Brasil organiza el Mundial', en: 'Brazil hosts the World Cup', pt: 'O Brasil sedia a Copa do Mundo' },
  { id: 'br-mariana', year: 2015, emoji: '🟤', es: 'La represa de Mariana revienta y el barro llega al mar', en: 'The Mariana dam bursts and the mud reaches the sea', pt: 'A barragem de Mariana rompe e a lama chega ao mar' },
  { id: 'br-impeachment-dilma', year: 2016, emoji: '⚖️', es: 'El Senado destituye a Dilma', en: 'The Senate removes Dilma from office', pt: 'O Senado afasta Dilma do cargo' },
  { id: 'br-olimpiadas', year: 2016, emoji: '🏅', es: 'Río recibe los Juegos Olímpicos, y Gisele cruza el Maracaná', en: 'Rio hosts the Olympics, and Gisele struts across the Maracanã', pt: 'O Rio recebe as Olimpíadas, e Gisele desfila no Maracanã' },
  { id: 'br-marielle', year: 2018, emoji: '🕯️', es: 'Asesinan a la concejala Marielle Franco', en: 'Councillor Marielle Franco is assassinated', pt: 'Assassinam a vereadora Marielle Franco' },
  { id: 'br-museo', year: 2018, emoji: '🔥', es: 'Un incendio destruye el Museo Nacional de Río', en: 'A fire destroys the National Museum in Rio', pt: 'Um incêndio destrói o Museu Nacional no Rio' },
  { id: 'br-bolsonaro', year: 2018, emoji: '🗳️', es: 'Bolsonaro es electo presidente', en: 'Bolsonaro is elected president', pt: 'Bolsonaro é eleito presidente' },
  { id: 'br-brumadinho', year: 2019, emoji: '⛏️', es: 'La tragedia de Brumadinho', en: 'The Brumadinho dam disaster', pt: 'A tragédia de Brumadinho' },
  { id: 'br-paulo-gustavo', year: 2021, emoji: '🎭', es: 'Muere Paulo Gustavo por covid', en: 'Paulo Gustavo dies of covid', pt: 'Paulo Gustavo morre de covid' },
  { id: 'br-juliette', year: 2021, emoji: '🌵', es: 'Juliette gana el BBB con el país entero de cactus', en: 'Juliette wins BBB with the whole country as her cactus fans', pt: 'Juliette ganha o BBB com o país inteiro de cacto' },
  { id: 'br-envolver', year: 2022, emoji: '🌎', es: 'Anitta llega al número uno mundial de Spotify con Envolver', en: 'Anitta hits number one worldwide on Spotify with Envolver', pt: 'Anitta chega ao número um mundial do Spotify com Envolver' },
  { id: 'br-lula-3', year: 2022, emoji: '🗳️', es: 'Lula gana su tercera elección', en: 'Lula wins his third election', pt: 'Lula vence sua terceira eleição' },
  { id: 'br-8-enero', year: 2023, emoji: '🏛️', es: 'Una turba invade los Tres Poderes en Brasilia', en: 'A mob storms the Three Powers in Brasília', pt: 'Uma multidão invade os Três Poderes em Brasília' },
  { id: 'br-rita-lee', year: 2023, emoji: '🎤', es: 'Muere Rita Lee, la reina del rock brasileño', en: 'Rita Lee, queen of Brazilian rock, dies', pt: 'Morre Rita Lee, a rainha do rock brasileiro' },
  { id: 'br-madonna', year: 2024, emoji: '🎤', es: 'Madonna canta gratis para un millón y medio en Copacabana', en: 'Madonna plays for free to a million and a half on Copacabana', pt: 'Madonna canta de graça para um milhão e meio em Copacabana' },
  { id: 'br-rs-inundaciones', year: 2024, emoji: '🌧️', es: 'Las inundaciones tapan Porto Alegre', en: 'Floods swallow Porto Alegre', pt: 'As enchentes cobrem Porto Alegre' },
  { id: 'br-silvio-santos', year: 2024, emoji: '🎙️', es: 'Muere Silvio Santos', en: 'Silvio Santos dies', pt: 'Morre Silvio Santos' },
  { id: 'br-oscar', year: 2025, emoji: '🏆', es: 'Ainda Estou Aqui gana el primer Oscar para Brasil', en: 'I’m Still Here wins Brazil’s first Oscar', pt: 'Ainda Estou Aqui ganha o primeiro Oscar do Brasil' },
  { id: 'br-gaga', year: 2025, emoji: '🎤', es: 'Lady Gaga junta dos millones en Copacabana', en: 'Lady Gaga draws two million to Copacabana', pt: 'Lady Gaga junta dois milhões em Copacabana' },
  { id: 'br-cop30', year: 2025, emoji: '🌳', es: 'Belém recibe la COP30, la cumbre del clima', en: 'Belém hosts COP30, the climate summit', pt: 'Belém recebe a COP30, a cúpula do clima' },
];
