/**
 * Mazo Chile: hitos del país, de la conquista al estallido, mezclando historia,
 * deporte, tele, música y vida cotidiana. Formato: { id, year, emoji, es, en }.
 * Solo van años indiscutibles: si la fecha se discute, la carta no entra.
 */
export const CHILE = [
  { id: 'cl-magallanes', year: 1520, emoji: '⛵', es: 'Magallanes cruza el estrecho que hoy lleva su nombre', en: 'Magellan crosses the strait that now bears his name' },
  { id: 'cl-almagro', year: 1536, emoji: '🐎', es: 'Diego de Almagro llega a Chile', en: 'Diego de Almagro reaches Chile' },
  { id: 'cl-santiago', year: 1541, emoji: '🏙️', es: 'Pedro de Valdivia funda Santiago', en: 'Pedro de Valdivia founds Santiago' },
  { id: 'cl-lautaro', year: 1553, emoji: '🏹', es: 'Lautaro derrota a Valdivia en Tucapel', en: 'Lautaro defeats Valdivia at Tucapel' },
  { id: 'cl-araucana', year: 1569, emoji: '📖', es: 'Se publica La Araucana de Alonso de Ercilla', en: 'Ercilla publishes his epic poem La Araucana' },
  { id: 'cl-curalaba', year: 1598, emoji: '⚔️', es: 'El desastre de Curalaba frena la conquista', en: 'The disaster of Curalaba halts the conquest' },
  { id: 'cl-terremoto-1647', year: 1647, emoji: '🌋', es: 'Un terremoto destruye Santiago', en: 'An earthquake destroys Santiago' },
  { id: 'cl-san-felipe', year: 1738, emoji: '🎓', es: 'Se funda la Universidad de San Felipe', en: 'The University of San Felipe is founded' },
  { id: 'cl-jesuitas', year: 1767, emoji: '⛪', es: 'Expulsan a los jesuitas del reino de Chile', en: 'The Jesuits are expelled from Chile' },
  { id: 'cl-moneda', year: 1805, emoji: '🏛️', es: 'Se termina el Palacio de La Moneda', en: 'La Moneda Palace is completed' },
  { id: 'cl-junta', year: 1810, emoji: '🇨🇱', es: 'Se forma la Primera Junta Nacional de Gobierno', en: 'Chile forms its first national government junta' },
  { id: 'cl-aurora', year: 1812, emoji: '📰', es: 'Sale el primer número de la Aurora de Chile', en: 'The first Chilean newspaper, Aurora de Chile, is printed' },
  { id: 'cl-rancagua', year: 1814, emoji: '🔥', es: 'El desastre de Rancagua termina la Patria Vieja', en: 'The disaster of Rancagua ends the Patria Vieja' },
  { id: 'cl-chacabuco', year: 1817, emoji: '🐎', es: 'San Martín y O’Higgins vencen en Chacabuco', en: 'San Martín and O’Higgins win at Chacabuco' },
  { id: 'cl-independencia', year: 1818, emoji: '📜', es: 'Se firma la Declaración de Independencia', en: 'Chile signs its Declaration of Independence' },
  { id: 'cl-maipu', year: 1818, emoji: '⚔️', es: 'La batalla de Maipú asegura la independencia', en: 'The battle of Maipú secures independence' },
  { id: 'cl-esclavitud', year: 1823, emoji: '⛓️', es: 'Chile abole la esclavitud', en: 'Chile abolishes slavery' },
  { id: 'cl-chiloe', year: 1826, emoji: '🏝️', es: 'Chiloé se incorpora a Chile', en: 'Chiloé joins Chile' },
  { id: 'cl-constitucion-1833', year: 1833, emoji: '📜', es: 'Se promulga la Constitución de 1833', en: 'The 1833 Constitution is enacted' },
  { id: 'cl-portales', year: 1837, emoji: '🎩', es: 'Asesinan a Diego Portales', en: 'Diego Portales is assassinated' },
  { id: 'cl-u-de-chile', year: 1842, emoji: '🎓', es: 'Se funda la Universidad de Chile', en: 'The University of Chile is founded' },
  { id: 'cl-magallanes-toma', year: 1843, emoji: '⚓', es: 'Chile toma posesión del Estrecho de Magallanes', en: 'Chile takes possession of the Strait of Magellan' },
  { id: 'cl-ferrocarril', year: 1851, emoji: '🚂', es: 'Corre el primer ferrocarril, de Caldera a Copiapó', en: 'The first railway runs from Caldera to Copiapó' },
  { id: 'cl-compania', year: 1863, emoji: '🕯️', es: 'El incendio de la Iglesia de la Compañía enluta Santiago', en: 'The Compañía church fire devastates Santiago' },
  { id: 'cl-bombardeo', year: 1866, emoji: '💥', es: 'La escuadra española bombardea Valparaíso', en: 'The Spanish fleet bombards Valparaíso' },
  { id: 'cl-iquique', year: 1879, emoji: '⚓', es: 'El combate naval de Iquique abre la Guerra del Pacífico', en: 'The naval battle of Iquique opens the War of the Pacific' },
  { id: 'cl-araucania', year: 1883, emoji: '🌾', es: 'Termina la ocupación de la Araucanía', en: 'The occupation of Araucanía ends' },
  { id: 'cl-rapanui', year: 1888, emoji: '🗿', es: 'Rapa Nui se incorpora a Chile', en: 'Rapa Nui joins Chile' },
  { id: 'cl-guerra-civil', year: 1891, emoji: '⚔️', es: 'La guerra civil termina con la muerte de Balmaceda', en: 'The civil war ends with Balmaceda’s death' },
  { id: 'cl-mercurio', year: 1900, emoji: '📰', es: 'Nace El Mercurio de Santiago', en: 'El Mercurio de Santiago is founded' },
  { id: 'cl-terremoto-1906', year: 1906, emoji: '🏚️', es: 'Un terremoto arrasa Valparaíso', en: 'An earthquake flattens Valparaíso' },
  { id: 'cl-santa-maria', year: 1907, emoji: '🕯️', es: 'La matanza de la Escuela Santa María de Iquique', en: 'The Santa María school massacre in Iquique' },
  { id: 'cl-centenario', year: 1910, emoji: '🎉', es: 'Chile celebra el Centenario', en: 'Chile celebrates its centenary' },
  { id: 'cl-alessandri', year: 1920, emoji: '🎩', es: 'Arturo Alessandri llega a la presidencia', en: 'Arturo Alessandri becomes president' },
  { id: 'cl-colo-colo', year: 1925, emoji: '⚽', es: 'Se funda Colo-Colo', en: 'Colo-Colo football club is founded' },
  { id: 'cl-constitucion-1925', year: 1925, emoji: '📜', es: 'Se promulga la Constitución de 1925', en: 'The 1925 Constitution is enacted' },
  { id: 'cl-carabineros', year: 1927, emoji: '👮', es: 'Se crean Carabineros de Chile', en: 'The Carabineros police force is created' },
  { id: 'cl-la-u', year: 1927, emoji: '🔵', es: 'Se funda Universidad de Chile, el club', en: 'The Universidad de Chile football club is founded' },
  { id: 'cl-tratado-lima', year: 1929, emoji: '🤝', es: 'El Tratado de Lima deja Arica en Chile', en: 'The Treaty of Lima leaves Arica in Chile' },
  { id: 'cl-catolica', year: 1937, emoji: '⚪', es: 'Se funda Universidad Católica, el club', en: 'The Universidad Católica football club is founded' },
  { id: 'cl-aguirre-cerda', year: 1938, emoji: '📚', es: 'Pedro Aguirre Cerda llega a la presidencia', en: 'Pedro Aguirre Cerda becomes president' },
  { id: 'cl-corfo', year: 1939, emoji: '🏭', es: 'Se crea la CORFO para industrializar el país', en: 'CORFO is created to industrialise the country' },
  { id: 'cl-chillan', year: 1939, emoji: '🏚️', es: 'Un terremoto destruye Chillán', en: 'An earthquake destroys Chillán' },
  { id: 'cl-mistral', year: 1945, emoji: '🏅', es: 'Gabriela Mistral gana el Premio Nobel', en: 'Gabriela Mistral wins the Nobel Prize' },
  { id: 'cl-voto-femenino', year: 1949, emoji: '🗳️', es: 'Se aprueba el voto femenino en elecciones presidenciales', en: 'Women win the right to vote for president' },
  { id: 'cl-vina', year: 1960, emoji: '🎤', es: 'Se hace el primer Festival de Viña del Mar', en: 'The first Viña del Mar song festival is held' },
  { id: 'cl-valdivia', year: 1960, emoji: '🌊', es: 'El terremoto de Valdivia, el más grande jamás registrado', en: 'The Valdivia earthquake, the strongest ever recorded' },
  { id: 'cl-mundial-62', year: 1962, emoji: '⚽', es: 'Chile organiza el Mundial y sale tercero', en: 'Chile hosts the World Cup and finishes third' },
  { id: 'cl-sabado-gigante', year: 1962, emoji: '📺', es: 'Debuta Sábado Gigante', en: 'Sábado Gigante premieres on TV' },
  { id: 'cl-frei-montalva', year: 1964, emoji: '🎩', es: 'Eduardo Frei Montalva llega a la presidencia', en: 'Eduardo Frei Montalva becomes president' },
  { id: 'cl-chilenizacion', year: 1966, emoji: '⛏️', es: 'Empieza la chilenización del cobre', en: 'The “Chileanisation” of copper begins' },
  { id: 'cl-violeta', year: 1966, emoji: '🎶', es: 'Violeta Parra graba Gracias a la vida', en: 'Violeta Parra records Gracias a la vida' },
  { id: 'cl-victor-jara', year: 1969, emoji: '🎸', es: 'Víctor Jara gana el Festival de la Nueva Canción', en: 'Víctor Jara wins the New Chilean Song festival' },
  { id: 'cl-allende', year: 1970, emoji: '✊', es: 'Salvador Allende llega a la presidencia', en: 'Salvador Allende becomes president' },
  { id: 'cl-piedra-roja', year: 1970, emoji: '✌️', es: 'El festival de Piedra Roja, el Woodstock chileno', en: 'The Piedra Roja festival, the Chilean Woodstock' },
  { id: 'cl-cobre', year: 1971, emoji: '⛏️', es: 'Se nacionaliza el cobre por unanimidad', en: 'Copper is nationalised by a unanimous vote' },
  { id: 'cl-neruda', year: 1971, emoji: '🏅', es: 'Pablo Neruda gana el Premio Nobel', en: 'Pablo Neruda wins the Nobel Prize' },
  { id: 'cl-golpe', year: 1973, emoji: '🕯️', es: 'El golpe de Estado del 11 de septiembre', en: 'The coup d’état of 11 September' },
  { id: 'cl-metro', year: 1975, emoji: '🚇', es: 'Se inaugura el Metro de Santiago', en: 'The Santiago Metro opens' },
  { id: 'cl-letelier', year: 1976, emoji: '💣', es: 'Asesinan a Orlando Letelier en Washington', en: 'Orlando Letelier is assassinated in Washington' },
  { id: 'cl-teleton', year: 1978, emoji: '❤️', es: 'Se hace la primera Teletón', en: 'The first Teletón telethon is held' },
  { id: 'cl-tv-color', year: 1978, emoji: '📺', es: 'Llega la televisión a color', en: 'Colour television arrives' },
  { id: 'cl-beagle', year: 1978, emoji: '⛴️', es: 'El conflicto del Beagle casi lleva a la guerra', en: 'The Beagle conflict nearly starts a war' },
  { id: 'cl-constitucion-1980', year: 1980, emoji: '📜', es: 'Se aprueba la Constitución de 1980', en: 'The 1980 Constitution is approved' },
  { id: 'cl-jaivas', year: 1981, emoji: '🎹', es: 'Los Jaivas graban Alturas de Machu Picchu', en: 'Los Jaivas record Alturas de Machu Picchu' },
  { id: 'cl-parque-arauco', year: 1982, emoji: '🛍️', es: 'Abre Parque Arauco, el primer mall del país', en: 'Parque Arauco, the country’s first mall, opens' },
  { id: 'cl-protestas', year: 1983, emoji: '✊', es: 'Empiezan las Protestas Nacionales', en: 'The National Protests begin' },
  { id: 'cl-prisioneros', year: 1984, emoji: '🎸', es: 'Los Prisioneros publican La voz de los ’80', en: 'Los Prisioneros release La voz de los ’80' },
  { id: 'cl-atentado', year: 1986, emoji: '🚗', es: 'Atentado contra Pinochet en el Cajón del Maipo', en: 'Pinochet survives an ambush in Cajón del Maipo' },
  { id: 'cl-sabado-gigante-usa', year: 1986, emoji: '📡', es: 'Don Francisco lleva Sábado Gigante a Estados Unidos', en: 'Don Francisco takes Sábado Gigante to the United States' },
  { id: 'cl-papa', year: 1987, emoji: '⛪', es: 'Juan Pablo II visita Chile', en: 'Pope John Paul II visits Chile' },
  { id: 'cl-bolocco', year: 1987, emoji: '👑', es: 'Cecilia Bolocco es coronada Miss Universo', en: 'Cecilia Bolocco is crowned Miss Universe' },
  { id: 'cl-plebiscito-88', year: 1988, emoji: '🗳️', es: 'Gana el NO en el plebiscito', en: 'The NO wins the plebiscite' },
  { id: 'cl-aylwin', year: 1990, emoji: '🎩', es: 'Vuelve la democracia con Patricio Aylwin', en: 'Democracy returns with Patricio Aylwin' },
  { id: 'cl-libertadores', year: 1991, emoji: '🏆', es: 'Colo-Colo gana la Copa Libertadores', en: 'Colo-Colo wins the Copa Libertadores' },
  { id: 'cl-rettig', year: 1991, emoji: '📄', es: 'Se entrega el Informe Rettig', en: 'The Rettig Report is delivered' },
  { id: 'cl-frei-rt', year: 1994, emoji: '🎩', es: 'Eduardo Frei Ruiz-Tagle llega a la presidencia', en: 'Eduardo Frei Ruiz-Tagle becomes president' },
  { id: 'cl-los-tres', year: 1995, emoji: '🎸', es: 'Los Tres graban su MTV Unplugged', en: 'Los Tres record their MTV Unplugged' },
  { id: 'cl-viva-el-lunes', year: 1995, emoji: '📺', es: 'Debuta Viva el lunes, con Cecilia Bolocco y Kike Morandé', en: 'Viva el lunes premieres, hosted by Cecilia Bolocco and Kike Morandé' },
  { id: 'cl-zamorano', year: 1996, emoji: '⚽', es: 'Iván Zamorano ficha por el Inter de Milán', en: 'Iván Zamorano signs for Inter Milan' },
  { id: 'cl-rios', year: 1998, emoji: '🎾', es: 'Marcelo Ríos llega al número uno del mundo', en: 'Marcelo Ríos becomes world number one' },
  { id: 'cl-francia-98', year: 1998, emoji: '🇫🇷', es: 'Chile vuelve a un Mundial después de 16 años', en: 'Chile returns to a World Cup after 16 years' },
  { id: 'cl-pinochet-londres', year: 1998, emoji: '⚖️', es: 'Detienen a Pinochet en Londres', en: 'Pinochet is arrested in London' },
  { id: 'cl-chacotero', year: 1999, emoji: '🎬', es: 'Se estrena El Chacotero Sentimental', en: 'El Chacotero Sentimental hits cinemas' },
  { id: 'cl-lagos', year: 2000, emoji: '🎩', es: 'Ricardo Lagos llega a la presidencia', en: 'Ricardo Lagos becomes president' },
  { id: 'cl-morande', year: 2001, emoji: '🎭', es: 'Kike Morandé estrena Morandé con Compañía', en: 'Kike Morandé launches Morandé con Compañía' },
  { id: 'cl-rojo', year: 2002, emoji: '🎤', es: 'Debuta Rojo, fama contrafama', en: 'The talent show Rojo premieres' },
  { id: 'cl-starbucks', year: 2003, emoji: '☕', es: 'Abre el primer Starbucks del país', en: 'The country’s first Starbucks opens' },
  { id: 'cl-31-minutos', year: 2003, emoji: '🐤', es: 'Se estrena 31 minutos', en: '31 minutos premieres on TV' },
  { id: 'cl-machos', year: 2003, emoji: '🐴', es: 'La teleserie Machos se toma las noches', en: 'The soap opera Machos takes over prime time' },
  { id: 'cl-atenas', year: 2004, emoji: '🥇', es: 'Massú y González ganan el oro olímpico en Atenas', en: 'Massú and González win Olympic gold in Athens' },
  { id: 'cl-machuca', year: 2004, emoji: '🎬', es: 'Se estrena Machuca', en: 'The film Machuca premieres' },
  { id: 'cl-divorcio', year: 2004, emoji: '💔', es: 'Se aprueba la ley de divorcio', en: 'Divorce becomes legal in Chile' },
  { id: 'cl-vodanovic', year: 2005, emoji: '🎙️', es: 'Antonio Vodanovic anima su último Festival de Viña', en: 'Antonio Vodanovic hosts his last Viña festival' },
  { id: 'cl-bachelet', year: 2006, emoji: '👩', es: 'Michelle Bachelet es la primera presidenta del país', en: 'Michelle Bachelet becomes the first woman president' },
  { id: 'cl-pinguinos', year: 2006, emoji: '🎒', es: 'La revolución pingüina llena las calles de escolares', en: 'The “penguin revolution” fills the streets with students' },
  { id: 'cl-transantiago', year: 2007, emoji: '🚌', es: 'Parte el Transantiago', en: 'The Transantiago bus system starts' },
  { id: 'cl-sub20', year: 2007, emoji: '⚽', es: 'Chile sale tercero en el Mundial Sub-20', en: 'Chile finishes third in the U-20 World Cup' },
  { id: 'cl-los-80', year: 2008, emoji: '📼', es: 'Se estrena la teleserie Los 80', en: 'The series Los 80 premieres' },
  { id: 'cl-27f', year: 2010, emoji: '🌊', es: 'El terremoto y tsunami del 27F', en: 'The 27F earthquake and tsunami' },
  { id: 'cl-mineros', year: 2010, emoji: '⛑️', es: 'Rescatan a los 33 mineros de Atacama', en: 'The 33 miners are rescued in Atacama' },
  { id: 'cl-estudiantes-2011', year: 2011, emoji: '📢', es: 'Camila Vallejo encabeza las marchas por la educación gratuita', en: 'Camila Vallejo leads the marches for free education' },
  { id: 'cl-costanera', year: 2012, emoji: '🏢', es: 'Abre el mall del Costanera Center', en: 'The Costanera Center mall opens' },
  { id: 'cl-pelicula-no', year: 2012, emoji: '🎬', es: 'Se estrena la película No', en: 'The film No premieres' },
  { id: 'cl-alma', year: 2013, emoji: '🔭', es: 'Se inaugura el observatorio ALMA', en: 'The ALMA observatory is inaugurated' },
  { id: 'cl-incendio-valpo', year: 2014, emoji: '🔥', es: 'El mayor incendio de la historia de Valparaíso arrasa casi 3.000 casas', en: 'The largest fire in Valparaíso’s history destroys almost 3,000 homes' },
  { id: 'cl-copa-america', year: 2015, emoji: '🏆', es: 'Chile gana su primera Copa América', en: 'Chile wins its first Copa América' },
  { id: 'cl-union-civil', year: 2015, emoji: '💍', es: 'Entra en vigencia el Acuerdo de Unión Civil', en: 'Civil unions come into force' },
  { id: 'cl-bicampeon', year: 2016, emoji: '🏆', es: 'Chile gana la Copa América Centenario', en: 'Chile wins the Copa América Centenario' },
  { id: 'cl-oso', year: 2016, emoji: '🐻', es: 'Historia de un oso gana el Oscar', en: 'Bear Story wins the Oscar' },
  { id: 'cl-incendios-2017', year: 2017, emoji: '🔥', es: 'Los peores incendios forestales de la historia del país', en: 'The worst wildfires in the country’s history' },
  { id: 'cl-tres-causales', year: 2017, emoji: '⚖️', es: 'Se aprueba el aborto en tres causales', en: 'Abortion is legalised on three grounds' },
  { id: 'cl-mon-laferte', year: 2017, emoji: '🎤', es: 'Mon Laferte gana su primer Latin Grammy', en: 'Mon Laferte wins her first Latin Grammy' },
  { id: 'cl-mujer-fantastica', year: 2018, emoji: '🎬', es: 'Una mujer fantástica gana el Oscar', en: 'A Fantastic Woman wins the Oscar' },
  { id: 'cl-estallido', year: 2019, emoji: '🚨', es: 'Estalla el 18 de octubre', en: 'The social uprising of 18 October' },
  { id: 'cl-covid', year: 2020, emoji: '😷', es: 'Llega el primer caso de covid al país', en: 'The first covid case arrives in the country' },
  { id: 'cl-plebiscito-2020', year: 2020, emoji: '🗳️', es: 'Chile vota Apruebo para escribir una nueva Constitución', en: 'Chile votes to write a new Constitution' },
  { id: 'cl-vacunacion', year: 2021, emoji: '💉', es: 'Empieza la vacunación masiva', en: 'Mass vaccination begins' },
  { id: 'cl-matrimonio', year: 2021, emoji: '🏳️‍🌈', es: 'Se aprueba el matrimonio igualitario', en: 'Same-sex marriage is approved' },
  { id: 'cl-boric', year: 2021, emoji: '🎩', es: 'Gabriel Boric es electo presidente', en: 'Gabriel Boric is elected president' },
  { id: 'cl-rechazo', year: 2022, emoji: '🗳️', es: 'Se rechaza la propuesta de nueva Constitución', en: 'The proposed new Constitution is rejected' },
  { id: 'cl-panamericanos', year: 2023, emoji: '🏟️', es: 'Santiago organiza los Juegos Panamericanos', en: 'Santiago hosts the Pan American Games' },
];
