/**
 * Mazo Fútbol: historia del fútbol mundial, de las reglas de 1863 al Mundial de Clubes,
 * con clubes, mundiales, goles, fichajes y escándalos. Formato: { id, year, emoji, es, en, pt }.
 * Solo van años indiscutibles: el año en que pasó, no la temporada en que empezó.
 */
export const FUTBOL = [
  { id: 'fut-fa', year: 1863, emoji: '📜', es: 'Se funda la Football Association y se escriben las primeras reglas', en: 'The Football Association is founded and the first rules are written', pt: 'É fundada a Football Association e nascem as primeiras regras' },
  { id: 'fut-primer-internacional', year: 1872, emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', es: 'Escocia e Inglaterra juegan el primer partido entre selecciones', en: 'Scotland and England play the first international match', pt: 'Escócia e Inglaterra jogam a primeira partida entre seleções' },
  { id: 'fut-fa-cup', year: 1872, emoji: '🏆', es: 'Se juega la primera final de la FA Cup', en: 'The first FA Cup final is played', pt: 'É disputada a primeira final da FA Cup' },
  { id: 'fut-football-league', year: 1888, emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', es: 'Arranca la Football League, la primera liga del mundo', en: 'The Football League, the first league in the world, kicks off', pt: 'Começa a Football League, a primeira liga do mundo' },
  { id: 'fut-penal', year: 1891, emoji: '🥅', es: 'Se inventa el tiro penal', en: 'The penalty kick is invented', pt: 'É inventado o pênalti' },
  { id: 'fut-liverpool', year: 1892, emoji: '🔴', es: 'Se funda el Liverpool', en: 'Liverpool FC is founded', pt: 'É fundado o Liverpool' },
  { id: 'fut-juventus', year: 1897, emoji: '⚪', es: 'Se funda la Juventus', en: 'Juventus is founded', pt: 'É fundada a Juventus' },
  { id: 'fut-barcelona', year: 1899, emoji: '🔵', es: 'Se funda el FC Barcelona', en: 'FC Barcelona is founded', pt: 'É fundado o FC Barcelona' },
  { id: 'fut-milan', year: 1899, emoji: '🔴', es: 'Se funda el Milan', en: 'AC Milan is founded', pt: 'É fundado o Milan' },
  { id: 'fut-bayern', year: 1900, emoji: '🍺', es: 'Se funda el Bayern Múnich', en: 'Bayern Munich is founded', pt: 'É fundado o Bayern de Munique' },
  { id: 'fut-olimpico', year: 1900, emoji: '🥇', es: 'El fútbol entra en los Juegos Olímpicos de París', en: 'Football joins the Paris Olympic Games', pt: 'O futebol entra nos Jogos Olímpicos de Paris' },
  { id: 'fut-river', year: 1901, emoji: '🎗️', es: 'Se funda River Plate', en: 'River Plate is founded', pt: 'É fundado o River Plate' },
  { id: 'fut-real-madrid', year: 1902, emoji: '⚪', es: 'Se funda el Real Madrid', en: 'Real Madrid is founded', pt: 'É fundado o Real Madrid' },
  { id: 'fut-fifa', year: 1904, emoji: '🌍', es: 'Siete países fundan la FIFA en París', en: 'Seven countries found FIFA in Paris', pt: 'Sete países fundam a FIFA em Paris' },
  { id: 'fut-boca', year: 1905, emoji: '💙', es: 'Se funda Boca Juniors', en: 'Boca Juniors is founded', pt: 'É fundado o Boca Juniors' },
  { id: 'fut-inter', year: 1908, emoji: '⚫', es: 'Se funda el Inter de Milán', en: 'Inter Milan is founded', pt: 'É fundada a Internazionale de Milão' },
  { id: 'fut-corinthians', year: 1910, emoji: '🖤', es: 'Se funda el Corinthians', en: 'Corinthians is founded', pt: 'É fundado o Corinthians' },
  { id: 'fut-santos', year: 1912, emoji: '🐳', es: 'Se funda el Santos', en: 'Santos FC is founded', pt: 'É fundado o Santos' },
  { id: 'fut-copa-america', year: 1916, emoji: '🌎', es: 'Se juega la primera Copa América, en Argentina', en: 'The first Copa América is played, in Argentina', pt: 'É disputada a primeira Copa América, na Argentina' },
  { id: 'fut-femenino-prohibido', year: 1921, emoji: '🚫', es: 'La FA prohíbe el fútbol femenino en sus canchas', en: 'The FA bans women’s football from its grounds', pt: 'A FA proíbe o futebol feminino em seus campos' },
  { id: 'fut-wembley', year: 1923, emoji: '🐎', es: 'Abre Wembley con la final del caballo blanco', en: 'Wembley opens with the White Horse final', pt: 'Wembley abre com a final do cavalo branco' },
  { id: 'fut-uruguay-1924', year: 1924, emoji: '🇺🇾', es: 'Uruguay deslumbra a Europa y gana el oro olímpico', en: 'Uruguay dazzles Europe and wins Olympic gold', pt: 'O Uruguai encanta a Europa e leva o ouro olímpico' },
  { id: 'fut-colo-colo', year: 1925, emoji: '🇨🇱', es: 'Se funda Colo-Colo', en: 'Colo-Colo is founded', pt: 'É fundado o Colo-Colo' },
  { id: 'fut-offside', year: 1925, emoji: '🚩', es: 'Cambia la regla del fuera de juego: bastan dos defensores', en: 'The offside rule changes: two defenders are enough', pt: 'Muda a regra do impedimento: bastam dois defensores' },
  { id: 'fut-mundial-1930', year: 1930, emoji: '🏆', es: 'Uruguay gana el primer Mundial en su casa', en: 'Uruguay wins the first World Cup at home', pt: 'O Uruguai vence a primeira Copa do Mundo em casa' },
  { id: 'fut-mundial-1934', year: 1934, emoji: '🇮🇹', es: 'Italia gana el Mundial en la Italia de Mussolini', en: 'Italy wins the World Cup in Mussolini’s Italy', pt: 'A Itália vence a Copa na Itália de Mussolini' },
  { id: 'fut-mundial-1938', year: 1938, emoji: '🇮🇹', es: 'Italia repite el título en Francia', en: 'Italy retains the title in France', pt: 'A Itália repete o título na França' },
  { id: 'fut-numeros', year: 1939, emoji: '🔢', es: 'La liga inglesa obliga a numerar las camisetas', en: 'The English league makes shirt numbers compulsory', pt: 'A liga inglesa obriga a numerar as camisas' },
  { id: 'fut-bombonera', year: 1940, emoji: '🍬', es: 'Se inaugura La Bombonera', en: 'La Bombonera opens', pt: 'É inaugurada La Bombonera' },
  { id: 'fut-bernabeu', year: 1947, emoji: '🏟️', es: 'Se inaugura el estadio del Real Madrid, el futuro Bernabéu', en: 'Real Madrid’s stadium, the future Bernabéu, opens', pt: 'É inaugurado o estádio do Real Madrid, o futuro Bernabéu' },
  { id: 'fut-maracanazo', year: 1950, emoji: '😱', es: 'El Maracanazo: Uruguay le gana la final a Brasil', en: 'The Maracanazo: Uruguay beats Brazil in the final', pt: 'O Maracanaço: o Uruguai vence o Brasil na final' },
  { id: 'fut-hungria', year: 1953, emoji: '🇭🇺', es: 'Hungría humilla a Inglaterra 6-3 en Wembley', en: 'Hungary humiliates England 6–3 at Wembley', pt: 'A Hungria humilha a Inglaterra por 6 a 3 em Wembley' },
  { id: 'fut-berna', year: 1954, emoji: '🇩🇪', es: 'El milagro de Berna: Alemania vence a Hungría', en: 'The Miracle of Bern: West Germany beats Hungary', pt: 'O milagre de Berna: a Alemanha vence a Hungria' },
  { id: 'fut-copa-europa', year: 1956, emoji: '🏆', es: 'El Real Madrid gana la primera Copa de Europa', en: 'Real Madrid wins the first European Cup', pt: 'O Real Madrid vence a primeira Copa dos Campeões' },
  { id: 'fut-balon-oro', year: 1956, emoji: '🟡', es: 'Stanley Matthews recibe el primer Balón de Oro', en: 'Stanley Matthews receives the first Ballon d’Or', pt: 'Stanley Matthews recebe a primeira Bola de Ouro' },
  { id: 'fut-camp-nou', year: 1957, emoji: '🏟️', es: 'Se inaugura el Camp Nou', en: 'The Camp Nou opens', pt: 'É inaugurado o Camp Nou' },
  { id: 'fut-munich', year: 1958, emoji: '🕯️', es: 'La tragedia de Múnich diezma al Manchester United', en: 'The Munich air disaster decimates Manchester United', pt: 'A tragédia de Munique dizima o Manchester United' },
  { id: 'fut-pele-1958', year: 1958, emoji: '👑', es: 'Pelé, con 17 años, le da a Brasil su primer Mundial', en: 'Pelé, aged 17, gives Brazil its first World Cup', pt: 'Pelé, aos 17 anos, dá ao Brasil sua primeira Copa' },
  { id: 'fut-libertadores', year: 1960, emoji: '🌎', es: 'Peñarol gana la primera Copa Libertadores', en: 'Peñarol wins the first Copa Libertadores', pt: 'O Peñarol vence a primeira Copa Libertadores' },
  { id: 'fut-glasgow', year: 1960, emoji: '7️⃣', es: 'El Real Madrid golea 7-3 al Eintracht en la final de Glasgow', en: 'Real Madrid thrashes Eintracht 7–3 in the Glasgow final', pt: 'O Real Madrid goleia o Eintracht por 7 a 3 na final de Glasgow' },
  { id: 'fut-intercontinental', year: 1960, emoji: '🌐', es: 'Se juega la primera Copa Intercontinental', en: 'The first Intercontinental Cup is played', pt: 'É disputada a primeira Copa Intercontinental' },
  { id: 'fut-garrincha', year: 1962, emoji: '🦵', es: 'Garrincha lleva a Brasil al bicampeonato en Chile', en: 'Garrincha carries Brazil to a second title in Chile', pt: 'Garrincha leva o Brasil ao bicampeonato no Chile' },
  { id: 'fut-bundesliga', year: 1963, emoji: '🇩🇪', es: 'Nace la Bundesliga', en: 'The Bundesliga is born', pt: 'Nasce a Bundesliga' },
  { id: 'fut-inglaterra-1966', year: 1966, emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', es: 'Inglaterra gana su único Mundial con el gol fantasma de Wembley', en: 'England wins its only World Cup with the ghost goal of Wembley', pt: 'A Inglaterra vence sua única Copa com o gol fantasma de Wembley' },
  { id: 'fut-azteca', year: 1966, emoji: '🇲🇽', es: 'Se inaugura el Estadio Azteca', en: 'The Estadio Azteca opens', pt: 'É inaugurado o Estádio Azteca' },
  { id: 'fut-celtic', year: 1967, emoji: '☘️', es: 'Los Leones de Lisboa: el Celtic es el primer campeón británico de Europa', en: 'The Lisbon Lions: Celtic becomes Britain’s first European champion', pt: 'Os Leões de Lisboa: o Celtic é o primeiro campeão europeu britânico' },
  { id: 'fut-pele-1000', year: 1969, emoji: '💯', es: 'Pelé marca su gol número mil en el Maracaná', en: 'Pelé scores his thousandth goal at the Maracanã', pt: 'Pelé marca seu milésimo gol no Maracanã' },
  { id: 'fut-tarjetas', year: 1970, emoji: '🟨', es: 'Debutan las tarjetas amarilla y roja en el Mundial de México', en: 'Yellow and red cards debut at the Mexico World Cup', pt: 'Os cartões amarelo e vermelho estreiam na Copa do México' },
  { id: 'fut-brasil-1970', year: 1970, emoji: '🇧🇷', es: 'Brasil es tricampeón y se queda con la Jules Rimet', en: 'Brazil wins a third title and keeps the Jules Rimet trophy', pt: 'O Brasil é tricampeão e fica com a Jules Rimet' },
  { id: 'fut-femenino-vuelve', year: 1971, emoji: '♀️', es: 'La FA levanta la prohibición al fútbol femenino', en: 'The FA lifts its ban on women’s football', pt: 'A FA suspende a proibição ao futebol feminino' },
  { id: 'fut-ajax', year: 1973, emoji: '🔴', es: 'El Ajax de Cruyff gana su tercera Copa de Europa seguida', en: 'Cruyff’s Ajax wins a third straight European Cup', pt: 'O Ajax de Cruyff vence a terceira Copa dos Campeões seguida' },
  { id: 'fut-alemania-1974', year: 1974, emoji: '🍊', es: 'Alemania frena a la Naranja Mecánica en la final', en: 'West Germany stops the Clockwork Orange in the final', pt: 'A Alemanha para a Laranja Mecânica na final' },
  { id: 'fut-panenka', year: 1976, emoji: '🪶', es: 'Panenka pica el penal que decide la Eurocopa', en: 'Panenka chips the penalty that decides the Euro', pt: 'Panenka cava o pênalti que decide a Eurocopa' },
  { id: 'fut-pele-retiro', year: 1977, emoji: '👋', es: 'Pelé se despide del fútbol en el Cosmos de Nueva York', en: 'Pelé says goodbye to football with the New York Cosmos', pt: 'Pelé se despede do futebol no Cosmos de Nova York' },
  { id: 'fut-argentina-1978', year: 1978, emoji: '🇦🇷', es: 'Argentina gana su primer Mundial en casa', en: 'Argentina wins its first World Cup at home', pt: 'A Argentina vence sua primeira Copa em casa' },
  { id: 'fut-flamengo', year: 1981, emoji: '🔴', es: 'El Flamengo de Zico golea al Liverpool en Tokio', en: 'Zico’s Flamengo thrashes Liverpool in Tokyo', pt: 'O Flamengo de Zico goleia o Liverpool em Tóquio' },
  { id: 'fut-italia-1982', year: 1982, emoji: '🇮🇹', es: 'Paolo Rossi elimina al Brasil de Zico y Sócrates', en: 'Paolo Rossi knocks out the Brazil of Zico and Sócrates', pt: 'Paolo Rossi elimina o Brasil de Zico e Sócrates' },
  { id: 'fut-platini', year: 1984, emoji: '🇫🇷', es: 'Platini marca nueve goles y Francia gana la Eurocopa', en: 'Platini scores nine goals and France wins the Euro', pt: 'Platini marca nove gols e a França vence a Eurocopa' },
  { id: 'fut-heysel', year: 1985, emoji: '🕯️', es: 'La tragedia de Heysel deja a los clubes ingleses fuera de Europa', en: 'The Heysel disaster gets English clubs banned from Europe', pt: 'A tragédia de Heysel deixa os clubes ingleses fora da Europa' },
  { id: 'fut-mano-de-dios', year: 1986, emoji: '✋', es: 'La mano de Dios y el gol del siglo, en el mismo partido', en: 'The Hand of God and the Goal of the Century, in the same match', pt: 'A mão de Deus e o gol do século, no mesmo jogo' },
  { id: 'fut-van-basten', year: 1988, emoji: '🍊', es: 'La volea imposible de Van Basten corona a Holanda', en: 'Van Basten’s impossible volley crowns the Netherlands', pt: 'O voleio impossível de Van Basten coroa a Holanda' },
  { id: 'fut-milan-sacchi', year: 1989, emoji: '🔴', es: 'El Milan de Sacchi golea 4-0 al Steaua en la final', en: 'Sacchi’s Milan thrashes Steaua 4–0 in the final', pt: 'O Milan de Sacchi goleia o Steaua por 4 a 0 na final' },
  { id: 'fut-italia-90', year: 1990, emoji: '🇩🇪', es: 'Alemania vence a Argentina en la final de Italia 90', en: 'West Germany beats Argentina in the Italia 90 final', pt: 'A Alemanha vence a Argentina na final da Copa de 90' },
  { id: 'fut-milla', year: 1990, emoji: '🇨🇲', es: 'Roger Milla baila en el córner con 38 años', en: 'Roger Milla dances by the corner flag at 38', pt: 'Roger Milla dança no córner aos 38 anos' },
  { id: 'fut-mundial-femenino', year: 1991, emoji: '♀️', es: 'Se juega el primer Mundial femenino, en China', en: 'The first Women’s World Cup is played, in China', pt: 'É disputada a primeira Copa do Mundo feminina, na China' },
  { id: 'fut-premier', year: 1992, emoji: '🦁', es: 'Nace la Premier League', en: 'The Premier League is born', pt: 'Nasce a Premier League' },
  { id: 'fut-champions', year: 1992, emoji: '⭐', es: 'La Copa de Europa pasa a llamarse Champions League', en: 'The European Cup becomes the Champions League', pt: 'A Copa dos Campeões vira a Champions League' },
  { id: 'fut-dinamarca', year: 1992, emoji: '🇩🇰', es: 'Dinamarca gana la Eurocopa después de entrar de reemplazo', en: 'Denmark wins the Euro after coming in as a replacement', pt: 'A Dinamarca vence a Eurocopa depois de entrar como substituta' },
  { id: 'fut-colombia-5-0', year: 1993, emoji: '🇨🇴', es: 'Colombia golea 5-0 a Argentina en el Monumental', en: 'Colombia thrashes Argentina 5–0 at the Monumental', pt: 'A Colômbia goleia a Argentina por 5 a 0 no Monumental' },
  { id: 'fut-tetra', year: 1994, emoji: '🇧🇷', es: 'Brasil es tetracampeón por penales y Baggio tira el suyo a las nubes', en: 'Brazil wins a fourth title on penalties as Baggio skies his', pt: 'O Brasil é tetra nos pênaltis e Baggio manda o dele para as nuvens' },
  { id: 'fut-bosman', year: 1995, emoji: '⚖️', es: 'La ley Bosman libera a los jugadores al terminar su contrato', en: 'The Bosman ruling frees players at the end of their contracts', pt: 'A lei Bosman libera os jogadores ao fim do contrato' },
  { id: 'fut-mls', year: 1996, emoji: '🇺🇸', es: 'Arranca la MLS en Estados Unidos', en: 'The MLS kicks off in the United States', pt: 'Começa a MLS nos Estados Unidos' },
  { id: 'fut-roberto-carlos', year: 1997, emoji: '🌀', es: 'Roberto Carlos dobla la física con su tiro libre contra Francia', en: 'Roberto Carlos bends physics with his free kick against France', pt: 'Roberto Carlos dobra a física com a falta contra a França' },
  { id: 'fut-francia-98', year: 1998, emoji: '🇫🇷', es: 'Zidane le da a Francia su primer Mundial con dos cabezazos', en: 'Zidane gives France its first World Cup with two headers', pt: 'Zidane dá à França sua primeira Copa com dois gols de cabeça' },
  { id: 'fut-triplete-united', year: 1999, emoji: '🔴', es: 'El United remonta en dos minutos y logra el triplete', en: 'United come back in two minutes and complete the treble', pt: 'O United vira em dois minutos e conquista a tríplice coroa' },
  { id: 'fut-chastain', year: 1999, emoji: '🇺🇸', es: 'Estados Unidos gana el Mundial femenino y Brandi Chastain celebra sin camiseta', en: 'The USA wins the Women’s World Cup and Brandi Chastain celebrates shirtless', pt: 'Os Estados Unidos vencem a Copa feminina e Brandi Chastain comemora sem camisa' },
  { id: 'fut-mundial-clubes', year: 2000, emoji: '🌐', es: 'El Corinthians gana el primer Mundial de Clubes', en: 'Corinthians wins the first Club World Cup', pt: 'O Corinthians vence o primeiro Mundial de Clubes' },
  { id: 'fut-figo', year: 2000, emoji: '🐷', es: 'Figo se va del Barcelona al Real Madrid', en: 'Figo leaves Barcelona for Real Madrid', pt: 'Figo troca o Barcelona pelo Real Madrid' },
  { id: 'fut-zidane-madrid', year: 2001, emoji: '💶', es: 'El Real Madrid paga por Zidane el fichaje más caro de la historia', en: 'Real Madrid pays a world-record fee for Zidane', pt: 'O Real Madrid paga por Zidane a contratação mais cara da história' },
  { id: 'fut-penta', year: 2002, emoji: '🇧🇷', es: 'Ronaldo y Brasil ganan el penta en Japón', en: 'Ronaldo and Brazil win a fifth title in Japan', pt: 'Ronaldo e o Brasil conquistam o penta no Japão' },
  { id: 'fut-abramovich', year: 2003, emoji: '💷', es: 'Abramóvich compra el Chelsea', en: 'Abramovich buys Chelsea', pt: 'Abramovich compra o Chelsea' },
  { id: 'fut-invencibles', year: 2004, emoji: '🔫', es: 'El Arsenal de los Invencibles gana la Premier sin perder', en: 'Arsenal’s Invincibles win the Premier League unbeaten', pt: 'O Arsenal dos Invencíveis vence a Premier League sem perder' },
  { id: 'fut-grecia', year: 2004, emoji: '🇬🇷', es: 'Grecia gana la Eurocopa contra todo pronóstico', en: 'Greece wins the Euro against all odds', pt: 'A Grécia vence a Eurocopa contra todos os prognósticos' },
  { id: 'fut-messi-debut', year: 2004, emoji: '🐐', es: 'Messi debuta en el Barcelona con 17 años', en: 'Messi makes his Barcelona debut at 17', pt: 'Messi estreia no Barcelona aos 17 anos' },
  { id: 'fut-estambul', year: 2005, emoji: '🇹🇷', es: 'El milagro de Estambul: el Liverpool remonta un 3-0 al Milan', en: 'The Miracle of Istanbul: Liverpool come back from 3–0 down against Milan', pt: 'O milagre de Istambul: o Liverpool vira um 3 a 0 contra o Milan' },
  { id: 'fut-cabezazo', year: 2006, emoji: '🤕', es: 'Zidane se despide con un cabezazo a Materazzi', en: 'Zidane bows out with a headbutt on Materazzi', pt: 'Zidane se despede com uma cabeçada em Materazzi' },
  { id: 'fut-marta', year: 2006, emoji: '👑', es: 'Marta gana su primer premio a mejor jugadora del mundo', en: 'Marta wins her first world player of the year award', pt: 'Marta ganha seu primeiro prêmio de melhor jogadora do mundo' },
  { id: 'fut-messi-getafe', year: 2007, emoji: '🎩', es: 'Messi repite el gol de Maradona contra el Getafe', en: 'Messi recreates Maradona’s goal against Getafe', pt: 'Messi repete o gol de Maradona contra o Getafe' },
  { id: 'fut-city', year: 2008, emoji: '🩵', es: 'Abu Dabi compra el Manchester City', en: 'Abu Dhabi buys Manchester City', pt: 'Abu Dhabi compra o Manchester City' },
  { id: 'fut-espana-euro', year: 2008, emoji: '🇪🇸', es: 'España rompe 44 años de sequía y gana la Eurocopa', en: 'Spain ends a 44-year drought and wins the Euro', pt: 'A Espanha quebra 44 anos de jejum e vence a Eurocopa' },
  { id: 'fut-sextete', year: 2009, emoji: '6️⃣', es: 'El Barcelona de Guardiola gana los seis títulos del año', en: 'Guardiola’s Barcelona wins all six titles in a year', pt: 'O Barcelona de Guardiola vence os seis títulos do ano' },
  { id: 'fut-cr7-madrid', year: 2009, emoji: '💶', es: 'Cristiano Ronaldo llega al Real Madrid por 94 millones', en: 'Cristiano Ronaldo joins Real Madrid for 94 million', pt: 'Cristiano Ronaldo chega ao Real Madrid por 94 milhões' },
  { id: 'fut-iniesta', year: 2010, emoji: '🇪🇸', es: 'Iniesta le da a España su primer Mundial entre vuvuzelas', en: 'Iniesta gives Spain its first World Cup amid the vuvuzelas', pt: 'Iniesta dá à Espanha sua primeira Copa em meio às vuvuzelas' },
  { id: 'fut-japon-femenino', year: 2011, emoji: '🇯🇵', es: 'Japón gana el Mundial femenino meses después del tsunami', en: 'Japan wins the Women’s World Cup months after the tsunami', pt: 'O Japão vence a Copa feminina meses depois do tsunami' },
  { id: 'fut-messi-91', year: 2012, emoji: '9️⃣', es: 'Messi marca 91 goles en un solo año', en: 'Messi scores 91 goals in a single year', pt: 'Messi marca 91 gols em um único ano' },
  { id: 'fut-neymar-barca', year: 2013, emoji: '🇧🇷', es: 'Neymar deja el Santos por el Barcelona', en: 'Neymar leaves Santos for Barcelona', pt: 'Neymar deixa o Santos pelo Barcelona' },
  { id: 'fut-7-1', year: 2014, emoji: '7️⃣', es: 'El 7-1: Alemania humilla a Brasil en Belo Horizonte', en: 'The 7–1: Germany humiliates Brazil in Belo Horizonte', pt: 'O 7 a 1: a Alemanha humilha o Brasil em Belo Horizonte' },
  { id: 'fut-gotze', year: 2014, emoji: '🇩🇪', es: 'Götze le da a Alemania el Mundial en el Maracaná', en: 'Götze wins Germany the World Cup at the Maracanã', pt: 'Götze dá à Alemanha a Copa no Maracanã' },
  { id: 'fut-fifagate', year: 2015, emoji: '🚔', es: 'El FIFA Gate: arrestan a dirigentes en un hotel de Zúrich', en: 'FIFA Gate: officials are arrested in a Zurich hotel', pt: 'O FIFA Gate: dirigentes são presos em um hotel de Zurique' },
  { id: 'fut-chile-copa', year: 2015, emoji: '🇨🇱', es: 'Chile gana su primera Copa América', en: 'Chile wins its first Copa América', pt: 'O Chile vence sua primeira Copa América' },
  { id: 'fut-leicester', year: 2016, emoji: '🦊', es: 'El Leicester gana la Premier League a 5000 contra 1', en: 'Leicester win the Premier League at 5000 to 1', pt: 'O Leicester vence a Premier League a 5000 contra 1' },
  { id: 'fut-portugal-euro', year: 2016, emoji: '🇵🇹', es: 'Portugal gana la Eurocopa con Cristiano lesionado en el banco', en: 'Portugal wins the Euro with an injured Cristiano on the bench', pt: 'Portugal vence a Eurocopa com Cristiano lesionado no banco' },
  { id: 'fut-chapecoense', year: 2016, emoji: '🕯️', es: 'La tragedia aérea del Chapecoense', en: 'The Chapecoense plane crash', pt: 'A tragédia aérea da Chapecoense' },
  { id: 'fut-remontada', year: 2017, emoji: '🔥', es: 'La remontada: el Barcelona le da vuelta un 4-0 al PSG', en: 'The Remontada: Barcelona overturn a 4–0 against PSG', pt: 'A virada histórica: o Barcelona reverte um 4 a 0 contra o PSG' },
  { id: 'fut-neymar-psg', year: 2017, emoji: '💶', es: 'El PSG paga 222 millones por Neymar', en: 'PSG pays 222 million for Neymar', pt: 'O PSG paga 222 milhões por Neymar' },
  { id: 'fut-var', year: 2018, emoji: '📺', es: 'El VAR debuta en un Mundial', en: 'VAR makes its World Cup debut', pt: 'O VAR estreia em uma Copa do Mundo' },
  { id: 'fut-francia-2018', year: 2018, emoji: '🇫🇷', es: 'Francia gana su segundo Mundial, en Rusia', en: 'France wins its second World Cup, in Russia', pt: 'A França vence sua segunda Copa, na Rússia' },
  { id: 'fut-cr7-juve', year: 2018, emoji: '⚪', es: 'Cristiano Ronaldo se va a la Juventus', en: 'Cristiano Ronaldo moves to Juventus', pt: 'Cristiano Ronaldo vai para a Juventus' },
  { id: 'fut-rapinoe', year: 2019, emoji: '🇺🇸', es: 'Estados Unidos gana su cuarto Mundial femenino con Megan Rapinoe', en: 'The USA wins a fourth Women’s World Cup with Megan Rapinoe', pt: 'Os Estados Unidos vencem a quarta Copa feminina com Megan Rapinoe' },
  { id: 'fut-lisboa', year: 2020, emoji: '😷', es: 'El Bayern gana la Champions en un estadio vacío en Lisboa', en: 'Bayern wins the Champions League in an empty stadium in Lisbon', pt: 'O Bayern vence a Champions em um estádio vazio em Lisboa' },
  { id: 'fut-maradona-muerte', year: 2020, emoji: '🕯️', es: 'Muere Diego Maradona', en: 'Diego Maradona dies', pt: 'Morre Diego Maradona' },
  { id: 'fut-superliga', year: 2021, emoji: '💥', es: 'La Superliga europea nace y muere en 48 horas', en: 'The European Super League is born and dies in 48 hours', pt: 'A Superliga europeia nasce e morre em 48 horas' },
  { id: 'fut-messi-psg', year: 2021, emoji: '😢', es: 'Messi deja el Barcelona llorando y firma con el PSG', en: 'Messi leaves Barcelona in tears and signs for PSG', pt: 'Messi deixa o Barcelona chorando e assina com o PSG' },
  { id: 'fut-argentina-copa', year: 2021, emoji: '🇦🇷', es: 'Messi gana su primer título con Argentina en el Maracaná', en: 'Messi wins his first title with Argentina at the Maracanã', pt: 'Messi ganha seu primeiro título pela Argentina no Maracanã' },
  { id: 'fut-qatar', year: 2022, emoji: '🏆', es: 'Messi levanta la Copa del Mundo en Qatar', en: 'Messi lifts the World Cup in Qatar', pt: 'Messi levanta a Copa do Mundo no Catar' },
  { id: 'fut-pele-muerte', year: 2022, emoji: '🕯️', es: 'Muere Pelé', en: 'Pelé dies', pt: 'Morre Pelé' },
  { id: 'fut-messi-miami', year: 2023, emoji: '🌴', es: 'Messi se va al Inter Miami', en: 'Messi joins Inter Miami', pt: 'Messi vai para o Inter Miami' },
  { id: 'fut-espana-femenino', year: 2023, emoji: '🇪🇸', es: 'España gana el Mundial femenino', en: 'Spain wins the Women’s World Cup', pt: 'A Espanha vence a Copa do Mundo feminina' },
  { id: 'fut-city-triplete', year: 2023, emoji: '🩵', es: 'El Manchester City gana su primera Champions y el triplete', en: 'Manchester City wins its first Champions League and the treble', pt: 'O Manchester City vence sua primeira Champions e a tríplice coroa' },
  { id: 'fut-madrid-15', year: 2024, emoji: '👑', es: 'El Real Madrid gana su decimoquinta Champions', en: 'Real Madrid wins its fifteenth Champions League', pt: 'O Real Madrid vence sua décima quinta Champions' },
  { id: 'fut-espana-euro-2024', year: 2024, emoji: '🇪🇸', es: 'España gana su cuarta Eurocopa con Lamine Yamal de 17 años', en: 'Spain wins a fourth Euro with 17-year-old Lamine Yamal', pt: 'A Espanha vence sua quarta Eurocopa com Lamine Yamal, de 17 anos' },
  { id: 'fut-psg-champions', year: 2025, emoji: '🗼', es: 'El PSG gana su primera Champions goleando 5-0 al Inter', en: 'PSG wins its first Champions League, thrashing Inter 5–0', pt: 'O PSG vence sua primeira Champions goleando a Inter por 5 a 0' },
  { id: 'fut-mundial-clubes-2025', year: 2025, emoji: '🇺🇸', es: 'El Chelsea gana el primer Mundial de Clubes de 32 equipos', en: 'Chelsea wins the first 32-team Club World Cup', pt: 'O Chelsea vence o primeiro Mundial de Clubes com 32 times' },
];
