/**
 * Mazo Historia: hitos universales y reconocibles, con años indiscutibles.
 * Los años negativos son antes de Cristo. Formato: { id, year, emoji, es, en }.
 */
export const HISTORIA = [
  { id: 'piramide', year: -2560, emoji: '🔺', es: 'Se termina la Gran Pirámide de Guiza', en: 'The Great Pyramid of Giza is finished' },
  { id: 'hammurabi', year: -1754, emoji: '⚖️', es: 'Se graba el Código de Hammurabi', en: 'The Code of Hammurabi is carved' },
  { id: 'tutankamon', year: -1323, emoji: '👑', es: 'Muere Tutankamón', en: 'Tutankhamun dies' },
  { id: 'olimpiadas', year: -776, emoji: '🏅', es: 'Se celebran los primeros Juegos Olímpicos', en: 'The first Olympic Games are held' },
  { id: 'roma', year: -753, emoji: '🐺', es: 'Se funda Roma, según la leyenda', en: 'Rome is founded, according to legend' },
  { id: 'buda', year: -528, emoji: '🧘', es: 'Buda alcanza la iluminación, según la tradición', en: 'Buddha reaches enlightenment, by tradition' },
  { id: 'maraton', year: -490, emoji: '🏃', es: 'Los griegos vencen en la batalla de Maratón', en: 'The Greeks win the Battle of Marathon' },
  { id: 'partenon', year: -438, emoji: '🏛️', es: 'Se termina el Partenón de Atenas', en: 'The Parthenon in Athens is completed' },
  { id: 'alejandro', year: -336, emoji: '🗡️', es: 'Alejandro Magno llega al trono', en: 'Alexander the Great takes the throne' },
  { id: 'china', year: -221, emoji: '🏯', es: 'China se unifica bajo su primer emperador', en: 'China is unified under its first emperor' },
  { id: 'cesar', year: -44, emoji: '🗡️', es: 'Asesinan a Julio César', en: 'Julius Caesar is assassinated' },
  { id: 'vesubio', year: 79, emoji: '🌋', es: 'El Vesubio sepulta Pompeya', en: 'Mount Vesuvius buries Pompeii' },
  { id: 'papel', year: 105, emoji: '📄', es: 'Se inventa el papel en China', en: 'Paper is invented in China' },
  { id: 'roma-cae', year: 476, emoji: '🏚️', es: 'Cae el Imperio Romano de Occidente', en: 'The Western Roman Empire falls' },
  { id: 'hegira', year: 622, emoji: '🕌', es: 'La Hégira marca el inicio del calendario islámico', en: 'The Hijra starts the Islamic calendar' },
  { id: 'carlomagno', year: 800, emoji: '👑', es: 'Coronan emperador a Carlomagno', en: 'Charlemagne is crowned emperor' },
  { id: 'polvora', year: 850, emoji: '💥', es: 'Se descubre la pólvora en China', en: 'Gunpowder is discovered in China' },
  { id: 'vikingos', year: 1000, emoji: '⛵', es: 'Los vikingos llegan a América del Norte', en: 'The Vikings reach North America' },
  { id: 'hastings', year: 1066, emoji: '🏹', es: 'Los normandos ganan la batalla de Hastings', en: 'The Normans win the Battle of Hastings' },
  { id: 'universidad', year: 1088, emoji: '🎓', es: 'Nace la Universidad de Bolonia, la primera', en: 'The University of Bologna, the first, is founded' },
  { id: 'magna', year: 1215, emoji: '📜', es: 'Se firma la Carta Magna en Inglaterra', en: 'The Magna Carta is signed in England' },
  { id: 'marcopolo', year: 1271, emoji: '🐫', es: 'Marco Polo parte hacia Asia', en: 'Marco Polo sets off for Asia' },
  { id: 'peste', year: 1347, emoji: '🐀', es: 'La peste negra llega a Europa', en: 'The Black Death reaches Europe' },
  { id: 'machupicchu', year: 1450, emoji: '⛰️', es: 'Los incas construyen Machu Picchu', en: 'The Incas build Machu Picchu' },
  { id: 'constantinopla', year: 1453, emoji: '🕌', es: 'Cae Constantinopla', en: 'Constantinople falls' },
  { id: 'imprenta', year: 1455, emoji: '🖨️', es: 'Gutenberg imprime su Biblia con tipos móviles', en: 'Gutenberg prints his Bible with movable type' },
  { id: 'colon', year: 1492, emoji: '⛵', es: 'Colón llega a América', en: 'Columbus reaches the Americas' },
  { id: 'monalisa', year: 1503, emoji: '🖼️', es: 'Leonardo empieza a pintar la Mona Lisa', en: 'Leonardo starts painting the Mona Lisa' },
  { id: 'lutero', year: 1517, emoji: '✝️', es: 'Lutero publica sus 95 tesis', en: 'Luther publishes his 95 theses' },
  { id: 'vueltamundo', year: 1522, emoji: '🌍', es: 'La expedición de Magallanes y Elcano da la vuelta al mundo', en: 'The Magellan and Elcano expedition circles the globe' },
  { id: 'copernico', year: 1543, emoji: '☀️', es: 'Copérnico publica que la Tierra gira alrededor del Sol', en: 'Copernicus publishes that Earth orbits the Sun' },
  { id: 'shakespeare', year: 1600, emoji: '🎭', es: 'Shakespeare estrena Hamlet', en: 'Shakespeare premieres Hamlet' },
  { id: 'quijote', year: 1605, emoji: '📕', es: 'Se publica la primera parte del Quijote', en: 'The first part of Don Quixote is published' },
  { id: 'galileo', year: 1609, emoji: '🔭', es: 'Galileo apunta su telescopio al cielo', en: 'Galileo points his telescope at the sky' },
  { id: 'newton', year: 1687, emoji: '🍎', es: 'Newton publica la ley de gravitación universal', en: 'Newton publishes the law of universal gravitation' },
  { id: 'vacuna', year: 1796, emoji: '💉', es: 'Jenner crea la primera vacuna', en: 'Jenner creates the first vaccine' },
  { id: 'eeuu', year: 1776, emoji: '🇺🇸', es: 'Estados Unidos declara su independencia', en: 'The United States declares independence' },
  { id: 'revfrancesa', year: 1789, emoji: '🗼', es: 'Estalla la Revolución Francesa', en: 'The French Revolution breaks out' },
  { id: 'napoleon', year: 1804, emoji: '🎩', es: 'Napoleón se corona emperador', en: 'Napoleon crowns himself emperor' },
  { id: 'independencias', year: 1810, emoji: '🌎', es: 'Comienzan las independencias latinoamericanas', en: 'The Latin American independence wars begin' },
  { id: 'tren', year: 1825, emoji: '🚂', es: 'Se inaugura el primer ferrocarril de pasajeros', en: 'The first passenger railway opens' },
  { id: 'fotografia', year: 1826, emoji: '📷', es: 'Se toma la primera fotografía', en: 'The first photograph is taken' },
  { id: 'telegrafo', year: 1844, emoji: '📡', es: 'Se envía el primer telegrama de larga distancia', en: 'The first long-distance telegram is sent' },
  { id: 'darwin', year: 1859, emoji: '🐢', es: 'Darwin publica El origen de las especies', en: 'Darwin publishes On the Origin of Species' },
  { id: 'esclavitud', year: 1863, emoji: '⛓️', es: 'Estados Unidos proclama la emancipación de los esclavos', en: 'The United States proclaims the emancipation of slaves' },
  { id: 'suez', year: 1869, emoji: '🚢', es: 'Se abre el canal de Suez', en: 'The Suez Canal opens' },
  { id: 'telefono', year: 1876, emoji: '☎️', es: 'Bell patenta el teléfono', en: 'Bell patents the telephone' },
  { id: 'ampolleta', year: 1879, emoji: '💡', es: 'Edison presenta su lámpara incandescente', en: 'Edison unveils his light bulb' },
  { id: 'auto', year: 1886, emoji: '🚗', es: 'Benz patenta el primer automóvil', en: 'Benz patents the first automobile' },
  { id: 'eiffel', year: 1889, emoji: '🗼', es: 'Se inaugura la torre Eiffel', en: 'The Eiffel Tower opens' },
  { id: 'cine', year: 1895, emoji: '🎬', es: 'Los hermanos Lumière hacen la primera función de cine', en: 'The Lumière brothers hold the first film screening' },
  { id: 'rayosx', year: 1895, emoji: '🦴', es: 'Röntgen descubre los rayos X', en: 'Röntgen discovers X-rays' },
  { id: 'nobel', year: 1901, emoji: '🏆', es: 'Se entregan los primeros premios Nobel', en: 'The first Nobel Prizes are awarded' },
  { id: 'avion', year: 1903, emoji: '✈️', es: 'Los hermanos Wright logran el primer vuelo', en: 'The Wright brothers make the first flight' },
  { id: 'relatividad', year: 1905, emoji: '🧠', es: 'Einstein publica la teoría de la relatividad especial', en: 'Einstein publishes special relativity' },
  { id: 'titanic', year: 1912, emoji: '🧊', es: 'Se hunde el Titanic', en: 'The Titanic sinks' },
  { id: 'granguerra', year: 1914, emoji: '🎖️', es: 'Empieza la Primera Guerra Mundial', en: 'World War I begins' },
  { id: 'rusia', year: 1917, emoji: '🚩', es: 'Estalla la Revolución Rusa', en: 'The Russian Revolution breaks out' },
  { id: 'gripe', year: 1918, emoji: '😷', es: 'La gripe española recorre el mundo', en: 'The Spanish flu sweeps the world' },
  { id: 'penicilina', year: 1928, emoji: '🧫', es: 'Fleming descubre la penicilina', en: 'Fleming discovers penicillin' },
  { id: 'crac', year: 1929, emoji: '📉', es: 'El crac de Wall Street desata la Gran Depresión', en: 'The Wall Street crash triggers the Great Depression' },
  { id: 'segundaguerra', year: 1939, emoji: '🎖️', es: 'Empieza la Segunda Guerra Mundial', en: 'World War II begins' },
  { id: 'bomba', year: 1945, emoji: '☢️', es: 'Se lanza la primera bomba atómica', en: 'The first atomic bomb is dropped' },
  { id: 'india', year: 1947, emoji: '🇮🇳', es: 'India se independiza', en: 'India gains independence' },
  { id: 'ddhh', year: 1948, emoji: '🕊️', es: 'Se firma la Declaración Universal de Derechos Humanos', en: 'The Universal Declaration of Human Rights is signed' },
  { id: 'adn', year: 1953, emoji: '🧬', es: 'Se descubre la estructura del ADN', en: 'The structure of DNA is discovered' },
  { id: 'everest', year: 1953, emoji: '🏔️', es: 'Se corona el Everest por primera vez', en: 'Everest is summited for the first time' },
  { id: 'sputnik', year: 1957, emoji: '🛰️', es: 'El Sputnik es el primer satélite en órbita', en: 'Sputnik becomes the first satellite in orbit' },
  { id: 'gagarin', year: 1961, emoji: '👨‍🚀', es: 'Gagarin es el primer humano en el espacio', en: 'Gagarin becomes the first human in space' },
  { id: 'sueno', year: 1963, emoji: '✊', es: 'Martin Luther King da su discurso “Tengo un sueño”', en: 'Martin Luther King gives his “I have a dream” speech' },
  { id: 'luna', year: 1969, emoji: '🚀', es: 'El hombre llega a la Luna', en: 'Humans land on the Moon' },
  { id: 'email', year: 1971, emoji: '📧', es: 'Se envía el primer correo electrónico', en: 'The first email is sent' },
  { id: 'vietnam', year: 1975, emoji: '🕊️', es: 'Termina la guerra de Vietnam', en: 'The Vietnam War ends' },
  { id: 'voyager', year: 1977, emoji: '🛸', es: 'Despegan las sondas Voyager', en: 'The Voyager probes launch' },
  { id: 'pc', year: 1981, emoji: '🖥️', es: 'IBM lanza su computador personal', en: 'IBM launches its personal computer' },
  { id: 'chernobil', year: 1986, emoji: '☢️', es: 'Explota el reactor de Chernóbil', en: 'The Chernobyl reactor explodes' },
  { id: 'muro', year: 1989, emoji: '🧱', es: 'Cae el Muro de Berlín', en: 'The Berlin Wall falls' },
  { id: 'web', year: 1989, emoji: '🕸️', es: 'Se propone la World Wide Web', en: 'The World Wide Web is proposed' },
  { id: 'mandela', year: 1990, emoji: '✊🏿', es: 'Liberan a Nelson Mandela', en: 'Nelson Mandela is released' },
  { id: 'hubble', year: 1990, emoji: '🔭', es: 'Se pone en órbita el telescopio Hubble', en: 'The Hubble telescope reaches orbit' },
  { id: 'urss', year: 1991, emoji: '🇷🇺', es: 'Se disuelve la Unión Soviética', en: 'The Soviet Union dissolves' },
  { id: 'dolly', year: 1996, emoji: '🐑', es: 'Nace la oveja Dolly, el primer mamífero clonado', en: 'Dolly the sheep, the first cloned mammal, is born' },
  { id: 'google', year: 1998, emoji: '🔍', es: 'Se funda Google', en: 'Google is founded' },
  { id: 'euro', year: 2002, emoji: '💶', es: 'El euro empieza a circular', en: 'The euro enters circulation' },
  { id: 'torres', year: 2001, emoji: '🏙️', es: 'Los atentados del 11 de septiembre sacuden Nueva York', en: 'The September 11 attacks shake New York' },
  { id: 'wikipedia', year: 2001, emoji: '📚', es: 'Nace Wikipedia', en: 'Wikipedia is born' },
  { id: 'genoma', year: 2003, emoji: '🧬', es: 'Se completa el mapa del genoma humano', en: 'The human genome is fully mapped' },
  { id: 'facebook', year: 2004, emoji: '👥', es: 'Se lanza Facebook', en: 'Facebook launches' },
  { id: 'youtube', year: 2005, emoji: '📺', es: 'Se sube el primer video a YouTube', en: 'The first video is uploaded to YouTube' },
  { id: 'iphone', year: 2007, emoji: '📱', es: 'Apple presenta el primer iPhone', en: 'Apple unveils the first iPhone' },
  { id: 'crisis', year: 2008, emoji: '🏦', es: 'La crisis financiera golpea al mundo', en: 'The financial crisis hits the world' },
  { id: 'higgs', year: 2012, emoji: '⚛️', es: 'Se confirma el bosón de Higgs', en: 'The Higgs boson is confirmed' },
  { id: 'paris', year: 2015, emoji: '🌡️', es: 'Se firma el Acuerdo de París sobre el clima', en: 'The Paris climate agreement is signed' },
  { id: 'ondas', year: 2016, emoji: '🌌', es: 'Se detectan ondas gravitacionales', en: 'Gravitational waves are detected' },
  { id: 'agujero', year: 2019, emoji: '🕳️', es: 'Se publica la primera foto de un agujero negro', en: 'The first photo of a black hole is published' },
  { id: 'covid', year: 2020, emoji: '🦠', es: 'La pandemia de COVID-19 paraliza el planeta', en: 'The COVID-19 pandemic halts the planet' },
  { id: 'webb', year: 2022, emoji: '✨', es: 'El telescopio James Webb envía sus primeras imágenes', en: 'The James Webb telescope sends its first images' },
  { id: 'chatgpt', year: 2022, emoji: '🤖', es: 'ChatGPT llega al público', en: 'ChatGPT reaches the public' },
];
