/**
 * Mazo Música: hitos universales de la música y su tecnología, con años verificables.
 * Formato: { id, year, emoji, es, en, pt }.
 */
export const MUSICA = [
  { id: 'opera', year: 1600, emoji: '🎭', es: 'Se estrena la primera ópera que se conserva', en: 'The earliest surviving opera premieres', pt: 'Estreia a primeira ópera que se conserva' },
  { id: 'piano', year: 1700, emoji: '🎹', es: 'Cristofori inventa el piano', en: 'Cristofori invents the piano', pt: 'Cristofori inventa o piano' },
  { id: 'brandeburgo', year: 1721, emoji: '🎻', es: 'Bach termina los Conciertos de Brandeburgo', en: 'Bach completes the Brandenburg Concertos', pt: 'Bach conclui os Concertos de Brandemburgo' },
  { id: 'mesias', year: 1742, emoji: '👑', es: 'Se estrena El Mesías de Händel', en: 'Handel’s Messiah premieres', pt: 'Estreia O Messias de Händel' },
  { id: 'mozart', year: 1787, emoji: '🌙', es: 'Mozart compone Pequeña serenata nocturna', en: 'Mozart composes Eine kleine Nachtmusik', pt: 'Mozart compõe Pequena Serenata Noturna' },
  { id: 'quinta', year: 1808, emoji: '🎼', es: 'Se estrena la Quinta sinfonía de Beethoven', en: 'Beethoven’s Fifth Symphony premieres', pt: 'Estreia a Quinta Sinfonia de Beethoven' },
  { id: 'novena', year: 1824, emoji: '🎶', es: 'Se estrena la Novena sinfonía de Beethoven', en: 'Beethoven’s Ninth Symphony premieres', pt: 'Estreia a Nona Sinfonia de Beethoven' },
  { id: 'saxofon', year: 1846, emoji: '🎷', es: 'Adolphe Sax patenta el saxofón', en: 'Adolphe Sax patents the saxophone', pt: 'Adolphe Sax patenteia o saxofone' },
  { id: 'fonografo', year: 1877, emoji: '📯', es: 'Edison inventa el fonógrafo y graba la voz humana', en: 'Edison invents the phonograph and records the human voice', pt: 'Edison inventa o fonógrafo e grava a voz humana' },
  { id: 'gramofono', year: 1887, emoji: '💿', es: 'Berliner patenta el gramófono de discos', en: 'Berliner patents the disc gramophone', pt: 'Berliner patenteia o gramofone de discos' },
  { id: 'carmen', year: 1875, emoji: '💃', es: 'Se estrena la ópera Carmen', en: 'The opera Carmen premieres', pt: 'Estreia a ópera Carmen' },
  { id: 'caruso', year: 1902, emoji: '🎤', es: 'Caruso hace la primera grabación que vende un millón', en: 'Caruso makes the first million-selling record', pt: 'Caruso faz a primeira gravação a vender um milhão' },
  { id: 'consagracion', year: 1913, emoji: '🔥', es: 'La consagración de la primavera provoca un escándalo en París', en: 'The Rite of Spring causes a riot in Paris', pt: 'A Sagração da Primavera provoca um escândalo em Paris' },
  { id: 'jazz', year: 1917, emoji: '🎺', es: 'Se publica la primera grabación de jazz', en: 'The first jazz recording is released', pt: 'Sai a primeira gravação de jazz' },
  { id: 'radio', year: 1920, emoji: '📻', es: 'Empieza la radio comercial', en: 'Commercial radio begins', pt: 'Começa o rádio comercial' },
  { id: 'rhapsody', year: 1924, emoji: '🎹', es: 'Gershwin estrena Rhapsody in Blue', en: 'Gershwin premieres Rhapsody in Blue', pt: 'Gershwin estreia Rhapsody in Blue' },
  { id: 'bolero', year: 1928, emoji: '🥁', es: 'Ravel estrena el Bolero', en: 'Ravel premieres Boléro', pt: 'Ravel estreia o Bolero' },
  { id: 'guitarraelec', year: 1931, emoji: '🎸', es: 'Aparece la primera guitarra eléctrica', en: 'The first electric guitar appears', pt: 'Surge a primeira guitarra elétrica' },
  { id: 'swing', year: 1935, emoji: '🕺', es: 'Comienza la era del swing', en: 'The swing era begins', pt: 'Começa a era do swing' },
  { id: 'billieholiday', year: 1939, emoji: '🌹', es: 'Billie Holiday graba Strange Fruit', en: 'Billie Holiday records Strange Fruit', pt: 'Billie Holiday grava Strange Fruit' },
  { id: 'lp', year: 1948, emoji: '💽', es: 'Sale el disco de vinilo de larga duración', en: 'The long-playing vinyl record arrives', pt: 'Chega o disco de vinil de longa duração' },
  { id: 'fender', year: 1950, emoji: '🎸', es: 'Fender lanza la primera guitarra eléctrica de fábrica', en: 'Fender launches the first mass-produced electric guitar', pt: 'Fender lança a primeira guitarra elétrica produzida em série' },
  { id: 'rocknroll', year: 1954, emoji: '🎸', es: 'Rock Around the Clock enciende el rock and roll', en: 'Rock Around the Clock ignites rock and roll', pt: 'Rock Around the Clock acende o rock and roll' },
  { id: 'elvis', year: 1956, emoji: '🕴️', es: 'Elvis Presley se convierte en estrella mundial', en: 'Elvis Presley becomes a global star', pt: 'Elvis Presley vira estrela mundial' },
  { id: 'grammy', year: 1959, emoji: '🏆', es: 'Se entregan los primeros premios Grammy', en: 'The first Grammy Awards are handed out', pt: 'São entregues os primeiros prêmios Grammy' },
  { id: 'bossa', year: 1962, emoji: '🌴', es: 'La bossa nova conquista el mundo', en: 'Bossa nova conquers the world', pt: 'A bossa nova conquista o mundo' },
  { id: 'beatles', year: 1962, emoji: '🐞', es: 'Los Beatles publican su primer sencillo', en: 'The Beatles release their first single', pt: 'Os Beatles lançam seu primeiro single' },
  { id: 'moog', year: 1964, emoji: '🎛️', es: 'Aparece el sintetizador Moog', en: 'The Moog synthesizer appears', pt: 'Surge o sintetizador Moog' },
  { id: 'dylan', year: 1965, emoji: '🎤', es: 'Dylan publica Like a Rolling Stone', en: 'Dylan releases Like a Rolling Stone', pt: 'Dylan lança Like a Rolling Stone' },
  { id: 'sgtpepper', year: 1967, emoji: '🎺', es: 'Los Beatles publican Sgt. Pepper’s', en: 'The Beatles release Sgt. Pepper’s', pt: 'Os Beatles lançam Sgt. Pepper’s' },
  { id: 'woodstock', year: 1969, emoji: '☮️', es: 'Se celebra el festival de Woodstock', en: 'The Woodstock festival takes place', pt: 'Acontece o festival de Woodstock' },
  { id: 'beatlesfin', year: 1970, emoji: '💔', es: 'Se separan los Beatles', en: 'The Beatles break up', pt: 'Os Beatles se separam' },
  { id: 'imagine', year: 1971, emoji: '🕊️', es: 'John Lennon publica Imagine', en: 'John Lennon releases Imagine', pt: 'John Lennon lança Imagine' },
  { id: 'darkside', year: 1973, emoji: '🌈', es: 'Pink Floyd publica The Dark Side of the Moon', en: 'Pink Floyd release The Dark Side of the Moon', pt: 'Pink Floyd lança The Dark Side of the Moon' },
  { id: 'abba', year: 1974, emoji: '💃', es: 'ABBA gana Eurovisión con Waterloo', en: 'ABBA win Eurovision with Waterloo', pt: 'ABBA vence o Eurovision com Waterloo' },
  { id: 'bohemian', year: 1975, emoji: '👑', es: 'Queen publica Bohemian Rhapsody', en: 'Queen release Bohemian Rhapsody', pt: 'Queen lança Bohemian Rhapsody' },
  { id: 'punk', year: 1976, emoji: '🧷', es: 'Estalla el punk en Londres y Nueva York', en: 'Punk explodes in London and New York', pt: 'O punk explode em Londres e Nova York' },
  { id: 'fiebre', year: 1977, emoji: '🕺', es: 'Fiebre de sábado por la noche desata la disco', en: 'Saturday Night Fever sets off disco fever', pt: 'Os Embalos de Sábado à Noite deflagra a febre disco' },
  { id: 'elvismuere', year: 1977, emoji: '🌹', es: 'Muere Elvis Presley', en: 'Elvis Presley dies', pt: 'Morre Elvis Presley' },
  { id: 'walkman', year: 1979, emoji: '🎧', es: 'Sony lanza el Walkman', en: 'Sony launches the Walkman', pt: 'Sony lança o Walkman' },
  { id: 'hiphop', year: 1979, emoji: '🎙️', es: 'Rapper’s Delight lleva el hip hop a la radio', en: 'Rapper’s Delight takes hip hop to the radio', pt: 'Rapper’s Delight leva o hip hop ao rádio' },
  { id: 'mtv', year: 1981, emoji: '📺', es: 'MTV sale al aire', en: 'MTV goes on air', pt: 'A MTV entra no ar' },
  { id: 'cd', year: 1982, emoji: '💿', es: 'Llega el disco compacto', en: 'The compact disc arrives', pt: 'Chega o CD' },
  { id: 'thriller', year: 1982, emoji: '🧟', es: 'Michael Jackson publica Thriller', en: 'Michael Jackson releases Thriller', pt: 'Michael Jackson lança Thriller' },
  { id: 'midi', year: 1983, emoji: '🎹', es: 'Se adopta el estándar MIDI', en: 'The MIDI standard is adopted', pt: 'O padrão MIDI é adotado' },
  { id: 'madonna', year: 1984, emoji: '👗', es: 'Madonna publica Like a Virgin', en: 'Madonna releases Like a Virgin', pt: 'Madonna lança Like a Virgin' },
  { id: 'liveaid', year: 1985, emoji: '🌍', es: 'El concierto Live Aid se transmite al mundo', en: 'Live Aid is broadcast to the world', pt: 'O show Live Aid é transmitido para o mundo' },
  { id: 'joshua', year: 1987, emoji: '🌵', es: 'U2 publica The Joshua Tree', en: 'U2 release The Joshua Tree', pt: 'U2 lança The Joshua Tree' },
  { id: 'nevermind', year: 1991, emoji: '👶', es: 'Nirvana publica Nevermind y llega el grunge', en: 'Nirvana release Nevermind and grunge arrives', pt: 'Nirvana lança Nevermind e chega o grunge' },
  { id: 'mp3', year: 1995, emoji: '🗜️', es: 'Se bautiza el formato MP3', en: 'The MP3 format gets its name', pt: 'O formato MP3 ganha nome' },
  { id: 'tupac', year: 1996, emoji: '🎤', es: 'Muere Tupac Shakur', en: 'Tupac Shakur dies', pt: 'Morre Tupac Shakur' },
  { id: 'macarena', year: 1996, emoji: '💃', es: 'La Macarena se baila en todo el planeta', en: 'The Macarena is danced worldwide', pt: 'A Macarena é dançada no planeta inteiro' },
  { id: 'britney', year: 1998, emoji: '🎀', es: 'Britney Spears debuta con ...Baby One More Time', en: 'Britney Spears debuts with ...Baby One More Time', pt: 'Britney Spears estreia com ...Baby One More Time' },
  { id: 'napster', year: 1999, emoji: '🏴‍☠️', es: 'Napster cambia para siempre la industria musical', en: 'Napster changes the music industry forever', pt: 'Napster muda para sempre a indústria da música' },
  { id: 'ipod', year: 2001, emoji: '🎵', es: 'Apple lanza el iPod', en: 'Apple launches the iPod', pt: 'Apple lança o iPod' },
  { id: 'itunes', year: 2003, emoji: '🛒', es: 'Abre la tienda iTunes', en: 'The iTunes Store opens', pt: 'Abre a iTunes Store' },
  { id: 'coldplay', year: 2005, emoji: '🎹', es: 'Coldplay publica Fix You', en: 'Coldplay release Fix You', pt: 'Coldplay lança Fix You' },
  { id: 'spotify', year: 2008, emoji: '🟢', es: 'Spotify empieza a funcionar', en: 'Spotify goes live', pt: 'O Spotify entra no ar' },
  { id: 'gaga', year: 2009, emoji: '👠', es: 'Lady Gaga publica Bad Romance', en: 'Lady Gaga releases Bad Romance', pt: 'Lady Gaga lança Bad Romance' },
  { id: 'mjmuere', year: 2009, emoji: '🕯️', es: 'Muere Michael Jackson', en: 'Michael Jackson dies', pt: 'Morre Michael Jackson' },
  { id: 'gangnam', year: 2012, emoji: '🐎', es: 'Gangnam Style es el primer video con mil millones de vistas', en: 'Gangnam Style becomes the first video with a billion views', pt: 'Gangnam Style é o primeiro vídeo com um bilhão de visualizações' },
  { id: 'daftpunk', year: 2013, emoji: '🤖', es: 'Daft Punk publica Get Lucky', en: 'Daft Punk release Get Lucky', pt: 'Daft Punk lança Get Lucky' },
  { id: 'taylor', year: 2014, emoji: '✨', es: 'Taylor Swift publica 1989', en: 'Taylor Swift releases 1989', pt: 'Taylor Swift lança 1989' },
  { id: 'hamilton', year: 2015, emoji: '🎩', es: 'El musical Hamilton se estrena en Broadway', en: 'The musical Hamilton opens on Broadway', pt: 'O musical Hamilton estreia na Broadway' },
  { id: 'despacito', year: 2017, emoji: '🌊', es: 'Despacito rompe los récords mundiales', en: 'Despacito breaks global records', pt: 'Despacito quebra os recordes mundiais' },
  { id: 'bohemianfilm', year: 2018, emoji: '🎬', es: 'La película Bohemian Rhapsody revive a Queen', en: 'The film Bohemian Rhapsody revives Queen', pt: 'O filme Bohemian Rhapsody revive o Queen' },
  { id: 'billieeilish', year: 2019, emoji: '💚', es: 'Billie Eilish arrasa con su primer disco', en: 'Billie Eilish sweeps up with her first album', pt: 'Billie Eilish arrasa com seu primeiro álbum' },
  { id: 'bts', year: 2020, emoji: '💜', es: 'BTS llega al número uno mundial con Dynamite', en: 'BTS hit number one worldwide with Dynamite', pt: 'BTS chega ao número um mundial com Dynamite' },
  { id: 'badbunny', year: 2022, emoji: '🐰', es: 'Bad Bunny es el artista más escuchado del planeta', en: 'Bad Bunny becomes the most streamed artist on the planet', pt: 'Bad Bunny é o artista mais ouvido do planeta' },
  { id: 'vinilos', year: 2022, emoji: '📀', es: 'El vinilo vuelve a vender más que el CD', en: 'Vinyl outsells the CD again', pt: 'O vinil volta a vender mais que o CD' },
  { id: 'erastour', year: 2023, emoji: '🎪', es: 'La gira Eras Tour bate todos los récords', en: 'The Eras Tour breaks every record', pt: 'A turnê Eras Tour bate todos os recordes' },
  { id: 'estereo', year: 1958, emoji: '🔊', es: 'Llegan los primeros discos en estéreo', en: 'The first stereo records arrive', pt: 'Chegam os primeiros discos em estéreo' },
  { id: 'motown', year: 1959, emoji: '🎶', es: 'Nace el sello Motown', en: 'The Motown label is founded', pt: 'Nasce o selo Motown' },
  { id: 'aretha', year: 1967, emoji: '👑', es: 'Aretha Franklin publica Respect', en: 'Aretha Franklin releases Respect', pt: 'Aretha Franklin lança Respect' },
  { id: 'casete', year: 1963, emoji: '📼', es: 'Philips presenta el casete', en: 'Philips introduces the cassette tape', pt: 'Philips apresenta a fita cassete' },
  { id: 'hendrix', year: 1969, emoji: '🔥', es: 'Hendrix toca el himno de Estados Unidos en Woodstock', en: 'Hendrix plays the US anthem at Woodstock', pt: 'Hendrix toca o hino dos Estados Unidos em Woodstock' },
  { id: 'reggae', year: 1973, emoji: '🇯🇲', es: 'Bob Marley lleva el reggae al mundo', en: 'Bob Marley takes reggae to the world', pt: 'Bob Marley leva o reggae ao mundo' },
  { id: 'kraftwerk', year: 1974, emoji: '🤖', es: 'Kraftwerk publica Autobahn y funda la música electrónica', en: 'Kraftwerk release Autobahn and found electronic music', pt: 'Kraftwerk lança Autobahn e funda a música eletrônica' },
  { id: 'salsa', year: 1975, emoji: '🎺', es: 'La Fania All-Stars consagra la salsa', en: 'The Fania All-Stars cement salsa', pt: 'A Fania All-Stars consagra a salsa' },
  { id: 'sonora', year: 1966, emoji: '🎉', es: 'La cumbia se vuelve el ritmo de las fiestas latinoamericanas', en: 'Cumbia becomes the sound of Latin American parties', pt: 'A cumbia vira o ritmo das festas latino-americanas' },
  { id: 'metallica', year: 1991, emoji: '⚡', es: 'Metallica publica su Álbum Negro', en: 'Metallica release The Black Album', pt: 'Metallica lança o Black Album' },
  { id: 'radiohead', year: 1997, emoji: '💻', es: 'Radiohead publica OK Computer', en: 'Radiohead release OK Computer', pt: 'Radiohead lança OK Computer' },
  { id: 'eminem', year: 2000, emoji: '🎤', es: 'Eminem publica The Marshall Mathers LP', en: 'Eminem releases The Marshall Mathers LP', pt: 'Eminem lança The Marshall Mathers LP' },
  { id: 'shakira', year: 2001, emoji: '💃', es: 'Shakira cruza al mercado global con Whenever, Wherever', en: 'Shakira crosses over with Whenever, Wherever', pt: 'Shakira conquista o mercado global com Whenever, Wherever' },
  { id: 'amy', year: 2006, emoji: '🐝', es: 'Amy Winehouse publica Back to Black', en: 'Amy Winehouse releases Back to Black', pt: 'Amy Winehouse lança Back to Black' },
  { id: 'autotune', year: 1998, emoji: '🎚️', es: 'El Auto-Tune cambia el sonido de la voz pop', en: 'Auto-Tune changes the sound of pop vocals', pt: 'O Auto-Tune muda o som da voz pop' },
  { id: 'edm', year: 2011, emoji: '🎆', es: 'La música electrónica de baile domina los festivales', en: 'Electronic dance music takes over festivals', pt: 'A música eletrônica de dança domina os festivais' },
  { id: 'streaming', year: 2015, emoji: '📶', es: 'El streaming supera a las ventas físicas', en: 'Streaming overtakes physical sales', pt: 'O streaming supera as vendas físicas' },
  { id: 'tiktok', year: 2019, emoji: '🎵', es: 'TikTok se vuelve la fábrica de éxitos musicales', en: 'TikTok becomes the hit factory of music', pt: 'O TikTok vira a fábrica de hits da música' },
];
