/**
 * Mazo Música: hitos universales de la música y su tecnología, con años verificables.
 * Formato: { id, year, emoji, es, en }.
 */
export const MUSICA = [
  { id: 'opera', year: 1600, emoji: '🎭', es: 'Se estrena la primera ópera que se conserva', en: 'The earliest surviving opera premieres' },
  { id: 'piano', year: 1700, emoji: '🎹', es: 'Cristofori inventa el piano', en: 'Cristofori invents the piano' },
  { id: 'brandeburgo', year: 1721, emoji: '🎻', es: 'Bach termina los Conciertos de Brandeburgo', en: 'Bach completes the Brandenburg Concertos' },
  { id: 'mesias', year: 1742, emoji: '👑', es: 'Se estrena El Mesías de Händel', en: 'Handel’s Messiah premieres' },
  { id: 'mozart', year: 1787, emoji: '🌙', es: 'Mozart compone Pequeña serenata nocturna', en: 'Mozart composes Eine kleine Nachtmusik' },
  { id: 'quinta', year: 1808, emoji: '🎼', es: 'Se estrena la Quinta sinfonía de Beethoven', en: 'Beethoven’s Fifth Symphony premieres' },
  { id: 'novena', year: 1824, emoji: '🎶', es: 'Se estrena la Novena sinfonía de Beethoven', en: 'Beethoven’s Ninth Symphony premieres' },
  { id: 'saxofon', year: 1846, emoji: '🎷', es: 'Adolphe Sax patenta el saxofón', en: 'Adolphe Sax patents the saxophone' },
  { id: 'fonografo', year: 1877, emoji: '📯', es: 'Edison inventa el fonógrafo y graba la voz humana', en: 'Edison invents the phonograph and records the human voice' },
  { id: 'gramofono', year: 1887, emoji: '💿', es: 'Berliner patenta el gramófono de discos', en: 'Berliner patents the disc gramophone' },
  { id: 'carmen', year: 1875, emoji: '💃', es: 'Se estrena la ópera Carmen', en: 'The opera Carmen premieres' },
  { id: 'caruso', year: 1902, emoji: '🎤', es: 'Caruso hace la primera grabación que vende un millón', en: 'Caruso makes the first million-selling record' },
  { id: 'consagracion', year: 1913, emoji: '🔥', es: 'La consagración de la primavera provoca un escándalo en París', en: 'The Rite of Spring causes a riot in Paris' },
  { id: 'jazz', year: 1917, emoji: '🎺', es: 'Se publica la primera grabación de jazz', en: 'The first jazz recording is released' },
  { id: 'radio', year: 1920, emoji: '📻', es: 'Empieza la radio comercial', en: 'Commercial radio begins' },
  { id: 'rhapsody', year: 1924, emoji: '🎹', es: 'Gershwin estrena Rhapsody in Blue', en: 'Gershwin premieres Rhapsody in Blue' },
  { id: 'bolero', year: 1928, emoji: '🥁', es: 'Ravel estrena el Bolero', en: 'Ravel premieres Boléro' },
  { id: 'guitarraelec', year: 1931, emoji: '🎸', es: 'Aparece la primera guitarra eléctrica', en: 'The first electric guitar appears' },
  { id: 'swing', year: 1935, emoji: '🕺', es: 'Comienza la era del swing', en: 'The swing era begins' },
  { id: 'billieholiday', year: 1939, emoji: '🌹', es: 'Billie Holiday graba Strange Fruit', en: 'Billie Holiday records Strange Fruit' },
  { id: 'lp', year: 1948, emoji: '💽', es: 'Sale el disco de vinilo de larga duración', en: 'The long-playing vinyl record arrives' },
  { id: 'fender', year: 1950, emoji: '🎸', es: 'Fender lanza la primera guitarra eléctrica de fábrica', en: 'Fender launches the first mass-produced electric guitar' },
  { id: 'rocknroll', year: 1954, emoji: '🎸', es: 'Rock Around the Clock enciende el rock and roll', en: 'Rock Around the Clock ignites rock and roll' },
  { id: 'elvis', year: 1956, emoji: '🕴️', es: 'Elvis Presley se convierte en estrella mundial', en: 'Elvis Presley becomes a global star' },
  { id: 'grammy', year: 1959, emoji: '🏆', es: 'Se entregan los primeros premios Grammy', en: 'The first Grammy Awards are handed out' },
  { id: 'bossa', year: 1962, emoji: '🌴', es: 'La bossa nova conquista el mundo', en: 'Bossa nova conquers the world' },
  { id: 'beatles', year: 1962, emoji: '🐞', es: 'Los Beatles publican su primer sencillo', en: 'The Beatles release their first single' },
  { id: 'moog', year: 1964, emoji: '🎛️', es: 'Aparece el sintetizador Moog', en: 'The Moog synthesizer appears' },
  { id: 'dylan', year: 1965, emoji: '🎤', es: 'Dylan publica Like a Rolling Stone', en: 'Dylan releases Like a Rolling Stone' },
  { id: 'sgtpepper', year: 1967, emoji: '🎺', es: 'Los Beatles publican Sgt. Pepper’s', en: 'The Beatles release Sgt. Pepper’s' },
  { id: 'woodstock', year: 1969, emoji: '☮️', es: 'Se celebra el festival de Woodstock', en: 'The Woodstock festival takes place' },
  { id: 'beatlesfin', year: 1970, emoji: '💔', es: 'Se separan los Beatles', en: 'The Beatles break up' },
  { id: 'imagine', year: 1971, emoji: '🕊️', es: 'John Lennon publica Imagine', en: 'John Lennon releases Imagine' },
  { id: 'darkside', year: 1973, emoji: '🌈', es: 'Pink Floyd publica The Dark Side of the Moon', en: 'Pink Floyd release The Dark Side of the Moon' },
  { id: 'abba', year: 1974, emoji: '💃', es: 'ABBA gana Eurovisión con Waterloo', en: 'ABBA win Eurovision with Waterloo' },
  { id: 'bohemian', year: 1975, emoji: '👑', es: 'Queen publica Bohemian Rhapsody', en: 'Queen release Bohemian Rhapsody' },
  { id: 'punk', year: 1976, emoji: '🧷', es: 'Estalla el punk en Londres y Nueva York', en: 'Punk explodes in London and New York' },
  { id: 'fiebre', year: 1977, emoji: '🕺', es: 'Fiebre de sábado por la noche desata la disco', en: 'Saturday Night Fever sets off disco fever' },
  { id: 'elvismuere', year: 1977, emoji: '🌹', es: 'Muere Elvis Presley', en: 'Elvis Presley dies' },
  { id: 'walkman', year: 1979, emoji: '🎧', es: 'Sony lanza el Walkman', en: 'Sony launches the Walkman' },
  { id: 'hiphop', year: 1979, emoji: '🎙️', es: 'Rapper’s Delight lleva el hip hop a la radio', en: 'Rapper’s Delight takes hip hop to the radio' },
  { id: 'mtv', year: 1981, emoji: '📺', es: 'MTV sale al aire', en: 'MTV goes on air' },
  { id: 'cd', year: 1982, emoji: '💿', es: 'Llega el disco compacto', en: 'The compact disc arrives' },
  { id: 'thriller', year: 1982, emoji: '🧟', es: 'Michael Jackson publica Thriller', en: 'Michael Jackson releases Thriller' },
  { id: 'midi', year: 1983, emoji: '🎹', es: 'Se adopta el estándar MIDI', en: 'The MIDI standard is adopted' },
  { id: 'madonna', year: 1984, emoji: '👗', es: 'Madonna publica Like a Virgin', en: 'Madonna releases Like a Virgin' },
  { id: 'liveaid', year: 1985, emoji: '🌍', es: 'El concierto Live Aid se transmite al mundo', en: 'Live Aid is broadcast to the world' },
  { id: 'joshua', year: 1987, emoji: '🌵', es: 'U2 publica The Joshua Tree', en: 'U2 release The Joshua Tree' },
  { id: 'nevermind', year: 1991, emoji: '👶', es: 'Nirvana publica Nevermind y llega el grunge', en: 'Nirvana release Nevermind and grunge arrives' },
  { id: 'mp3', year: 1995, emoji: '🗜️', es: 'Se bautiza el formato MP3', en: 'The MP3 format gets its name' },
  { id: 'tupac', year: 1996, emoji: '🎤', es: 'Muere Tupac Shakur', en: 'Tupac Shakur dies' },
  { id: 'macarena', year: 1996, emoji: '💃', es: 'La Macarena se baila en todo el planeta', en: 'The Macarena is danced worldwide' },
  { id: 'britney', year: 1998, emoji: '🎀', es: 'Britney Spears debuta con ...Baby One More Time', en: 'Britney Spears debuts with ...Baby One More Time' },
  { id: 'napster', year: 1999, emoji: '🏴‍☠️', es: 'Napster cambia para siempre la industria musical', en: 'Napster changes the music industry forever' },
  { id: 'ipod', year: 2001, emoji: '🎵', es: 'Apple lanza el iPod', en: 'Apple launches the iPod' },
  { id: 'itunes', year: 2003, emoji: '🛒', es: 'Abre la tienda iTunes', en: 'The iTunes Store opens' },
  { id: 'coldplay', year: 2005, emoji: '🎹', es: 'Coldplay publica Fix You', en: 'Coldplay release Fix You' },
  { id: 'spotify', year: 2008, emoji: '🟢', es: 'Spotify empieza a funcionar', en: 'Spotify goes live' },
  { id: 'gaga', year: 2009, emoji: '👠', es: 'Lady Gaga publica Bad Romance', en: 'Lady Gaga releases Bad Romance' },
  { id: 'mjmuere', year: 2009, emoji: '🕯️', es: 'Muere Michael Jackson', en: 'Michael Jackson dies' },
  { id: 'gangnam', year: 2012, emoji: '🐎', es: 'Gangnam Style es el primer video con mil millones de vistas', en: 'Gangnam Style becomes the first video with a billion views' },
  { id: 'daftpunk', year: 2013, emoji: '🤖', es: 'Daft Punk publica Get Lucky', en: 'Daft Punk release Get Lucky' },
  { id: 'taylor', year: 2014, emoji: '✨', es: 'Taylor Swift publica 1989', en: 'Taylor Swift releases 1989' },
  { id: 'hamilton', year: 2015, emoji: '🎩', es: 'El musical Hamilton se estrena en Broadway', en: 'The musical Hamilton opens on Broadway' },
  { id: 'despacito', year: 2017, emoji: '🌊', es: 'Despacito rompe los récords mundiales', en: 'Despacito breaks global records' },
  { id: 'bohemianfilm', year: 2018, emoji: '🎬', es: 'La película Bohemian Rhapsody revive a Queen', en: 'The film Bohemian Rhapsody revives Queen' },
  { id: 'billieeilish', year: 2019, emoji: '💚', es: 'Billie Eilish arrasa con su primer disco', en: 'Billie Eilish sweeps up with her first album' },
  { id: 'bts', year: 2020, emoji: '💜', es: 'BTS llega al número uno mundial con Dynamite', en: 'BTS hit number one worldwide with Dynamite' },
  { id: 'badbunny', year: 2022, emoji: '🐰', es: 'Bad Bunny es el artista más escuchado del planeta', en: 'Bad Bunny becomes the most streamed artist on the planet' },
  { id: 'vinilos', year: 2022, emoji: '📀', es: 'El vinilo vuelve a vender más que el CD', en: 'Vinyl outsells the CD again' },
  { id: 'erastour', year: 2023, emoji: '🎪', es: 'La gira Eras Tour bate todos los récords', en: 'The Eras Tour breaks every record' },
  { id: 'estereo', year: 1958, emoji: '🔊', es: 'Llegan los primeros discos en estéreo', en: 'The first stereo records arrive' },
  { id: 'motown', year: 1959, emoji: '🎶', es: 'Nace el sello Motown', en: 'The Motown label is founded' },
  { id: 'aretha', year: 1967, emoji: '👑', es: 'Aretha Franklin publica Respect', en: 'Aretha Franklin releases Respect' },
  { id: 'casete', year: 1963, emoji: '📼', es: 'Philips presenta el casete', en: 'Philips introduces the cassette tape' },
  { id: 'hendrix', year: 1969, emoji: '🔥', es: 'Hendrix toca el himno de Estados Unidos en Woodstock', en: 'Hendrix plays the US anthem at Woodstock' },
  { id: 'reggae', year: 1973, emoji: '🇯🇲', es: 'Bob Marley lleva el reggae al mundo', en: 'Bob Marley takes reggae to the world' },
  { id: 'kraftwerk', year: 1974, emoji: '🤖', es: 'Kraftwerk publica Autobahn y funda la música electrónica', en: 'Kraftwerk release Autobahn and found electronic music' },
  { id: 'salsa', year: 1975, emoji: '🎺', es: 'La Fania All-Stars consagra la salsa', en: 'The Fania All-Stars cement salsa' },
  { id: 'sonora', year: 1966, emoji: '🎉', es: 'La cumbia se vuelve el ritmo de las fiestas latinoamericanas', en: 'Cumbia becomes the sound of Latin American parties' },
  { id: 'metallica', year: 1991, emoji: '⚡', es: 'Metallica publica su Álbum Negro', en: 'Metallica release The Black Album' },
  { id: 'radiohead', year: 1997, emoji: '💻', es: 'Radiohead publica OK Computer', en: 'Radiohead release OK Computer' },
  { id: 'eminem', year: 2000, emoji: '🎤', es: 'Eminem publica The Marshall Mathers LP', en: 'Eminem releases The Marshall Mathers LP' },
  { id: 'shakira', year: 2001, emoji: '💃', es: 'Shakira cruza al mercado global con Whenever, Wherever', en: 'Shakira crosses over with Whenever, Wherever' },
  { id: 'amy', year: 2006, emoji: '🐝', es: 'Amy Winehouse publica Back to Black', en: 'Amy Winehouse releases Back to Black' },
  { id: 'autotune', year: 1998, emoji: '🎚️', es: 'El Auto-Tune cambia el sonido de la voz pop', en: 'Auto-Tune changes the sound of pop vocals' },
  { id: 'edm', year: 2011, emoji: '🎆', es: 'La música electrónica de baile domina los festivales', en: 'Electronic dance music takes over festivals' },
  { id: 'streaming', year: 2015, emoji: '📶', es: 'El streaming supera a las ventas físicas', en: 'Streaming overtakes physical sales' },
  { id: 'tiktok', year: 2019, emoji: '🎵', es: 'TikTok se vuelve la fábrica de éxitos musicales', en: 'TikTok becomes the hit factory of music' },
];
