/**
 * Mazo Cultura Pop: cine, tele, videojuegos, internet y memes.
 * Formato: { id, year, emoji, es, en, pt }. Solo años indiscutibles: el año en que
 * la cosa salió al mundo, no cuando se hizo famosa (salvo que se diga en la carta).
 */
export const POP = [
  { id: 'pop-mickey', year: 1928, emoji: '🐭', es: 'Mickey Mouse debuta en Steamboat Willie', en: 'Mickey Mouse debuts in Steamboat Willie', pt: 'Mickey Mouse estreia em Steamboat Willie' },
  { id: 'pop-blancanieves', year: 1937, emoji: '🍎', es: 'Disney estrena Blancanieves, su primer largometraje', en: 'Disney releases Snow White, its first feature film', pt: 'A Disney lança Branca de Neve, seu primeiro longa' },
  { id: 'pop-mago-oz', year: 1939, emoji: '🌪️', es: 'Se estrena El Mago de Oz', en: 'The Wizard of Oz premieres', pt: 'Estreia O Mágico de Oz' },
  { id: 'pop-godzilla', year: 1954, emoji: '🦖', es: 'Godzilla pisa Tokio por primera vez', en: 'Godzilla stomps through Tokyo for the first time', pt: 'Godzilla pisa em Tóquio pela primeira vez' },
  { id: 'pop-disneylandia', year: 1955, emoji: '🏰', es: 'Abre Disneylandia en California', en: 'Disneyland opens in California', pt: 'A Disneylândia abre na Califórnia' },
  { id: 'pop-lego', year: 1958, emoji: '🧱', es: 'Lego patenta el ladrillo que todos pisamos', en: 'Lego patents the brick we all step on', pt: 'A Lego patenteia a peça que todo mundo pisa' },
  { id: 'pop-barbie', year: 1959, emoji: '👱‍♀️', es: 'Sale la primera Barbie', en: 'The first Barbie doll goes on sale', pt: 'A primeira Barbie chega às lojas' },
  { id: 'pop-psicosis', year: 1960, emoji: '🚿', es: 'Hitchcock estrena Psicosis', en: 'Hitchcock releases Psycho', pt: 'Hitchcock lança Psicose' },
  { id: 'pop-2001', year: 1968, emoji: '🛰️', es: 'Se estrena 2001: Odisea del espacio', en: '2001: A Space Odyssey premieres', pt: 'Estreia 2001: Uma Odisseia no Espaço' },
  { id: 'pop-sesamo', year: 1969, emoji: '🧸', es: 'Debuta Plaza Sésamo', en: 'Sesame Street premieres', pt: 'Estreia Vila Sésamo nos Estados Unidos' },
  { id: 'pop-pong', year: 1972, emoji: '🏓', es: 'Pong inaugura los videojuegos en los bares', en: 'Pong brings video games to the bar', pt: 'Pong leva os videogames para os bares' },
  { id: 'pop-rubik', year: 1974, emoji: '🧩', es: 'Se inventa el cubo Rubik', en: 'The Rubik’s Cube is invented', pt: 'É inventado o cubo mágico' },
  { id: 'pop-tiburon', year: 1975, emoji: '🦈', es: 'Tiburón inventa el éxito de verano', en: 'Jaws invents the summer blockbuster', pt: 'Tubarão inventa o blockbuster de verão' },
  { id: 'pop-star-wars', year: 1977, emoji: '🌌', es: 'Se estrena La Guerra de las Galaxias', en: 'Star Wars hits cinemas', pt: 'Star Wars chega aos cinemas' },
  { id: 'pop-atari', year: 1977, emoji: '🕹️', es: 'Sale el Atari 2600', en: 'The Atari 2600 goes on sale', pt: 'O Atari 2600 chega às lojas' },
  { id: 'pop-space-invaders', year: 1978, emoji: '👾', es: 'Space Invaders se toma los arcades', en: 'Space Invaders takes over the arcades', pt: 'Space Invaders toma conta dos fliperamas' },
  { id: 'pop-walkman', year: 1979, emoji: '🎧', es: 'Sony lanza el Walkman', en: 'Sony launches the Walkman', pt: 'A Sony lança o Walkman' },
  { id: 'pop-alien', year: 1979, emoji: '👽', es: 'Alien llega a los cines', en: 'Alien reaches cinemas', pt: 'Alien, o Oitavo Passageiro, chega aos cinemas' },
  { id: 'pop-pac-man', year: 1980, emoji: '🟡', es: 'Aparece Pac-Man', en: 'Pac-Man appears', pt: 'Surge o Pac-Man' },
  { id: 'pop-donkey-kong', year: 1981, emoji: '🦍', es: 'Donkey Kong presenta a Mario al mundo', en: 'Donkey Kong introduces Mario to the world', pt: 'Donkey Kong apresenta o Mario ao mundo' },
  { id: 'pop-et', year: 1982, emoji: '🚲', es: 'E.T. quiere llamar a su casa', en: 'E.T. wants to phone home', pt: 'E.T. quer telefonar para casa' },
  { id: 'pop-celular', year: 1983, emoji: '📞', es: 'Sale el primer celular comercial', en: 'The first commercial mobile phone goes on sale', pt: 'Chega o primeiro celular comercial' },
  { id: 'pop-famicom', year: 1983, emoji: '🎮', es: 'Nintendo lanza la Famicom', en: 'Nintendo launches the Famicom', pt: 'A Nintendo lança o Famicom' },
  { id: 'pop-tetris', year: 1984, emoji: '🟦', es: 'Se crea Tetris en la Unión Soviética', en: 'Tetris is created in the Soviet Union', pt: 'Tetris é criado na União Soviética' },
  { id: 'pop-cazafantasmas', year: 1984, emoji: '👻', es: 'Se estrena Los Cazafantasmas', en: 'Ghostbusters premieres', pt: 'Estreia Os Caça-Fantasmas' },
  { id: 'pop-mario', year: 1985, emoji: '🍄', es: 'Sale Super Mario Bros', en: 'Super Mario Bros is released', pt: 'É lançado Super Mario Bros' },
  { id: 'pop-volver-al-futuro', year: 1985, emoji: '🚗', es: 'Marty McFly viaja a 1955 en Volver al Futuro', en: 'Marty McFly travels to 1955 in Back to the Future', pt: 'Marty McFly viaja a 1955 em De Volta para o Futuro' },
  { id: 'pop-simpsons', year: 1989, emoji: '🍩', es: 'Los Simpson estrenan su primera temporada', en: 'The Simpsons air their first season', pt: 'Os Simpsons estreiam sua primeira temporada' },
  { id: 'pop-gameboy', year: 1989, emoji: '🎮', es: 'El Game Boy sale con Tetris incluido', en: 'The Game Boy ships with Tetris in the box', pt: 'O Game Boy chega com Tetris na caixa' },
  { id: 'pop-sonic', year: 1991, emoji: '🦔', es: 'Sega responde con Sonic', en: 'Sega answers back with Sonic', pt: 'A Sega responde com o Sonic' },
  { id: 'pop-street-fighter', year: 1991, emoji: '🥋', es: 'Street Fighter II llega a los arcades', en: 'Street Fighter II hits the arcades', pt: 'Street Fighter II chega aos fliperamas' },
  { id: 'pop-web', year: 1991, emoji: '🌐', es: 'Se publica la primera página web', en: 'The first web page goes online', pt: 'É publicada a primeira página da web' },
  { id: 'pop-mario-kart', year: 1992, emoji: '🏁', es: 'Sale Super Mario Kart', en: 'Super Mario Kart is released', pt: 'É lançado Super Mario Kart' },
  { id: 'pop-doom', year: 1993, emoji: '🔫', es: 'Doom populariza los juegos en primera persona', en: 'Doom popularises first-person shooters', pt: 'Doom populariza os jogos de tiro em primeira pessoa' },
  { id: 'pop-jurassic', year: 1993, emoji: '🦕', es: 'Jurassic Park revive a los dinosaurios', en: 'Jurassic Park brings dinosaurs back', pt: 'Jurassic Park traz os dinossauros de volta' },
  { id: 'pop-rey-leon', year: 1994, emoji: '🦁', es: 'Disney estrena El Rey León', en: 'Disney releases The Lion King', pt: 'A Disney lança O Rei Leão' },
  { id: 'pop-pulp-fiction', year: 1994, emoji: '🕺', es: 'Tarantino estrena Pulp Fiction', en: 'Tarantino releases Pulp Fiction', pt: 'Tarantino lança Pulp Fiction' },
  { id: 'pop-friends', year: 1994, emoji: '☕', es: 'Debuta Friends', en: 'Friends premieres', pt: 'Estreia Friends' },
  { id: 'pop-playstation', year: 1994, emoji: '🎮', es: 'Sony lanza la primera PlayStation', en: 'Sony launches the first PlayStation', pt: 'A Sony lança o primeiro PlayStation' },
  { id: 'pop-amazon', year: 1994, emoji: '📦', es: 'Nace Amazon vendiendo libros', en: 'Amazon is born selling books', pt: 'Nasce a Amazon vendendo livros' },
  { id: 'pop-toy-story', year: 1995, emoji: '🤠', es: 'Toy Story es la primera película hecha por computador', en: 'Toy Story is the first fully computer-animated film', pt: 'Toy Story é o primeiro filme feito todo por computador' },
  { id: 'pop-tamagotchi', year: 1996, emoji: '🐣', es: 'Los Tamagotchi piden comida desde el bolsillo', en: 'Tamagotchis start begging for food from your pocket', pt: 'Os Tamagotchis pedem comida de dentro do bolso' },
  { id: 'pop-pokemon-juego', year: 1996, emoji: '🔴', es: 'Salen los primeros juegos de Pokémon', en: 'The first Pokémon games are released', pt: 'Saem os primeiros jogos de Pokémon' },
  { id: 'pop-pokemon-tv', year: 1997, emoji: '⚡', es: 'El anime de Pokémon sale al aire', en: 'The Pokémon anime hits TV', pt: 'O anime de Pokémon vai ao ar' },
  { id: 'pop-final-fantasy', year: 1997, emoji: '⚔️', es: 'Final Fantasy VII llega a Occidente', en: 'Final Fantasy VII reaches the West', pt: 'Final Fantasy VII chega ao Ocidente' },
  { id: 'pop-titanic', year: 1997, emoji: '🚢', es: 'Titanic arrasa en los cines', en: 'Titanic sweeps the box office', pt: 'Titanic arrasa nas bilheterias' },
  { id: 'pop-google', year: 1998, emoji: '🔍', es: 'Se funda Google', en: 'Google is founded', pt: 'É fundado o Google' },
  { id: 'pop-furby', year: 1998, emoji: '🦉', es: 'Los Furby hablan solos y asustan a todos', en: 'Furbies start talking on their own', pt: 'Os Furbys falam sozinhos e assustam todo mundo' },
  { id: 'pop-ocarina', year: 1998, emoji: '🗡️', es: 'Zelda: Ocarina of Time cambia los juegos en 3D', en: 'Zelda: Ocarina of Time changes 3D gaming', pt: 'Zelda: Ocarina of Time muda os jogos em 3D' },
  { id: 'pop-matrix', year: 1999, emoji: '💊', es: 'Matrix estrena las balas en cámara lenta', en: 'The Matrix invents bullet time', pt: 'Matrix inventa as balas em câmera lenta' },
  { id: 'pop-napster', year: 1999, emoji: '🎵', es: 'Napster pone toda la música en internet', en: 'Napster puts all the music online', pt: 'Napster põe toda a música na internet' },
  { id: 'pop-bob-esponja', year: 1999, emoji: '🍍', es: 'Bob Esponja sale del fondo del mar', en: 'SpongeBob emerges from the sea floor', pt: 'Bob Esponja sai do fundo do mar' },
  { id: 'pop-gran-hermano', year: 1999, emoji: '📹', es: 'Nace Gran Hermano y con él la telerrealidad', en: 'Big Brother is born, and with it reality TV', pt: 'Nasce o Big Brother e, com ele, o reality show' },
  { id: 'pop-emoji', year: 1999, emoji: '😀', es: 'Se crean los primeros emoji en Japón', en: 'The first emoji are created in Japan', pt: 'São criados os primeiros emojis no Japão' },
  { id: 'pop-sims', year: 2000, emoji: '🏡', es: 'Los Sims dejan jugar a la vida', en: 'The Sims lets you play at life', pt: 'The Sims deixa você brincar de viver' },
  { id: 'pop-nokia', year: 2000, emoji: '📟', es: 'Sale el Nokia 3310, el celular indestructible', en: 'The indestructible Nokia 3310 goes on sale', pt: 'Chega o Nokia 3310, o celular indestrutível' },
  { id: 'pop-wikipedia', year: 2001, emoji: '📚', es: 'Nace Wikipedia', en: 'Wikipedia is born', pt: 'Nasce a Wikipédia' },
  { id: 'pop-ipod', year: 2001, emoji: '🎧', es: 'Apple lanza el iPod', en: 'Apple launches the iPod', pt: 'A Apple lança o iPod' },
  { id: 'pop-harry-potter', year: 2001, emoji: '⚡', es: 'Harry Potter llega al cine', en: 'Harry Potter reaches the big screen', pt: 'Harry Potter chega ao cinema' },
  { id: 'pop-anillos', year: 2001, emoji: '💍', es: 'Empieza la trilogía de El Señor de los Anillos', en: 'The Lord of the Rings trilogy begins', pt: 'Começa a trilogia O Senhor dos Anéis' },
  { id: 'pop-shrek', year: 2001, emoji: '🧅', es: 'Se estrena Shrek', en: 'Shrek premieres', pt: 'Estreia Shrek' },
  { id: 'pop-gta3', year: 2001, emoji: '🚕', es: 'GTA III abre el mundo abierto', en: 'GTA III opens up the open world', pt: 'GTA III abre o mundo aberto' },
  { id: 'pop-myspace', year: 2003, emoji: '🎸', es: 'Nace MySpace', en: 'MySpace is born', pt: 'Nasce o MySpace' },
  { id: 'pop-nemo', year: 2003, emoji: '🐠', es: 'Se estrena Buscando a Nemo', en: 'Finding Nemo premieres', pt: 'Estreia Procurando Nemo' },
  { id: 'pop-skype', year: 2003, emoji: '☎️', es: 'Skype deja llamar gratis por internet', en: 'Skype lets you call for free over the internet', pt: 'Skype deixa ligar de graça pela internet' },
  { id: 'pop-facebook', year: 2004, emoji: '👍', es: 'Nace Facebook en una universidad', en: 'Facebook is born in a college dorm', pt: 'Nasce o Facebook numa universidade' },
  { id: 'pop-lost', year: 2004, emoji: '🏝️', es: 'Se estrena Lost', en: 'Lost premieres', pt: 'Estreia Lost' },
  { id: 'pop-wow', year: 2004, emoji: '🐉', es: 'World of Warcraft junta millones en línea', en: 'World of Warcraft gathers millions online', pt: 'World of Warcraft reúne milhões online' },
  { id: 'pop-youtube', year: 2005, emoji: '▶️', es: 'Se sube el primer video a YouTube', en: 'The first video is uploaded to YouTube', pt: 'O primeiro vídeo é enviado ao YouTube' },
  { id: 'pop-google-maps', year: 2005, emoji: '🗺️', es: 'Aparece Google Maps', en: 'Google Maps appears', pt: 'Surge o Google Maps' },
  { id: 'pop-twitter', year: 2006, emoji: '🐦', es: 'Nace Twitter', en: 'Twitter is born', pt: 'Nasce o Twitter' },
  { id: 'pop-wii', year: 2006, emoji: '🎾', es: 'La Wii pone a todos de pie frente a la tele', en: 'The Wii gets everyone off the couch', pt: 'O Wii tira todo mundo do sofá' },
  { id: 'pop-iphone', year: 2007, emoji: '📱', es: 'Steve Jobs presenta el iPhone', en: 'Steve Jobs unveils the iPhone', pt: 'Steve Jobs apresenta o iPhone' },
  { id: 'pop-netflix', year: 2007, emoji: '📺', es: 'Netflix empieza a transmitir por internet', en: 'Netflix starts streaming online', pt: 'A Netflix começa a transmitir pela internet' },
  { id: 'pop-rickroll', year: 2007, emoji: '🎤', es: 'El Rickroll empieza a engañar a internet', en: 'The Rickroll starts trolling the internet', pt: 'O Rickroll começa a enganar a internet' },
  { id: 'pop-iron-man', year: 2008, emoji: '🦾', es: 'Iron Man abre el universo Marvel', en: 'Iron Man opens the Marvel universe', pt: 'Homem de Ferro abre o universo Marvel' },
  { id: 'pop-breaking-bad', year: 2008, emoji: '🧪', es: 'Se estrena Breaking Bad', en: 'Breaking Bad premieres', pt: 'Estreia Breaking Bad' },
  { id: 'pop-whatsapp', year: 2009, emoji: '💬', es: 'Aparece WhatsApp', en: 'WhatsApp appears', pt: 'Surge o WhatsApp' },
  { id: 'pop-angry-birds', year: 2009, emoji: '🐦', es: 'Angry Birds convierte el celular en consola', en: 'Angry Birds turns the phone into a console', pt: 'Angry Birds transforma o celular em videogame' },
  { id: 'pop-avatar', year: 2009, emoji: '🌏', es: 'Avatar rompe todos los récords de taquilla', en: 'Avatar breaks every box office record', pt: 'Avatar quebra todos os recordes de bilheteria' },
  { id: 'pop-instagram', year: 2010, emoji: '📷', es: 'Nace Instagram con fotos cuadradas', en: 'Instagram is born with square photos', pt: 'Nasce o Instagram com fotos quadradas' },
  { id: 'pop-ipad', year: 2010, emoji: '📲', es: 'Apple lanza el iPad', en: 'Apple launches the iPad', pt: 'A Apple lança o iPad' },
  { id: 'pop-minecraft', year: 2011, emoji: '⛏️', es: 'Minecraft sale de su versión beta', en: 'Minecraft leaves beta', pt: 'Minecraft sai da versão beta' },
  { id: 'pop-got', year: 2011, emoji: '🐉', es: 'Game of Thrones llega a la televisión', en: 'Game of Thrones arrives on TV', pt: 'Game of Thrones chega à televisão' },
  { id: 'pop-snapchat', year: 2011, emoji: '👻', es: 'Snapchat borra las fotos solo', en: 'Snapchat makes photos disappear on their own', pt: 'Snapchat faz as fotos sumirem sozinhas' },
  { id: 'pop-nyan', year: 2011, emoji: '🐱', es: 'El Nyan Cat cruza internet dejando un arcoíris', en: 'Nyan Cat flies across the internet leaving a rainbow', pt: 'O Nyan Cat cruza a internet deixando um arco-íris' },
  { id: 'pop-vengadores', year: 2012, emoji: '🦸', es: 'Los Vengadores se juntan por primera vez', en: 'The Avengers assemble for the first time', pt: 'Os Vingadores se reúnem pela primeira vez' },
  { id: 'pop-candy-crush', year: 2012, emoji: '🍬', es: 'Candy Crush llega a los celulares', en: 'Candy Crush arrives on phones', pt: 'Candy Crush chega aos celulares' },
  { id: 'pop-gangnam', year: 2012, emoji: '🕺', es: 'Gangnam Style llega a mil millones de vistas', en: 'Gangnam Style hits a billion views', pt: 'Gangnam Style chega a um bilhão de visualizações' },
  { id: 'pop-doge', year: 2013, emoji: '🐕', es: 'El perro Doge se convierte en meme', en: 'The Doge dog becomes a meme', pt: 'O cachorro Doge vira meme' },
  { id: 'pop-frozen', year: 2013, emoji: '❄️', es: 'Frozen y su “Libre soy” se toman el planeta', en: 'Frozen and “Let It Go” take over the planet', pt: 'Frozen e seu “Livre Estou” tomam conta do planeta' },
  { id: 'pop-gta5', year: 2013, emoji: '💰', es: 'GTA V vende como ningún juego antes', en: 'GTA V outsells every game before it', pt: 'GTA V vende como nenhum jogo antes' },
  { id: 'pop-ice-bucket', year: 2014, emoji: '🪣', es: 'El desafío del balde de hielo inunda las redes', en: 'The Ice Bucket Challenge floods social media', pt: 'O desafio do balde de gelo inunda as redes' },
  { id: 'pop-flappy', year: 2014, emoji: '🐤', es: 'Flappy Bird desaparece de las tiendas en su mejor momento', en: 'Flappy Bird vanishes from the stores at its peak', pt: 'Flappy Bird some das lojas no auge' },
  { id: 'pop-selfie-oscar', year: 2014, emoji: '🤳', es: 'La selfie de los Oscar rompe Twitter', en: 'The Oscars selfie breaks Twitter', pt: 'A selfie do Oscar quebra o Twitter' },
  { id: 'pop-vestido', year: 2015, emoji: '👗', es: 'El mundo discute si el vestido es azul o dorado', en: 'The world argues whether the dress is blue or gold', pt: 'O mundo discute se o vestido é azul ou dourado' },
  { id: 'pop-stranger-things', year: 2016, emoji: '🚲', es: 'Netflix estrena Stranger Things', en: 'Netflix premieres Stranger Things', pt: 'A Netflix estreia Stranger Things' },
  { id: 'pop-pokemon-go', year: 2016, emoji: '📱', es: 'Pokémon GO saca a todos a caminar a la calle', en: 'Pokémon GO gets everyone walking outside', pt: 'Pokémon GO põe todo mundo para andar na rua' },
  { id: 'pop-tiktok', year: 2016, emoji: '🎵', es: 'Nace TikTok', en: 'TikTok is born', pt: 'Nasce o TikTok' },
  { id: 'pop-switch', year: 2017, emoji: '🔀', es: 'Nintendo lanza la Switch', en: 'Nintendo launches the Switch', pt: 'A Nintendo lança o Switch' },
  { id: 'pop-fortnite', year: 2017, emoji: '🪂', es: 'Fortnite inventa el baile de la victoria', en: 'Fortnite invents the victory dance', pt: 'Fortnite inventa a dancinha da vitória' },
  { id: 'pop-baby-shark', year: 2018, emoji: '🦈', es: 'Baby Shark se pega en la cabeza del planeta', en: 'Baby Shark gets stuck in everyone’s head', pt: 'Baby Shark gruda na cabeça do planeta' },
  { id: 'pop-endgame', year: 2019, emoji: '💥', es: 'Avengers: Endgame cierra una saga de 22 películas', en: 'Avengers: Endgame closes a 22-film saga', pt: 'Vingadores: Ultimato fecha uma saga de 22 filmes' },
  { id: 'pop-among-us', year: 2020, emoji: '🔪', es: 'Among Us se vuelve viral dos años después de salir', en: 'Among Us goes viral two years after release', pt: 'Among Us viraliza dois anos depois de sair' },
  { id: 'pop-videollamadas', year: 2020, emoji: '💻', es: 'El mundo entero se muda a las videollamadas', en: 'The whole world moves onto video calls', pt: 'O mundo inteiro se muda para as videochamadas' },
  { id: 'pop-parasitos', year: 2020, emoji: '🎬', es: 'Parásitos gana el Oscar a mejor película', en: 'Parasite wins the Best Picture Oscar', pt: 'Parasita ganha o Oscar de melhor filme' },
  { id: 'pop-calamar', year: 2021, emoji: '🦑', es: 'El Juego del Calamar es el estreno más visto de Netflix', en: 'Squid Game becomes Netflix’s biggest premiere', pt: 'Round 6 é a estreia mais vista da Netflix' },
  { id: 'pop-chatgpt', year: 2022, emoji: '🤖', es: 'ChatGPT se hace conocido en una semana', en: 'ChatGPT becomes famous in a week', pt: 'ChatGPT fica famoso em uma semana' },
  { id: 'pop-wordle', year: 2022, emoji: '🟩', es: 'Wordle llena las redes de cuadraditos verdes', en: 'Wordle fills social media with little green squares', pt: 'Wordle enche as redes de quadradinhos verdes' },
  { id: 'pop-barbenheimer', year: 2023, emoji: '🎀', es: 'Barbie y Oppenheimer llenan los cines el mismo día', en: 'Barbie and Oppenheimer fill cinemas on the same day', pt: 'Barbie e Oppenheimer lotam os cinemas no mesmo dia' },
];
