/**
 * La Copa — datos y textos. Sin lógica ni DOM (C-2).
 *
 * Solo en español por ahora (D-98): el contenido de los minijuegos (grillas, palabras) es
 * chileno y no se traduce. Cuando lleguen inglés y portugués (LIG-32), cada idioma necesita
 * su propio contenido, no una traducción.
 */
export const GAME_ID = 'copa';

/** Los minijuegos: cómo se muestran y cómo se juegan. */
export const MINIJUEGOS = {
  linea: {
    emoji: '⏳', nombre: 'Línea Relámpago', habilidad: 'saber',
    como: [
      'Hay 8 hitos de una misma temática. El primero ya está puesto en la línea.',
      'Los otros 7 salen de a uno: toca el hueco donde crees que va y confirma.',
      'Si te equivocas, la carta queda en su lugar marcada en rojo y sigues con la siguiente.',
    ],
    puntaje: 'Ganas un punto por cada carta bien puesta, de 0 a 7. Si empatas, gana quien tardó menos.',
  },
  numero: {
    emoji: '🔢', nombre: 'El Número del Día', habilidad: 'deducir',
    como: [
      'Hay un número secreto de 4 cifras distintas, el mismo para todos. Puede empezar con cero.',
      'Cada intento te dice cuántas famas tiene (cifra correcta en su lugar) y cuántos toques (cifra correcta en otro lugar).',
      'Tienes 10 intentos para descubrirlo.',
    ],
    puntaje: 'Mientras menos intentos uses, más puntos: 10 si lo sacas al primero y 1 si lo sacas al décimo. Si empatas, gana quien tardó menos.',
  },
  conexiones: {
    emoji: '🔗', nombre: 'Conexiones', habilidad: 'asociar',
    como: [
      'Hay 16 palabras que forman 4 grupos de 4, de más fácil a más difícil.',
      'Elige 4 palabras que creas que van juntas y confirma.',
      'Puedes equivocarte 3 veces: al cuarto error se termina. Si te faltó una sola palabra para un grupo, te avisamos.',
    ],
    puntaje: 'Cada grupo vale 25 puntos y cada error resta 5, de 0 a 100. Si empatas, gana quien tardó menos.',
  },
  solitario: {
    emoji: '⚓', nombre: 'Batalla Naval: Solitario', habilidad: 'lógica',
    como: [
      'Hay una flota escondida: los mismos cinco barcos de Batalla Naval, de 5, 4, 3, 3 y 2 casillas.',
      'Los números de cada fila y columna dicen cuántas casillas de barco tienen. Los barcos no se tocan, ni siquiera en diagonal.',
      'Toca una casilla una vez para marcar agua, otra vez para marcar barco y una tercera para limpiarla. Cuando creas que está, toca Revisar.',
    ],
    puntaje: 'Parte en 100 puntos y cada revisión fallida resta 15, con un mínimo de 10 si la resuelves. Si empatas, gana quien tardó menos.',
  },
  dudo: {
    emoji: '🎲', nombre: '¿Dudo o le creo?', habilidad: 'probabilidad',
    como: [
      'Son 8 manos de Dudo. En cada una ves tus 5 dados, cuántos dados hay en la mesa y lo que apostó el rival.',
      'Los ases son comodín, salvo que la apuesta sea de ases.',
      'Elige si dudas o le crees, y se destapa la mesa.',
    ],
    puntaje: 'No importa lo que salió sino qué tan buena era tu decisión: ganas la probabilidad de que tu elección fuera cierta, de 0 a 100 por mano. Si empatas, gana quien tardó menos.',
  },
  anio: {
    emoji: '📅', nombre: '¿En qué año?', habilidad: 'estimar',
    como: [
      'Hay 6 hitos. Escribe en qué año crees que pasó cada uno.',
      'Si fue antes de Cristo, toca el botón a. C. antes de confirmar.',
    ],
    puntaje: 'Cada hito da 100 puntos si aciertas el año exacto y menos mientras más te alejas. En los hitos antiguos el margen es más amplio. Si empatas, gana quien tardó menos.',
  },
  final: {
    emoji: '🏁', nombre: 'La Gran Final', habilidad: 'todo',
    como: [
      'Son cinco rondas cortas seguidas, una de cada minijuego de la copa: 4 hitos, un número de 3 cifras, un solitario chico, 3 manos de Dudo y 2 años.',
      'Antes de cada ronda verás cómo se juega.',
      'La final vale el doble de puntos en la tabla.',
    ],
    puntaje: 'Cada ronda vale de 0 a 100, en total de 0 a 500. Si empatas, gana quien tardó menos.',
  },
};

/** Las rondas de la Gran Final: versiones cortas, con su propia explicación. */
export const RONDAS_FINAL = {
  linea: 'Cuatro hitos: el primero ya está puesto y colocas los otros tres. Vale 33 puntos por carta bien puesta.',
  numero: 'Un número de 3 cifras distintas en 7 intentos. Si lo sacas al primero son 100 puntos, y cada intento extra resta 15.',
  solitario: 'Un solitario de 6 × 6 con tres barcos, de 3, 3 y 2 casillas. Son 100 puntos y cada revisión fallida resta 25.',
  dudo: 'Tres manos de ¿Dudo o le creo? Ganas el promedio de la probabilidad de acertar de tus decisiones.',
  anio: 'Dos hitos para decir el año. Ganas el promedio de los puntos de los dos.',
};

/** Los textos. Un solo idioma por ahora (D-98): la forma `const ES` es la de todos los juegos. */
const ES = {
  title: 'La Copa',
  menu: '‹ Menú',
  chip: '🏆 La Copa',
  lead: 'Un torneo entre amigos que dura una semana. Cada día hay un minijuego distinto, el mismo para todos, que se juega una sola vez. Gana quien suma más puntos al final.',
  howTitle: 'Cómo funciona',
  howItems: [
    'Una persona crea la copa y comparte el link con el grupo.',
    'Cada uno entra con su nombre y un PIN de 4 números, desde el celular o el computador.',
    'Cada día se abre un minijuego. Tienes ese día y el siguiente para jugarlo, una sola vez.',
    'Según cómo te fue frente al resto, sumas puntos: 10 el primero, 8 el segundo, 6 el tercero y así.',
    'Tienes un comodín que duplica los puntos de un día, y la Gran Final del último día vale doble para todos.',
  ],
  create: '🏆 Crear una copa',
  haveCode: 'Tengo un código',
  codeLabel: 'Código de la copa',
  codePlaceholder: 'K7Q2X',
  go: 'Entrar',
  mine: 'Tus copas',
  mineDay: 'Día {d} de {n}',
  mineBefore: 'Parte el {fecha}',
  mineOver: 'Terminó',

  // Crear
  createTitle: 'Nueva copa',
  fCopa: 'Nombre de la copa',
  fCopaPh: 'Copa de la oficina',
  fMode: '¿Cuánto dura?',
  mode3: 'Copa de 3 días',
  mode3Sub: 'Solo para probar: una línea, Conexiones y la final.',
  mode7: 'Copa de 7 días',
  mode7Sub: 'La semana completa, un juego distinto cada día.',
  fStart: '¿Cuándo parte?',
  startToday: 'Hoy',
  startTomorrow: 'Mañana',
  startHint: 'Cada día empieza a las 00:00 y termina a las 23:59, hora de Chile.',
  fYou: 'Tu nombre',
  fYouPh: 'Como te conocen en el grupo',
  fPin: 'Tu PIN de 4 números',
  fPin2: 'Repite el PIN',
  pinHint: 'Con tu nombre y este PIN entras desde cualquier celular o computador. No lo compartas.',
  createGo: 'Crear la copa',
  creating: 'Creando la copa…',

  // Entrar
  inviteTitle: 'Te invitaron a una copa',
  inviteInfo: '{modo} · parte el {fecha} · {n} de {max} jugadores',
  inviteStarted: '{modo} · va en el día {d} de {n} · {k} de {max} jugadores',
  imNew: 'Soy nuevo',
  imIn: 'Ya estoy inscrito',
  pickName: 'Toca tu nombre',
  joinGo: 'Inscribirme',
  loginGo: 'Entrar como {name}',
  joining: 'Entrando…',
  lateJoin: 'Los días que ya cerraron quedan con 0 puntos, pero todavía puedes pelear la copa.',
  closedJoin: 'Esta copa ya está en la final y no recibe más jugadores. Si ya estás inscrito, entra con tu nombre y tu PIN.',

  // Errores
  errNombre: 'Escribe un nombre.',
  errCopa: 'Ponle un nombre a la copa.',
  errMode: 'Elige si la copa dura 3 o 7 días.',
  errMode7: 'Toca Copa de 7 días para elegirla.',
  errStart: 'Elige si la copa parte hoy o mañana.',
  errPin: 'El PIN tiene que tener 4 números.',
  errPin2: 'Los dos PIN no son iguales. Escríbelos de nuevo.',
  errPinWrong: 'Ese PIN no es el de {name}. Si lo olvidaste, pídele a quien creó la copa que te ponga uno nuevo.',
  errRepetido: 'Ya hay alguien con ese nombre en la copa. Si eres tú, entra por Ya estoy inscrito.',
  errLlena: 'La copa ya tiene 10 jugadores, que es el máximo.',
  errCerrada: 'Esta copa ya está en la final y no recibe más jugadores.',
  errNoExiste: 'No encontramos una copa con ese código. Revisa que esté bien escrito.',
  errCodigo: 'El código tiene 5 letras.',
  errVentana: 'El tiempo para jugar este día ya se terminó.',
  errYaJugado: 'Este día ya lo jugaste.',
  errComodin: 'El comodín ya no se puede usar en este día.',
  errPermiso: 'Este celular no tiene permiso para hacer eso. Vuelve a entrar con tu nombre y tu PIN.',
  errConfig: 'La Copa todavía no está habilitada en el servidor. Avísale a quien mantiene juegosdesalon.cl.',
  errOffline: 'No pudimos conectarnos. Puede ser tu internet o que haya mucha gente jugando. Intenta nuevamente en unos minutos.',
  errNet: 'Algo falló al conectarnos. Intenta nuevamente en unos minutos.',
  retry: 'Intentar de nuevo',

  // Tablero
  dayOf: 'Día {d} de {n}',
  before: 'Parte el {fecha} a las 00:00',
  beforeSub: 'Mientras tanto, comparte el link para que se inscriba el resto del grupo.',
  over: 'La copa terminó',
  today: 'Hoy',
  yesterday: 'Ayer · último día para jugarlo',
  closesIn: 'Cierra en {t}',
  untilTonight: 'Tienes hasta hoy a las 23:59 para jugarlo (quedan {t}).',
  untilTomorrowNight: 'Tienes hasta mañana a las 23:59 para jugarlo.',
  play: 'Jugar',
  resume: 'Seguir jugando',
  played: 'Ya lo jugaste',
  seeResult: 'Ver resultado',
  lost: 'No lo jugaste',
  whoPlayed: 'Ya jugaron: {names}',
  nobodyPlayed: 'Nadie lo ha jugado todavía.',
  missing: 'Faltan: {names}',
  tableTitle: 'Tabla',
  tableHidden: 'Los puntos de los días que no has jugado aparecen cuando los juegues o cuando cierren.',
  pts: 'pts',
  calendarTitle: 'Calendario',
  myDays: 'Tus días',
  dayShort: 'D{d}',
  opensOn: 'Se abre el {fecha}',
  lastDay: 'Último día para jugarlo',
  notPlayed: 'No lo jugaste',
  progressTitle: 'Tu posición día a día',
  progressHint: 'Tu línea es la de color y las grises son las del resto. Toca un punto para ver quién era.',
  progressPoint: 'Día {d}: {name} iba {pos}º',
  calToday: 'hoy',
  x2: '×2',
  wildUsed: 'comodín',
  players: 'Jugadores ({n} de {max})',
  shareInvite: '📤 Invitar al grupo',
  adminTab: '⚙️ Administrar',
  you: 'tú',
  leave: 'Salir de esta copa en este celular',
  leaveConfirm: '¿Salir de la copa en este celular? Para volver vas a necesitar tu nombre y tu PIN.',

  // Antes de jugar
  howToPlay: 'Cómo se juega',
  scoring: 'Puntaje',
  wildTitle: 'Comodín ×2',
  wildOff: 'Tienes un comodín por copa: duplica los puntos de un día. Se activa antes de empezar y no vale en la final.',
  wildUse: 'Usar el comodín en este día',
  wildOn: 'Comodín activado: este día vale el doble.',
  wildGone: 'Ya usaste tu comodín en el día {d}.',
  wildFinal: 'En la final no se puede usar el comodín, pero vale el doble para todos.',
  wildConfirm: '¿Usar tu único comodín en el día {d}? No se puede deshacer.',
  start: 'Empezar',
  startWarn: 'Tienes un solo intento. Si cierras la página, al volver sigues donde quedaste.',
  timer: '⏱ {t}',

  // Resultado del día
  resultTitle: 'Día {d}: {juego}',
  yourScore: 'Tu puntaje',
  provisional: 'Por ahora vas {pos} de {n} en este día. La posición es provisoria hasta que el día cierre.',
  finalPos: 'Quedaste {pos} de {n} en este día y sumaste {pts} puntos.',
  dayTable: 'Resultados del día',
  shareCard: '📤 Compartir mi resultado',
  toBoard: 'Volver a la copa',
  sending: 'Guardando tu resultado…',
  sendFail: 'No pudimos guardar tu resultado. Revisa tu internet e intenta nuevamente: tu partida está guardada en este celular.',

  // Final
  podiumTitle: '¡{name} ganó la copa!',
  podiumTie: '¡Empate en la copa!',
  medalChamp: '🏆 Campeón',
  medalWins: '🥇 Más días ganados',
  medalComeback: '🚀 La remontada',
  medalLast: '🏮 Farolito rojo',
  shareSummary: '📤 Compartir el resumen',

  // Admin
  adminTitle: 'Administrar la copa',
  adminMsgs: 'Mensajes para el grupo',
  msgInvite: 'Invitación',
  msgToday: 'Recordatorio del día',
  msgTable: 'Tabla parcial',
  msgFinal: 'Resumen final',
  adminPlayers: 'Jugadores',
  kick: 'Sacar',
  unkick: 'Volver a meter',
  rename: 'Renombrar',
  newPin: 'Nuevo PIN',
  kicked: 'fuera',
  kickConfirm: '¿Sacar a {name} de la copa? Deja de aparecer en la tabla y sus puntos no cuentan. Se puede deshacer.',
  renamePrompt: 'Nuevo nombre para {name}',
  pinPrompt: 'Escribe un PIN nuevo de 4 números para {name}. Después díselo a esa persona.',
  pinDone: 'Listo. El nuevo PIN de {name} es {pin}.',
  copied: 'Copiado. Pégalo en el chat del grupo.',

  // Mensajes para compartir (van por WhatsApp)
  shareInviteText: 'Te invito a la {copa}: {dias} días, un juego distinto cada día y una tabla para ver quién manda. Parte el {fecha}. Entra con tu nombre y un PIN de 4 números en este link:',
  shareTodayText: 'Día {d} de {n} en la {copa}: hoy toca {juego}. Tienes hasta {hasta} para jugarlo.',
  shareTodayGrace: 'Si te falta el de ayer ({juego}), todavía lo puedes jugar hasta hoy a medianoche.',
  shareTodayMissing: 'Faltan por jugar hoy: {names}.',
  shareBeforeText: 'La {copa} parte el {fecha}. El primer juego es {juego}. Si todavía no te inscribes, entra con tu nombre y un PIN de 4 números en este link:',
  shareTableText: 'Tabla de la {copa} después del día {d}:\n{tabla}',
  shareTableMissing: 'Todavía no juegan el día {d}: {names}.',
  shareFinalText: 'Terminó la {copa}. {campeon}\n{podio}',
  shareFinalChamp: 'Ganó {name} con {pts} puntos.',
  shareCardText: '{copa} · Día {d} {emoji} {resumen}',
  untilTomorrow: 'mañana a medianoche',
  untilToday: 'hoy a medianoche',

  // Pantalla de minijuego
  confirm: 'Confirmar',
  placeHere: 'Colocar aquí',
  pickSlot: 'Toca un hueco de la línea',
  cardOf: 'Carta {i} de {n}',
  wentWrong: 'No era ahí. {c} fue en {y}.',
  wentAfter: 'Va después de {c} ({y})',
  wentBefore: 'antes de {c} ({y})',
  wentBeforeSolo: 'Va antes de {c} ({y})',
  wentJoin: ' y ',
  guess: 'Probar {v}',
  typeDigits: 'Escribe {n} cifras distintas',
  famas: '{n} famas', fama1: '1 fama',
  toques: '{n} toques', toque1: '1 toque',
  triesLeft: 'Te quedan {n} intentos.',
  tryLeft1: 'Te queda 1 intento.',
  solved: '¡Lo sacaste!',
  notSolved: 'Se acabaron los intentos. El número era {v}.',
  select4: 'Elige 4 palabras',
  oneAway: '¡A una!',
  wrongGroup: 'No es un grupo.',
  alreadyTried: 'Ya probaste esas cuatro.',
  mistakesLeft: 'Errores disponibles: {n}',
  shuffle: 'Barajar',
  deselect: 'Limpiar',
  groupsOk: '¡Encontraste los 4 grupos!',
  groupsFail: 'Se acabaron los errores. Estos eran los grupos.',
  check: 'Revisar',
  giveUp: 'Rendirse',
  giveUpConfirm: '¿Rendirte? Este día quedaría con 0 puntos.',
  checkBad: 'Todavía hay casillas que no calzan. Cada revisión fallida resta 15 puntos.',
  checkOk: '¡Encontraste la flota!',
  gaveUp: 'Te rendiste. Esta era la flota.',
  shipsLeft: 'Casillas de barco: {m} de {t}',
  tableDice: '{n} dados en la mesa',
  yourDice: 'Tus dados',
  bid: 'El rival apuesta',
  bidText: '{n} × {cara}',
  doubt: 'Dudo',
  believe: 'Le creo',
  handOf: 'Mano {i} de {n}',
  thereWere: 'Había {n}. La apuesta era {v}.',
  trueWord: 'cierta', falseWord: 'falsa',
  chanceWas: 'La probabilidad de que fuera cierta era {p} %. Ganaste {pts} puntos.',
  next: 'Siguiente',
  yearOf: 'Hito {i} de {n}',
  yearPh: 'Año',
  bc: 'a. C.',
  yearWas: 'Fue en {v}. Ganaste {pts} puntos.',
  roundOf: 'Ronda {i} de 5',

  // Laboratorio y práctica (D-101)
  backToLabs: '🧪 Volver al laboratorio',
  backToLabsShort: '‹ Laboratorio',
  practiceTitle: 'Práctica en el laboratorio',
  practiceHint: 'Es una práctica: no cuenta para ninguna copa y puedes jugarla las veces que quieras.',
  practiceSeed: 'Esta partida es la semilla {semilla}. Si vas a reportar un problema, con ella se repite la misma partida.',
  practiceAgain: 'Jugar otra vez con otro contenido',
  practiceSame: 'Repetir exactamente esta partida',

  // Reportes (LIG-42)
  reportButton: '🐞 Reportar un problema o dejar un comentario',
  reportTitle: 'Cuéntanos qué pasó',
  reportLead: 'Describe el problema o el comentario con tus palabras: qué hiciste, qué esperabas y qué pasó. Lo lee quien mantiene juegosdesalon.cl.',
  reportPlaceholder: 'Por ejemplo: toqué Confirmar en Conexiones y no pasó nada.',
  reportNamePh: 'Tu nombre (opcional)',
  reportContext: 'Lo que se envía además de tu texto',
  reportSend: 'Enviar',
  reportEmpty: 'Escribe qué pasó antes de enviar.',
  reportThanks: '¡Gracias! Tu mensaje llegó y lo vamos a revisar.',
  reportBack: 'Volver',
  reportCancel: 'Cancelar',
  sending2: 'Enviando…',

  // Barra del modo de prueba
  testBar: 'Modo de prueba',
  testHour: '+1 h',
  testDay: '+1 día',
  testNow: 'Hoy',
  roundStart: 'Empezar la ronda',
  roundNext: 'Siguiente ronda',
  roundDone: 'Ronda terminada: {pts} puntos.',
  finalSoFar: 'Llevas {pts} de {max} puntos.',
  seeResults: 'Ver resultado',
};

export const LOCALES = { es: ES };
