/**
 * La Copa — datos y textos. Sin lógica ni DOM (C-2).
 *
 * Solo en español por ahora (D-98): el contenido de los minijuegos (grillas, palabras) es
 * chileno y no se traduce. Cuando lleguen inglés y portugués (LIG-32), cada idioma necesita
 * su propio contenido, no una traducción.
 */
export const GAME_ID = 'copa';

/** Los minijuegos: cómo se muestran y cómo se juegan. */
export const MINIJUEGOS = {
  linea: {
    emoji: '⏳', nombre: 'Línea Relámpago', habilidad: 'saber',
    como: [
      'Hay 10 hitos de una misma temática. El primero ya está puesto en la línea y los otros 9 están en tu mano.',
      'Toca una carta de tu mano y después el lugar de la línea donde va (o arrástrala hasta ahí), y toca Colocar aquí. Puedes jugarlas en el orden que quieras.',
      'Si te equivocas, la carta queda en su lugar marcada en rojo y sigues con las demás.',
    ],
    puntaje: 'Va de 0 a 100 según la parte de las cartas que pongas bien: las 9 bien son 100 puntos. Si empatas, gana quien tardó menos.',
  },
  numero: {
    emoji: '🔢', nombre: 'Toque y Fama: adivina el número', habilidad: 'deducir',
    como: [
      'Hay un número secreto de 4 cifras distintas, el mismo para todos. Puede empezar con cero.',
      'Escribe un número de 4 cifras distintas y toca Probar. Cada intento te dice cuántas famas tiene (cifra correcta en su lugar) y cuántos toques (cifra correcta en otro lugar).',
      'Mantén apretada una cifra para tacharla cuando sepas que no está. Tienes 10 intentos.',
    ],
    puntaje: 'Mientras menos intentos uses, más puntos: 100 si lo sacas al primero y 10 menos por cada intento más, hasta 10 si lo sacas al décimo. Si empatas, gana quien tardó menos.',
  },
  conexiones: {
    emoji: '🔗', nombre: 'Conexiones', habilidad: 'asociar',
    como: [
      'Hay 16 palabras que forman 4 grupos de 4, de más fácil a más difícil. Ojo: algunas palabras parecen de dos grupos.',
      'Toca 4 palabras que creas que van juntas y toca Confirmar. Barajar cambia el orden de las palabras y Limpiar suelta las que elegiste.',
      'Tienes 4 errores disponibles: al cuarto se termina. Si te faltó una sola palabra para un grupo, te avisamos.',
    ],
    puntaje: 'Cada grupo vale 25 puntos y cada error resta 5, de 0 a 100. Si empatas, gana quien tardó menos.',
  },
  reinas: {
    emoji: '👑', nombre: 'Reinas', habilidad: 'lógica',
    como: [
      'Pon una reina en cada fila, en cada columna y en cada zona de color.',
      'Dos reinas nunca se pueden tocar, ni siquiera en diagonal.',
      'Toca una casilla para poner o sacar una reina. Mantenla apretada para marcarla con una X y descartarla. Hay una sola solución y se llega deduciendo, sin adivinar.',
    ],
    puntaje: 'Puntúa el tiempo que tardas en resolverlo: hasta 30 segundos vale 100 puntos, y después baja parejo hasta 10 puntos a los 5 minutos. Equivocarse no resta: las reinas que chocan se ven en rojo y las corriges. Si te rindes, ves la solución y el juego da 0 puntos.',
  },
  letras: {
    emoji: '🔤', nombre: 'Toque y Fama: Palabra', habilidad: 'deducir',
    como: [
      'Hay una palabra secreta de 5 letras distintas, la misma para todos.',
      'Escribe 5 letras distintas, aunque no formen una palabra, y toca Probar. Cada intento te dice cuántas famas (letra correcta en su lugar) y cuántos toques (letra correcta en otro lugar) tiene, y cada letra se pinta: amarilla si es fama y celeste si es toque.',
      'Mantén apretada una letra para tacharla cuando sepas que no está. Tienes 8 intentos.',
    ],
    puntaje: 'Cada letra que encuentras en su lugar suma 10 puntos, una sola vez aunque la repitas en otros intentos. Si sacas la palabra, sumas 50 más, menos 5 por cada intento después del primero. Va de 0 a 100 y, si empatas, gana quien tardó menos.',
  },
  anio: {
    emoji: '📅', nombre: '¿En qué año?', habilidad: 'estimar',
    como: [
      'Hay 6 hitos. Escribe en qué año crees que pasó cada uno y toca OK.',
      'Si fue antes de Cristo, toca el botón a. C. antes de tocar OK.',
    ],
    puntaje: 'Cada hito da 100 puntos si aciertas el año exacto y menos mientras más te alejas, y tu puntaje es el promedio de los seis, de 0 a 100. En los hitos antiguos el margen es más amplio. Si empatas, gana quien tardó menos.',
  },
  zip: {
    emoji: '〰️', nombre: 'Zip', habilidad: 'lógica', labs: true,
    como: [
      'Dibuja un solo trazo que parta en el 1, pase por todas las casillas una sola vez y toque los números en orden. Termina en el último número, con todas las casillas pintadas.',
      'Arrastra el dedo desde el 1. Para corregir, vuelve con el dedo por el mismo camino o toca una casilla del trazo para cortarlo ahí.',
      'Tienes 3 minutos para resolver todos los niveles que puedas. Cada nivel es igual o más grande que el anterior.',
    ],
    puntaje: 'Cada nivel resuelto vale 10 puntos, hasta 100. Si empatas, gana quien resolvió su último nivel antes.',
  },
  tango: {
    emoji: '☀️', nombre: 'Tango', habilidad: 'lógica', labs: true,
    como: [
      'Llena la grilla con soles y lunas: cada fila y cada columna lleva tres de cada uno.',
      'Nunca puede haber tres iguales seguidos. Un = entre dos casillas dice que son iguales y un ≠ que son distintas.',
      'Toca una casilla para poner un sol, otra vez para una luna y una tercera para limpiarla. Hay una sola solución.',
      'Si te atascas, abre la sección Consejos o toca Pista: revela una casilla y resta 15 puntos.',
    ],
    puntaje: 'Parte en 100 puntos: cada jugada que rompe una regla resta 10 y cada pista resta 15, con un mínimo de 10. Si empatas, gana quien tardó menos.',
  },
  final: {
    emoji: '🏁', nombre: 'La Gran Final', habilidad: 'todo',
    como: [
      'Son cinco rondas cortas seguidas, una de cada minijuego de la copa: 4 hitos, un número de 3 cifras, unas reinas chicas, una palabra en 6 intentos y 2 años.',
      'Antes de cada ronda verás cómo se juega.',
      'La final vale el doble de puntos en la tabla.',
    ],
    puntaje: 'Cada ronda vale de 0 a 100 y tu puntaje es el promedio de las cinco, de 0 a 100. Si empatas, gana quien tardó menos.',
  },
};

/** Las rondas de la Gran Final: versiones cortas, con su propia explicación. */
export const RONDAS_FINAL = {
  linea: 'Cuatro hitos: el primero ya está puesto y colocas los otros tres. Vale 33 puntos por carta bien puesta.',
  numero: 'Un número de 3 cifras distintas en 7 intentos. Si lo sacas al primero son 100 puntos, y cada intento extra resta 15.',
  reinas: 'Unas reinas de 6 × 6: una por fila, por columna y por zona, sin tocarse. Resolverlas vale 100 puntos, y equivocarse no resta.',
  letras: 'Una palabra de 5 letras distintas en 6 intentos. Cada letra que encuentras en su lugar suma 10 puntos, y sacarla suma 50 más, menos 5 por cada intento después del primero.',
  anio: 'Dos hitos para decir el año. Ganas el promedio de los puntos de los dos.',
}

/** Los textos. Un solo idioma por ahora (D-98): la forma `const ES` es la de todos los juegos. */
const ES = {
  title: 'La Copa',
  menu: '‹ Menú',
  chip: '🏆 La Copa',
  lead: 'Un torneo entre amigos que dura una semana. Cada día hay un minijuego distinto, el mismo para todos, que se juega una sola vez. Quien acumula más puntos al final se lleva la gloria.',
  howTitle: 'Cómo funciona',
  howItems: [
    'Una persona crea la copa y comparte el link con el grupo.',
    'Cada uno entra con su nombre y un PIN de 4 números, desde el celular o el computador.',
    'Cada día se abre un minijuego. Tienes ese día y el siguiente para jugarlo, una sola vez.',
    'Según cómo te fue frente al resto, sumas puntos: 10 el primero, 8 el segundo, 6 el tercero y así.',
    'Tienes un comodín que duplica los puntos de un día, y la Gran Final del último día vale doble para todos.',
  ],
  create: '🏆 Crear una copa',
  haveCode: 'Tengo un código',
  codeLabel: 'Código de la copa',
  codePlaceholder: 'K7Q2X',
  go: 'Entrar',
  mine: 'Tus copas',
  mineDay: 'Día {d} de {n}',
  mineBefore: 'Parte el {fecha}',
  mineOver: 'Terminó',

  // Crear
  createTitle: 'Nueva copa',
  fCopa: 'Nombre de la copa',
  fCopaPh: 'Copa de la oficina',
  fMode: '¿Cuánto dura?',
  mode3: 'Copa de 3 días',
  mode3Sub: 'Solo para probar: una línea, Conexiones y la final.',
  mode7: 'Copa de 7 días',
  mode7Sub: 'La semana completa, un juego distinto cada día.',
  fStart: '¿Cuándo parte?',
  startToday: 'Hoy',
  startTomorrow: 'Mañana',
  startHint: 'Cada día empieza a las 00:00 y termina a las 23:59, en {zona}.',
  startZone: 'Los días de la copa van de 00:00 a 23:59 en {zona}.',
  zones: { 'America/Los_Angeles': 'hora del Pacífico (Los Ángeles, California)', 'America/Santiago': 'hora de Chile' },
  zoneOther: 'la zona horaria {tz}',
  fYou: 'Tu nombre',
  fYouPh: 'Como te conocen en el grupo',
  fPin: 'Tu PIN de 4 números',
  fPin2: 'Repite el PIN',
  pinHint: 'Con tu nombre y este PIN entras desde cualquier celular o computador. No lo compartas.',
  createGo: 'Crear la copa',
  creating: 'Creando la copa…',

  // Entrar
  inviteTitle: 'Te invitaron a una copa',
  inviteInfo: '{dias} días · Parte el {fecha} · {inscritos}',
  inviteStarted: '{dias} días · Va en el día {d} de {n} · {inscritos}',
  inviteEnded: '{dias} días · Terminó · {inscritos}',
  signedUp: '{n} jugadores inscritos',
  signedUpOne: '1 jugador inscrito',
  imNew: 'Soy nuevo',
  imIn: 'Ya estoy inscrito',
  pickName: 'Toca tu nombre',
  joinGo: 'Inscribirme',
  loginGo: 'Entrar como {name}',
  joining: 'Entrando…',
  lateJoin: 'Los días que ya cerraron quedan con 0 puntos, pero todavía puedes pelear la copa.',
  closedByAdmin: 'El admin cerró la inscripción de esta copa. Si ya estás inscrito, entra con tu nombre y tu PIN.',
  closedEnded: 'Esta copa ya terminó. Si participaste, entra con tu nombre y tu PIN para ver el podio y la tabla final.',
  closedJoin: 'Esta copa ya está en la final y no recibe más jugadores. Si ya estás inscrito, entra con tu nombre y tu PIN.',

  // Errores
  errNombre: 'Escribe un nombre.',
  errCopa: 'Ponle un nombre a la copa.',
  errMode: 'Elige si la copa dura 3 o 7 días.',
  errMode7: 'Toca Copa de 7 días para elegirla.',
  errStart: 'Elige si la copa parte hoy o mañana.',
  errPin: 'El PIN tiene que tener 4 números.',
  errPin2: 'Los dos PIN no son iguales. Escríbelos de nuevo.',
  errPinWrong: 'Ese PIN no es el de {name}. Si lo olvidaste, pídele a quien creó la copa que te ponga uno nuevo.',
  errRepetidoPin: 'Ya hay alguien con ese nombre en la copa y ese PIN no es el de {name}. Si eres tú, revisa tu PIN; si no, elige otro nombre.',
  welcomeBack: 'Hola de nuevo, {name}: ya estabas inscrito, así que entraste.',
  errRepetido: 'Ya hay alguien con ese nombre en la copa. Si eres tú, entra por Ya estoy inscrito.',
  errLlena: 'La copa ya tiene 10 jugadores, que es el máximo.',
  errCerrada: 'Esta copa ya está en la final y no recibe más jugadores.',
  deleteTitle: 'Eliminar la copa',
  deleteLead: 'Borra la copa para todos: los jugadores, los resultados y la tabla. No se puede deshacer.',
  deleteGo: 'Eliminar la copa',
  deleteConfirm1: '¿Eliminar la copa "{copa}" para todos? Se borran los jugadores, los resultados y la tabla, y no se puede deshacer.',
  deleteConfirm2: 'Para confirmar, escribe el nombre de la copa: {copa}',
  deleteMismatch: 'El nombre no coincide, así que no se eliminó nada.',
  deletedTitle: 'Copa eliminada',
  deletedDone: 'La copa "{copa}" se eliminó para todos. Quien la tenga abierta va a ver que ya no existe.',
  deletedBack: 'Volver al inicio',
  copaDeleted: 'Esta copa ya no existe: su admin la eliminó.',
  fLink: 'Link de la copa (opcional)',
  fLinkPh: 'pirata',
  fLinkHint: 'Si le pones un nombre, el link queda como juegosdesalon.cl/copa/?pirata. Si no, lleva un código de 5 letras.',
  fLinkChecking: 'Revisando si {url} está libre…',
  fLinkFree: '✓ {url} está libre.',
  fLinkTaken: 'Otra copa ya usa {url}. Prueba con otro nombre.',
  fLinkBad: 'El link {url} no sirve: usa de 3 a 20 letras, números o guiones (y que no sean 5 letras solas).',
  errAlias: 'Otra copa ya usa ese link. Prueba con otro nombre.',
  errNoAlias: 'No encontramos una copa con el link ?{a}. Revisa que esté bien escrito.',
  adminWelcomeAlias: 'Como tu link es fácil de adivinar, cuando estén todos cierra la inscripción para que no se sume nadie más.',
  errNoExiste: 'No encontramos una copa con ese código. Revisa que esté bien escrito.',
  errCodigo: 'El código tiene 5 letras.',
  errVentana: 'El tiempo para jugar este día ya se terminó.',
  errYaJugado: 'Este día ya lo jugaste.',
  errComodin: 'El comodín ya no se puede usar en este día.',
  errPermiso: 'Este celular no tiene permiso para hacer eso. Vuelve a entrar con tu nombre y tu PIN.',
  errConfig: 'La Copa todavía no está habilitada en el servidor. Avísale a quien mantiene juegosdesalon.cl.',
  errOffline: 'No pudimos conectarnos. Puede ser tu internet o que haya mucha gente jugando. Revisa tu conexión y vuelve a intentarlo: lo que ya hiciste no se pierde.',
  errNet: 'Algo falló al conectarnos. Intenta nuevamente en unos minutos.',
  retry: 'Intentar de nuevo',

  // Tablero
  dayOf: 'Día {d} de {n}',
  before: 'Parte el {fecha} a las 00:00',
  needSecond: 'Para jugar hace falta al menos un competidor más. Comparte la invitación: apenas se inscriba alguien, se puede jugar.',
  needSecondBefore: 'La copa necesita al menos 2 jugadores para partir. Comparte el link para que se inscriba el resto del grupo.',
  labNeedSecond: 'Para pasar de día hace falta al menos un competidor más.',
  errFaltan: 'Hace falta al menos un competidor más para jugar.',
  beforeSub: 'Mientras tanto, comparte el link para que se inscriba el resto del grupo.',
  over: 'La copa terminó',
  today: 'Hoy',
  yesterday: 'Ayer · último día para jugarlo',
  closesIn: 'Cierra en {t}',
  untilTonight: 'Tienes hasta hoy a las 23:59 para jugarlo (quedan {t}).',
  untilTomorrowNight: 'Tienes hasta mañana a las 23:59 para jugarlo.',
  play: 'Jugar',
  resume: 'Seguir jugando',
  played: 'Ya lo jugaste',
  seeResult: 'Ver resultado',
  lost: 'No lo jugaste',
  whoPlayed: 'Ya jugaron: {names}',
  nobodyPlayed: 'Nadie lo ha jugado todavía.',
  missing: 'Faltan: {names}',
  tableTitle: 'Tabla',
  blockPending: 'Todavía no abre',
  blockHidden: 'Ya lo jugó: sus puntos se ven cuando juegues tú o cuando cierre el día',
  blockOpen: 'Abierto: todavía no lo juega',
  blockMissed: 'No lo jugó y ya cerró',
  legendPoints: 'puntos',
  legendHidden: 'jugado',
  legendOpen: 'por jugar',
  legendMissed: 'no jugó',
  legendPending: 'todavía no abre',
  tableHidden: 'Los puntos de los días que no has jugado aparecen cuando los juegues o cuando cierren.',
  pts: 'pts',
  calendarTitle: 'Calendario',
  myDays: 'Calendario',
  dayShort: 'D{d}',
  opensOn: 'Se abre el {fecha}',
  lastDay: 'Día de gracia: puedes jugarlo hasta hoy a las 23:59',
  notPlayed: 'No lo jugaste',
  progressTitle: 'Posiciones día a día',
  progressHint: 'Cada jugador tiene su color y la tuya es la línea más gruesa. Toca un nombre o un punto para destacar su línea.',
  progressYou: '{name} (tú)',
  shareImage: 'Compartir',
  imageSubtitle: 'Tabla de posiciones · día {d} de {n}',
  imageDownloaded: 'Listo: la imagen se descargó.',
  fewerGames: '{name} (-{n}J)',
  fewerGamesNote: '(-1J), (-2J)… = uno, dos o más juegos por jugar',
  progressPoint: 'Día {d}: {name} iba {pos}º',
  calToday: 'hoy',
  x2: '×2',
  wildUsed: 'comodín',
  players: 'Jugadores ({n} de {max})',
  shareInvite: '📤 Invitar al grupo',
  adminTab: '⚙️ Administrar',
  you: 'tú',
  leave: 'Salir de esta copa en este celular',
  leaveConfirm: '¿Salir de la copa en este celular? Para volver vas a necesitar tu nombre y tu PIN.',

  // Antes de jugar
  howToPlay: 'Cómo se juega',
  rulesOf: 'Reglas de {juego}',
  finalRounds: 'Las cinco rondas',
  scoring: 'Puntaje',
  wildTitle: 'Comodín ×2',
  wildOff: 'Tienes un comodín por copa: duplica los puntos de un día. Se activa antes de empezar y no vale en la final.',
  wildUse: 'Usar el comodín en este día',
  wildOn: 'Comodín activado: este día vale el doble.',
  wildGone: 'Ya usaste tu comodín en el día {d}.',
  wildFinal: 'En la final no se puede usar el comodín, pero vale el doble para todos.',
  wildConfirm: '¿Usar tu único comodín en el día {d}? No se puede deshacer.',
  start: 'Empezar',
  letsPlay: '¡A jugar!',
  bdTitle: 'Cómo se calculó tu puntaje',
  bdTotal: 'Total: {s} puntos.',
  bdTotalOne: 'Total: 1 punto.',
  bdTime: 'Tu tiempo fue {t}. Si empatas en puntos con alguien, gana quien tardó menos.',
  bdPlaces: 'En la copa, tu lugar del día se convierte en puntos: el 1º gana 10, el 2º 8, el 3º 6, el 4º 5, el 5º 4, el 6º 3, el 7º 2 y del 8º en adelante 1.',
  bdWild: 'Usaste el comodín este día, así que tus puntos de la copa valen el doble.',
  bdFinal: 'Es la gran final, así que los puntos de la copa de este día valen el doble para todos.',
  bdLinea: 'Pusiste bien {n} de {total} cartas, así que te llevas esa parte de 100: {s} puntos.',
  bdTries: 'Lo sacaste en {u} de {max} intentos.',
  bdTriesPts: 'Parte en 100 y cada intento después del primero resta 10: se restan {menos} y quedan {s} puntos.',
  bdNotSolved: 'No alcanzaste a resolverlo, así que este juego da 0 puntos.',
  bdGroups: 'Encontraste {n} grupos de 4, a 25 puntos cada uno: {pts} puntos.',
  bdMistakes: 'Tuviste {n} errores, a {c} puntos cada uno: se restan {pts} puntos.',
  bdMistakesOne: 'Tuviste 1 error, que resta {c} puntos.',
  bdStart100: 'Partes con 100 puntos.',
  bdFamas: 'Encontraste {n} letras en su lugar, a 10 puntos cada una: {pts} puntos. Una letra que ya habías encontrado no vuelve a sumar.',
  bdFamasOne: 'Encontraste 1 letra en su lugar, que suma 10 puntos. Una letra que ya habías encontrado no vuelve a sumar.',
  bdNoFamas: 'No encontraste ninguna letra en su lugar, así que por eso no sumas puntos.',
  bdWordBonus: 'Sacaste la palabra en {u} intentos: suma 50 menos 5 por cada intento después del primero, o sea {b} puntos.',
  bdWordBonusFirst: 'Sacaste la palabra al primer intento: suma 50 puntos más.',
  bdWordNoBonus: 'No sacaste la palabra, así que no sumas los puntos de resolverla.',
  bdQueensTime: 'Resolviste el tablero en {t}.',
  bdQueensScale: 'Hasta 30 segundos vale 100 puntos y después baja parejo hasta 10 puntos a los 5 minutos. Equivocarse no resta.',
  bdRuleBreaks: 'Hiciste {n} jugadas que rompían una regla, a 10 puntos cada una: se restan {pts} puntos.',
  bdRuleBreaksOne: 'Hiciste 1 jugada que rompía una regla, que resta 10 puntos.',
  bdNoRuleBreaks: 'No hiciste ninguna jugada que rompiera una regla, así que no se resta nada por eso.',
  bdHints: 'Pediste {n} pistas, a {c} puntos cada una: se restan {pts} puntos.',
  bdHintsOne: 'Pediste 1 pista, que resta {c} puntos.',
  bdFloor10: 'Si terminas el tablero, el puntaje nunca baja de 10.',
  bdLevels: 'Resolviste {n} niveles en los tres minutos, a 10 puntos cada uno: {pts} puntos.',
  bdLevelsOne: 'Resolviste 1 nivel en los tres minutos, que vale 10 puntos.',
  bdLastLevel: 'Resolviste tu último nivel a los {t}. Si empatas en niveles, gana quien lo resolvió antes.',
  bdYear: '{hito}: dijiste {r} y era {y}, así que ganaste {pts} de 100 puntos.',
  bdRound: '{emoji} {juego}: {pts} de 100 puntos.',
  bdAverage: 'Tu puntaje es el promedio, de 0 a 100.',
  reportNameKeep: 'Tu nombre queda guardado en este dispositivo para el próximo reporte.',
  startWarn: 'Tienes un solo intento. Si cierras la página, al volver sigues donde quedaste.',
  timer: '⏱ {t}',

  // Resultado del día
  resultTitle: 'Día {d}: {juego}',
  yourScore: 'Tu puntaje',
  provisional: 'Por ahora vas {pos} de {n} en este día. La posición es provisoria hasta que el día cierre.',
  finalPos: 'Quedaste {pos} de {n} en este día y sumaste {pts} puntos.',
  dayTable: 'Resultados del día',
  shareCard: '📤 Compartir mi resultado',
  toBoard: 'Volver a la copa',
  sending: 'Guardando tu resultado…',
  sendFail: 'No pudimos guardar tu resultado. Revisa tu internet e intenta nuevamente: tu partida está guardada en este celular.',

  // Final
  podiumTitle: '¡{name} ganó la copa!',
  podiumTie: '¡Empate en la copa!',
  medalChamp: '🏆 Campeón',
  medalWins: '🥇 Más días ganados',
  medalComeback: '🚀 La remontada',
  medalLast: '🏮 Farolito rojo',
  shareSummary: '📤 Compartir el resumen',

  // Admin
  adminTitle: 'Administrar la copa',
  adminMsgs: 'Mensajes para los competidores',
  msgInvite: 'Invitación',
  msgToday: 'Recordatorio del día',
  msgTable: 'Tabla parcial',
  msgFinal: 'Resumen final',
  adminPlayers: 'Jugadores',
  youAdmin: 'tú, admin',
  adminWelcomeTitle: 'Tu copa está creada. Ahora, a juntar a los competidores',
  adminWelcome1: 'Toca Invitación y compártela por WhatsApp o por donde quieras. Cada uno entra con el link, escribe su nombre y elige un PIN de 4 números.',
  adminWelcome2: 'Espera a que se inscriban: van apareciendo abajo, en Jugadores. Pueden inscribirse desde ahora, antes de que la copa parta el {fecha}. La copa necesita al menos 2 jugadores, contigo incluido, y admite hasta 10.',
  adminWelcome3: 'Cuando estén todos, puedes cerrar la inscripción. Si la fecha de inicio ya no te acomoda, cámbiala a hoy o a mañana mientras nadie haya jugado.',
  startTitle: 'Inicio de la copa',
  startIs: 'La copa parte el {fecha}.',
  startWas: 'La copa partió el {fecha}, pero todavía nadie ha jugado.',
  startPassed: 'Como nadie ha jugado todavía, puedes mover el inicio a hoy o a mañana para que todos partan juntos.',
  startLate: 'Quedan pocas horas de hoy. El día 1 se puede jugar hasta mañana a las 23:59, pero si prefieres que la copa parta mañana, muévela.',
  startTodayBtn: 'Que parta hoy',
  startTomorrowBtn: 'Que parta mañana',
  startOther: 'Otra fecha',
  startOtherGo: 'Que parta ese día',
  errStartDate: 'Elige una fecha desde hoy y hasta {n} días más.',
  labTitle: 'Copa de prueba',
  labLead: 'Esta copa es del laboratorio. Para probar sin esperar, puedes pasarla al día siguiente: lo de hoy queda como ayer, en su día de gracia, y se abre el día que sigue para todos.',
  labNext: 'Pasar al día {d}',
  labEnd: 'Terminar la copa',
  labNextConfirm: '¿Pasar la copa al día {d}? El día {hoy} queda como ayer y el día {d} se abre para todos. No se puede deshacer.',
  labEndConfirm: '¿Terminar la copa ahora? Se cierra la final y se ve el podio. No se puede deshacer.',
  labNextDone: 'Listo: la copa está en el día {d}.',
  labEndDone: 'Listo: la copa terminó.',
  startMoveConfirm: '¿Mover el inicio de la copa al {fecha}? Todos los días se corren con él.',
  startMoved: 'Listo: la copa parte el {fecha}. Si ya habías mandado la invitación, avísale al grupo con el recordatorio.',
  joinTitle: 'Inscripción',
  joinIsOpen: 'La inscripción está abierta: van {n} de {max} jugadores.',
  joinIsClosed: 'La inscripción está cerrada: nadie nuevo puede entrar. Los inscritos siguen entrando con su nombre y su PIN.',
  joinClose: 'Cerrar la inscripción',
  joinReopen: 'Reabrir la inscripción',
  joinCloseConfirm: '¿Cerrar la inscripción? Nadie nuevo va a poder entrar a la copa. Puedes reabrirla después.',
  kick: 'Sacar',
  unkick: 'Volver a meter',
  rename: 'Renombrar',
  newPin: 'Nuevo PIN',
  kicked: 'fuera',
  kickConfirm: '¿Sacar a {name} de la copa? Deja de aparecer en la tabla y sus puntos no cuentan. Se puede deshacer.',
  renamePrompt: 'Nuevo nombre para {name}',
  pinPrompt: 'Escribe un PIN nuevo de 4 números para {name}. Después díselo a esa persona.',
  pinDone: 'Listo. El nuevo PIN de {name} es {pin}.',
  copied: 'Copiado. Pégalo en el chat del grupo.',

  // Mensajes para compartir (van por WhatsApp)
  shareInviteText: '🏆 *La Copa: {copa}* · ¡Estás invitado!\n\n¿Te la puedes? Son {dias} días y {dias} minijuegos, con una sola oportunidad al día. Todos juegan lo mismo y la tabla dice quién manda. Quien acumula más puntos se lleva la gloria. 🥇\n\n📅 Parte el {fecha}.\n⏱️ Unos pocos minutos al día, desde tu celular.\n{inscritos}\n\n🔑 Entra con tu nombre y un PIN de 4 números:',
  shareInviteJoined: '👥 Ya se inscribieron: {names}.',
  shareInviteJoinedOne: '👥 Ya se inscribió {names}.',
  shareTodayText: '🏆 *{copa}* · Día {d} de {n}\n\n🎮 Hoy toca {juego}.\n⏰ Tienes hasta {hasta} para jugarlo.',
  shareTodayGrace: '🕐 Si te falta el de ayer ({juego}), todavía lo puedes jugar hasta hoy a medianoche.',
  shareTodayMissing: '👀 Faltan por jugar hoy: {names}.',
  shareBeforeClosed: '🏆 *{copa}*\n\n📅 Parte el {fecha}.\n🎮 El primer juego es {juego}.\n🔑 Entra con tu nombre y tu PIN en este link:',
  shareBeforeText: '🏆 *{copa}*\n\n📅 Parte el {fecha}.\n🎮 El primer juego es {juego}.\n✍️ Si todavía no te inscribes, entra con tu nombre y un PIN de 4 números en este link:',
  shareTableText: '📊 *La Copa: {copa}* · Tabla de posiciones (día {d})\n\n{tabla}',
  shareTableMissing: '⏳ ¡Día {d} en curso! Falta que jueguen: {names}.',
  shareFinalText: '🏁 *La Copa: {copa}* · Terminó\n\n🏆 {campeon}\n\n{podio}',
  shareFinalChamp: 'Ganó {name} con {pts} puntos.',
  shareCardText: '🏆 *La Copa: {copa}* · Día {d}\n{emoji} {juego}\n👤 {name} · {resumen}',
  untilTomorrow: 'mañana a medianoche',
  untilToday: 'hoy a medianoche',

  // Pantalla de minijuego
  confirm: 'Confirmar',
  confirmShort: 'OK',
  dc: 'd. C.',
  // Línea Relámpago (el resto de sus textos son los de Línea de Tiempo)
  lineaLleva: 'vas {ok} de {n}',
  lineaQuedan: 'Quedan {n}',
  lineaFin: 'Pusiste bien {ok} de {n} cartas.',
  // Toque y Fama (el resto de sus textos son los de Toque y Fama)
  yourGuesses: 'Tus intentos',
  solvedWord: '¡La sacaste!',
  famasFound: 'Llevas {n} de {largo} letras en su lugar: {pts} puntos.',
  famasFoundOne: 'Llevas 1 de {largo} letras en su lugar: {pts} puntos.',
  notSolvedWord: 'Se acabaron los intentos. La palabra era {v}.',
  blockHintDigits: '💡 Mantén apretada una cifra para tacharla si crees que no está en el número secreto. Repite para destacharla.',
  blockHintLetters: '💡 Mantén apretada una letra para tacharla si crees que no está en la palabra. Repite para destacharla.',
  // Reinas, Tango y Zip
  queensLeft: 'Reinas puestas: {m} de {n}',
  queensOk: '¡Resolviste las reinas!',
  queensClash: 'Hay reinas que chocan: comparten fila, columna o zona, o se tocan.',
  tangoOk: '¡Resolviste el tango!',
  tangoClash: 'Algo no calza: tres iguales seguidos, más de tres de uno en una línea, o una marca = o ≠ que no se cumple.',
  // Sesión de prueba (D-103)
  tryFirst: 'Probar primero (no cuenta)',
  trialChip: '🧪 Prueba',
  trialEnd: 'Terminar la prueba',
  trialDoneTitle: 'Así se juega',
  trialDone: 'En la prueba sacaste {resumen}. No cuenta para la copa, y el juego de verdad tiene otro contenido.',
  trialBack: 'Volver para jugar de verdad',
  zipHint: 'Arrastra el dedo desde el 1 por todas las casillas, pasando por los números en orden.',
  zipLevel: 'Nivel {k} · {n} × {n}',
  zipDone: 'Resueltos: {n}',
  zipTime: 'Se acabó el tiempo. Resolviste {n} niveles.',
  zipTimeOne: 'Se acabó el tiempo. Resolviste 1 nivel.',
  zipSolution: 'Así se resolvía el nivel {k}, el que te quedó a medias.',
  zipMissing: 'Llegaste al último número, pero te faltan {n} casillas: el trazo tiene que pasar por todas. Vuelve atrás y busca otro camino.',
  zipMissingOne: 'Llegaste al último número, pero te falta 1 casilla: el trazo tiene que pasar por todas. Vuelve atrás y busca otro camino.',
  giveUp: 'Rendirse',
  giveUpConfirm: '¿Seguro que te rindes? Vas a ver la solución y este juego te va a dar 0 puntos. No se puede deshacer.',
  queensGaveUp: 'Te rendiste. Esta es la solución: una reina por fila, columna y zona, sin tocarse.',
  bdGaveUp: 'Te rendiste, así que este juego da 0 puntos.',
  queensExOk: 'Así: una reina por fila, por columna y por color.',
  queensExBad: 'Así no: se tocan.',
  tangoExOk: 'Así: tres soles y tres lunas en cada fila y en cada columna, y las marcas = y ≠ se cumplen.',
  tangoExBad: 'Así no: tres iguales seguidos.',
  zipExOk: 'Así: un solo trazo que pasa por todas las casillas y toca los números en orden.',
  zipExBad: 'Así no: llegó al 4, pero quedaron casillas sin pintar.',
  queensHint: '💡 Toca una casilla para poner o sacar una reina. Mantenla apretada para marcarla con una X y descartarla.',
  tangoCount: 'Errores: {e} · Pistas: {p}',
  clearAll: 'Borrar todo',
  clearAllSure: '¿Seguro? Toca de nuevo para borrar',
  hintCost: 'Pista (−{n} puntos)',
  hintSure: 'Toca de nuevo para usar la pista (−{n})',
  tipsTitle: 'Consejos si estás atascado',
  tangoTips: [
    'Si dos casillas seguidas son iguales, las de los lados son del otro tipo: nunca hay tres iguales seguidos.',
    'Si hay un hueco entre dos iguales (☀️ _ ☀️), el del medio es del otro tipo.',
    'Cuando una fila o columna ya tiene sus tres soles, todo lo que falta son lunas, y al revés.',
    'Las marcas se encadenan: si A = B y ya sabes A, ya sabes B. Con ≠, es el contrario.',
    'Mira primero las filas y columnas más llenas: ahí quedan menos opciones.',
  ],
  triesLeft: 'Te quedan {n} intentos.',
  tryLeft1: 'Te queda 1 intento.',
  solved: '¡Lo sacaste!',
  notSolved: 'Se acabaron los intentos. El número era {v}.',
  select4: 'Elige 4 palabras',
  oneAway: '¡A una!',
  wrongGroup: 'No es un grupo.',
  alreadyTried: 'Ya probaste esas cuatro.',
  mistakesLeft: 'Errores disponibles: {n}',
  shuffle: 'Barajar',
  deselect: 'Limpiar',
  groupsOk: '¡Encontraste los 4 grupos!',
  groupsFail: 'Se acabaron los errores. Estos eran los grupos.',
  next: 'Siguiente',
  yearOf: 'Hito {i} de {n}',
  yearPh: 'Año',
  bc: 'a. C.',
  yearWas: 'Fue en {v}. Ganaste {pts} puntos.',
  roundOf: 'Ronda {i} de 5',

  // Laboratorio y práctica (D-101)
  backToLabs: '🧪 Volver al laboratorio',
  backToLabsShort: '‹ Laboratorio',
  practiceTitle: 'Práctica en el laboratorio',
  // El minijuego suelto, abierto desde la portada (D-141)
  looseTitle: 'Minijuego de La Copa',
  looseHint: 'Acá lo juegas suelto: no cuenta para ninguna copa y puedes jugarlo las veces que quieras.',
  backToMenu: 'Volver al menú',
  practiceHint: 'Es una práctica: no cuenta para ninguna copa y puedes jugarla las veces que quieras.',
  practiceSeed: 'Esta partida es la semilla {semilla}. Si vas a reportar un problema, con ella se repite la misma partida.',
  practiceAgain: 'Jugar otra vez con otro contenido',
  practiceSame: 'Repetir exactamente esta partida',

  // Reportes (LIG-42)
  reportButton: '🐞 Reportar un problema o dejar un comentario',
  reportTitle: 'Cuéntanos qué pasó',
  reportLead: 'Describe el problema o el comentario con tus palabras: qué hiciste, qué esperabas y qué pasó. Lo lee quien mantiene juegosdesalon.cl.',
  reportPlaceholder: 'Por ejemplo: toqué Confirmar en Conexiones y no pasó nada.',
  reportNamePh: 'Tu nombre (opcional)',
  reportNameLabel: '¿Quién escribe?',
  reportContext: 'Lo que se envía además de tu texto',
  reportSend: 'Enviar',
  reportEmpty: 'Escribe qué pasó antes de enviar.',
  errEmpezada: 'Ya no se puede mover el inicio: alguien empezó a jugar.',
  errReport: 'No pudimos enviar tu mensaje. Revisa tu internet e intenta nuevamente en unos minutos.',
  reportThanks: '¡Gracias! Tu mensaje llegó y lo vamos a revisar.',
  reportQueued: 'No pudimos enviar tu mensaje ahora, pero quedó guardado en este dispositivo y se enviará solo la próxima vez que abras La Copa. ¡Gracias!',
  reportBack: 'Volver',
  reportCancel: 'Cancelar',
  sending2: 'Enviando…',

  // Barra del modo de prueba
  roundStart: 'Empezar la ronda',
  roundNext: 'Siguiente ronda',
  roundDone: 'Ronda terminada: {pts} puntos.',
  finalSoFar: 'Llevas {pts} de {max} puntos.',
  seeResults: 'Ver resultado',
};

export const LOCALES = { es: ES };
