/**
 * Batalla Naval — configuración por defecto y textos en español, inglés y portugués.
 */
export const GAME_ID = 'batalla-naval';
export const DEFAULT_CONFIG = { extraShot: true, confirmShot: true };

const ES = {
  docTitle: 'Batalla Naval ⚓ · Juegos de Salón', gameChip: '⚓ Batalla Naval', menu: '‹ Menú',
  title: 'Batalla Naval',
  lead: 'Coloca tu flota en secreto y hunde la del rival antes de que hunda la tuya.',
  howTitle: '🧭 Cómo se juega',
  howText: 'Cada flota tiene 5 barcos en un tablero de 10×10. Por turnos disparas a una casilla del rival: <b>agua</b> si no hay nada, <b>tocado</b> si le das a un barco y <b>hundido</b> si ya le diste en todas sus casillas.',
  modeLocal: '📱 Un celular, dos jugadores', modeLocalHint: 'Se pasan el celular. Tu flota se tapa entre turnos.',
  modeOnline: '📡 Dos celulares', modeOnlineHint: 'Cada uno juega en su celular.',
  modeCpu: '🤖 Contra el celular', modeCpuHint: 'El celular coloca su flota y dispara a la tuya.',
  setupTitle: '¿Cómo jugamos?', extraShot: 'Tiro extra al acertar', extraShotHint: 'Si tocas o hundes, disparas de nuevo.', confirmShot: 'Confirmar cada disparo', confirmShotHint: 'Eliges la casilla y luego tocas ¡Fuego!',
  yourName: 'Tu nombre', p1: 'Jugador 1', p2: 'Jugador 2', cpuName: 'Celular', start: '¡A jugar!',
  errName: 'Falta el nombre.', errNames: 'Faltan nombres o están repetidos.',
  create: 'Crear sala', joinTitle: 'Unirse a una sala', codePlaceholder: 'CÓDIGO', join: 'Unirse', errCode: 'El código tiene 4 letras.',
  errNotFound: 'No existe esa sala. Revisa el código.', errFull: 'La sala ya está llena.', errExpired: 'Esa sala ya venció.', errOtherGame: 'Ese código es de otro juego.', errNet: 'No se pudo conectar. ¿Hay internet?',
  errOffline: 'No se pudo abrir la sala. Puede ser tu internet o que haya mucha gente jugando. Intenta nuevamente en unos minutos o jugar en modo de un solo celular sin conexión a internet.',
  errTooMany: 'Abriste muchas salas seguidas. Espera un ratito y prueba de nuevo.',
  invitedTitle: '¡Invitado a jugar!', invited: '📩 Sala {code}', invitedHint: 'Escribe tu nombre y entra. La partida la configura quien te invitó.',
  lobbyTitle: 'Sala creada', lobbyCode: 'Código', lobbyShare: 'Dile el código al rival o que escanee el QR.', lobbyWaiting: 'Esperando al rival', lobbyJoined: '¡{name} se unió!', shareLink: '📤 Compartir link', copyLink: '📋 Copiar link', copied: '¡Copiado!',
  lobbyCancel: 'Cancelar la sala', lobbyLeave: 'Salir de la sala',
  chatTitle: 'Chat de la sala', chatOpen: 'Abrir el chat', chatClose: 'Cerrar el chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escribe algo…', chatEmpty: 'Acá pueden picarse entre disparo y disparo. Se borra cuando termina la sala.',
  offline: 'Rival desconectado. Esperando que vuelva…', rematchWaiting: 'Esperando a {name} para la revancha',
  resumeTitle: '⏯ Hay una batalla a medias', resume: 'Continuar', delete: 'Borrar',
  // colocación
  placeTitle: 'Coloca tu flota', placeFor: 'Flota de {name}', placeHint: 'Toca un barco y luego una casilla, o arrástralo. Toca uno puesto para girarlo o moverlo.',
  ships: { carrier: 'Portaaviones', battleship: 'Acorazado', cruiser: 'Crucero', submarine: 'Submarino', destroyer: 'Destructor' },
  rotate: '↻ Girar {dir}', random: '🎲 Al azar', clear: '🧹 Limpiar', sail: '⚓ ¡Zarpar!', placed: '{n} de 5 barcos',
  fleetSaved: 'Flota lista 🔒', waitingFleet: 'Esperando a que {name} coloque su flota', tapToReveal: 'Toca para ver', hoPass: 'Pásale el celular a', hoReady: '¡Listo, soy yo!',
  // batalla
  turnYou: '¡Te toca!', turnYouSub: 'Dispara a la flota de {name}', turnOther: 'Turno de {name}', turnOtherSub: 'Te está apuntando…',
  notYourTurn: 'Espera tu turno: ahora dispara {name}.', extraGo: '{result} Sigues disparando', waitingReply: 'Esperando la respuesta…',
  fire: '🎯 ¡Fuego!', enemyBoard: 'Flota de {name}', myBoard: 'Mi flota', showFleet: 'toca para ver mi flota', hideFleet: 'toca para ocultar',
  agua: 'Agua', tocado: '¡Tocado!', hundido: '¡Hundido!', sunkShip: 'Hundiste el {ship} de {name}', sunkMine: '¡Te hundieron el {ship}!',
  shotAt: '{name} disparó a {cell}',
  hoResult: 'Resultado', hoContinue: 'Seguir',
  // resultado
  winTitle: '¡Ganó {name}!', youWin: '¡Ganaste!', youLose: 'Te hundieron… esta vez.', stats: '{shots} disparos · {acc}% puntería', fleetsWere: 'Las flotas eran',
  verified: 'verificado ✅', notVerified: '⚠️ no coincide (¿trampa?)', replayTitle: '🔎 Ver todos los disparos', shotsOf: 'Disparos de {name}',
  rematch: '🔁 Revancha', changeMode: 'Cambiar modo', backMenu: 'Volver al menú',
};

const EN = {
  docTitle: 'Battleship ⚓ · Party Games', gameChip: '⚓ Battleship', menu: '‹ Menu',
  title: 'Battleship',
  lead: 'Hide your fleet and sink your rival\'s before they sink yours.',
  howTitle: '🧭 How to play',
  howText: 'Each fleet has 5 ships on a 10×10 board. Take turns firing at a cell on your rival\'s board: <b>miss</b> if there\'s nothing, <b>hit</b> if you strike a ship and <b>sunk</b> once you\'ve hit all its cells.',
  modeLocal: '📱 One phone, two players', modeLocalHint: 'Pass the phone around. Your fleet is hidden between turns.',
  modeOnline: '📡 Two phones', modeOnlineHint: 'Each player plays on their own phone.',
  modeCpu: '🤖 Versus the phone', modeCpuHint: 'The phone places its fleet and fires at yours.',
  setupTitle: 'How do we play?', extraShot: 'Extra shot on a hit', extraShotHint: 'Hit or sink and you fire again.', confirmShot: 'Confirm every shot', confirmShotHint: 'Pick the cell, then tap Fire!',
  yourName: 'Your name', p1: 'Player 1', p2: 'Player 2', cpuName: 'Phone', start: 'Let\'s play!',
  errName: 'Name missing.', errNames: 'Names missing or repeated.',
  create: 'Create room', joinTitle: 'Join a room', codePlaceholder: 'CODE', join: 'Join', errCode: 'The code has 4 letters.',
  errNotFound: 'That room doesn\'t exist. Check the code.', errFull: 'That room is full.', errExpired: 'That room has expired.', errOtherGame: 'That code belongs to another game.', errNet: 'Could not connect. Is there internet?',
  errOffline: 'Couldn\'t open the room. It might be your connection or too many people playing. Try again in a few minutes, or play in one-phone mode, which needs no internet.',
  errTooMany: 'You\'ve opened a lot of rooms in a row. Wait a bit and try again.',
  invitedTitle: 'Invited to play!', invited: '📩 Room {code}', invitedHint: 'Type your name and jump in. Whoever invited you sets up the game.',
  lobbyTitle: 'Room created', lobbyCode: 'Code', lobbyShare: 'Tell your rival the code or let them scan the QR.', lobbyWaiting: 'Waiting for your rival', lobbyJoined: '{name} joined!', shareLink: '📤 Share link', copyLink: '📋 Copy link', copied: 'Copied!',
  lobbyCancel: 'Cancel the room', lobbyLeave: 'Leave the room',
  chatTitle: 'Room chat', chatOpen: 'Open the chat', chatClose: 'Close the chat', chatSend: 'Send',
  chatPlaceholder: 'Say something…', chatEmpty: 'Trash talk between shots. It disappears when the room closes.',
  offline: 'Rival disconnected. Waiting for them to come back…', rematchWaiting: 'Waiting for {name} for the rematch',
  resumeTitle: '⏯ There\'s an unfinished battle', resume: 'Continue', delete: 'Delete',
  placeTitle: 'Place your fleet', placeFor: '{name}\'s fleet', placeHint: 'Tap a ship, then a cell, or drag it. Tap a placed ship to rotate or move it.',
  ships: { carrier: 'Carrier', battleship: 'Battleship', cruiser: 'Cruiser', submarine: 'Submarine', destroyer: 'Destroyer' },
  rotate: '↻ Rotate {dir}', random: '🎲 Random', clear: '🧹 Clear', sail: '⚓ Set sail!', placed: '{n} of 5 ships',
  fleetSaved: 'Fleet ready 🔒', waitingFleet: 'Waiting for {name} to place their fleet', tapToReveal: 'Tap to reveal', hoPass: 'Pass the phone to', hoReady: 'Ready, it\'s me!',
  turnYou: 'Your turn!', turnYouSub: 'Fire at {name}\'s fleet', turnOther: '{name}\'s turn', turnOtherSub: 'They\'re aiming at you…',
  notYourTurn: 'Wait your turn: {name} is firing now.', extraGo: '{result} Fire again', waitingReply: 'Waiting for the reply…',
  fire: '🎯 Fire!', enemyBoard: '{name}\'s fleet', myBoard: 'My fleet', showFleet: 'tap to show my fleet', hideFleet: 'tap to hide',
  agua: 'Miss', tocado: 'Hit!', hundido: 'Sunk!', sunkShip: 'You sank {name}\'s {ship}', sunkMine: 'They sank your {ship}!',
  shotAt: '{name} fired at {cell}',
  hoResult: 'Result', hoContinue: 'Continue',
  winTitle: '{name} wins!', youWin: 'You win!', youLose: 'You got sunk… this time.', stats: '{shots} shots · {acc}% accuracy', fleetsWere: 'The fleets were',
  verified: 'verified ✅', notVerified: '⚠️ mismatch (cheating?)', replayTitle: '🔎 See all shots', shotsOf: '{name}\'s shots',
  rematch: '🔁 Rematch', changeMode: 'Change mode', backMenu: 'Back to menu',
};


const PT = {
  docTitle: 'Batalha Naval ⚓ · Jogos de Salão', gameChip: '⚓ Batalha Naval', menu: '‹ Menu',
  title: 'Batalha Naval',
  lead: 'Posicione sua frota em segredo e afunde a do rival antes que ele afunde a sua.',
  howTitle: '🧭 Como se joga',
  howText: 'Cada frota tem 5 navios em um tabuleiro de 10×10. Nos turnos você atira em uma casa do rival: <b>água</b> se não tem nada, <b>acertou</b> se você atinge um navio e <b>afundou</b> se você já acertou todas as casas dele.',
  modeLocal: '📱 Um celular, dois jogadores', modeLocalHint: 'Vocês passam o celular. Sua frota fica coberta entre os turnos.',
  modeOnline: '📡 Dois celulares', modeOnlineHint: 'Cada um joga no seu celular.',
  modeCpu: '🤖 Contra o celular', modeCpuHint: 'O celular posiciona a frota dele e atira na sua.',
  setupTitle: 'Como vamos jogar?', extraShot: 'Tiro extra ao acertar', extraShotHint: 'Se acertar ou afundar, você atira de novo.', confirmShot: 'Confirmar cada tiro', confirmShotHint: 'Você escolhe a casa e depois toca em Fogo!',
  yourName: 'Seu nome', p1: 'Jogador 1', p2: 'Jogador 2', cpuName: 'Celular', start: 'Bora jogar!',
  errName: 'Falta o nome.', errNames: 'Faltam nomes ou estão repetidos.',
  create: 'Criar sala', joinTitle: 'Entrar em uma sala', codePlaceholder: 'CÓDIGO', join: 'Entrar', errCode: 'O código tem 4 letras.',
  errNotFound: 'Essa sala não existe. Confira o código.', errFull: 'A sala já está cheia.', errExpired: 'Essa sala já expirou.', errOtherGame: 'Esse código é de outro jogo.', errNet: 'Não foi possível conectar. Tem internet?',
  errOffline: 'Não foi possível abrir a sala. Pode ser a sua internet ou muita gente jogando ao mesmo tempo. Tente de novo em alguns minutos ou jogue no modo de um celular só, que não precisa de internet.',
  errTooMany: 'Você abriu muitas salas seguidas. Espere um pouquinho e tente de novo.',
  invitedTitle: 'Convidado para jogar!', invited: '📩 Sala {code}', invitedHint: 'Escreva seu nome e entre. Quem te convidou configura a partida.',
  lobbyTitle: 'Sala criada', lobbyCode: 'Código', lobbyShare: 'Diga o código ao rival ou deixe ele escanear o QR.', lobbyWaiting: 'Esperando o rival', lobbyJoined: '{name} entrou!', shareLink: '📤 Compartilhar link', copyLink: '📋 Copiar link', copied: 'Copiado!',
  lobbyCancel: 'Cancelar a sala', lobbyLeave: 'Sair da sala',
  chatTitle: 'Chat da sala', chatOpen: 'Abrir o chat', chatClose: 'Fechar o chat', chatSend: 'Enviar',
  chatPlaceholder: 'Escreva algo…', chatEmpty: 'Aqui dá para provocar entre um tiro e outro. Some quando a sala fecha.',
  offline: 'Rival desconectado. Esperando ele voltar…', rematchWaiting: 'Esperando {name} para a revanche',
  resumeTitle: '⏯ Tem uma batalha pela metade', resume: 'Continuar', delete: 'Apagar',
  // posicionamento
  placeTitle: 'Posicione sua frota', placeFor: 'Frota de {name}', placeHint: 'Toque em um navio e depois em uma casa, ou arraste-o. Toque em um navio posicionado para girá-lo ou movê-lo.',
  ships: { carrier: 'Porta-aviões', battleship: 'Encouraçado', cruiser: 'Cruzador', submarine: 'Submarino', destroyer: 'Destróier' },
  rotate: '↻ Girar {dir}', random: '🎲 Aleatório', clear: '🧹 Limpar', sail: '⚓ Zarpar!', placed: '{n} de 5 navios',
  fleetSaved: 'Frota pronta 🔒', waitingFleet: 'Esperando {name} posicionar a frota', tapToReveal: 'Toque para ver', hoPass: 'Passe o celular para', hoReady: 'Pronto, sou eu!',
  // batalha
  turnYou: 'Sua vez!', turnYouSub: 'Atire na frota de {name}', turnOther: 'Vez de {name}', turnOtherSub: 'Estão mirando em você…',
  notYourTurn: 'Espere a sua vez: agora quem atira é {name}.', extraGo: '{result} Continue atirando', waitingReply: 'Esperando a resposta…',
  fire: '🎯 Fogo!', enemyBoard: 'Frota de {name}', myBoard: 'Minha frota', showFleet: 'toque para ver minha frota', hideFleet: 'toque para esconder',
  agua: 'Água', tocado: 'Acertou!', hundido: 'Afundou!', sunkShip: 'Você afundou o {ship} de {name}', sunkMine: 'Afundaram o seu {ship}!',
  shotAt: '{name} atirou em {cell}',
  hoResult: 'Resultado', hoContinue: 'Continuar',
  // resultado
  winTitle: '{name} ganhou!', youWin: 'Você ganhou!', youLose: 'Afundaram você… desta vez.', stats: '{shots} tiros · {acc}% de pontaria', fleetsWere: 'As frotas eram',
  verified: 'verificado ✅', notVerified: '⚠️ não confere (roubou?)', replayTitle: '🔎 Ver todos os tiros', shotsOf: 'Tiros de {name}',
  rematch: '🔁 Revanche', changeMode: 'Mudar o modo', backMenu: 'Voltar ao menu',
};

const DE = {
  docTitle: 'Schiffe versenken ⚓ · Salonspiele', gameChip: '⚓ Schiffe versenken', menu: '‹ Menü',
  title: 'Schiffe versenken',
  lead: 'Versteck deine Flotte und versenk die deines Gegners, bevor er deine versenkt.',
  howTitle: '🧭 So geht’s',
  howText: 'Jede Flotte hat 5 Schiffe auf einem 10×10-Feld. Abwechselnd schießt ihr auf ein Feld des Gegners: <b>Wasser</b>, wenn dort nichts ist, <b>Treffer</b>, wenn du ein Schiff erwischst, und <b>versenkt</b>, wenn du alle seine Felder getroffen hast.',
  modeLocal: '📱 Ein Handy, zwei Spieler', modeLocalHint: 'Ihr reicht das Handy weiter. Zwischen den Zügen wird deine Flotte verdeckt.',
  modeOnline: '📡 Zwei Handys', modeOnlineHint: 'Jeder spielt auf seinem eigenen Handy.',
  modeCpu: '🤖 Gegen das Handy', modeCpuHint: 'Das Handy stellt seine Flotte auf und schießt auf deine.',
  setupTitle: 'Wie spielen wir?', extraShot: 'Extraschuss bei Treffer', extraShotHint: 'Triffst oder versenkst du, schießt du nochmal.', confirmShot: 'Jeden Schuss bestätigen', confirmShotHint: 'Du wählst das Feld und tippst dann auf Feuer!',
  yourName: 'Dein Name', p1: 'Spieler 1', p2: 'Spieler 2', cpuName: 'Handy', start: 'Los geht’s!',
  errName: 'Der Name fehlt.', errNames: 'Namen fehlen oder sind doppelt.',
  create: 'Raum erstellen', joinTitle: 'Einem Raum beitreten', codePlaceholder: 'CODE', join: 'Beitreten', errCode: 'Der Code hat 4 Buchstaben.',
  errNotFound: 'Diesen Raum gibt es nicht. Prüf den Code.', errFull: 'Der Raum ist schon voll.', errExpired: 'Dieser Raum ist abgelaufen.', errOtherGame: 'Dieser Code gehört zu einem anderen Spiel.', errNet: 'Keine Verbindung. Hast du Internet?',
  errOffline: 'Der Raum ließ sich nicht öffnen. Vielleicht liegt es an deinem Internet oder es spielen gerade sehr viele. Versuch es in ein paar Minuten nochmal oder spiel mit einem Handy, dafür brauchst du kein Internet.',
  errTooMany: 'Du hast viele Räume hintereinander geöffnet. Warte kurz und versuch es nochmal.',
  invitedTitle: 'Du bist eingeladen!', invited: '📩 Raum {code}', invitedHint: 'Gib deinen Namen ein und steig ein. Wer dich eingeladen hat, stellt das Spiel ein.',
  lobbyTitle: 'Raum erstellt', lobbyCode: 'Code', lobbyShare: 'Sag deinem Gegner den Code oder lass ihn den QR-Code scannen.', lobbyWaiting: 'Warte auf deinen Gegner', lobbyJoined: '{name} ist dabei!', shareLink: '📤 Link teilen', copyLink: '📋 Link kopieren', copied: 'Kopiert!',
  lobbyCancel: 'Raum auflösen', lobbyLeave: 'Raum verlassen',
  chatTitle: 'Raum-Chat', chatOpen: 'Chat öffnen', chatClose: 'Chat schließen', chatSend: 'Senden',
  chatPlaceholder: 'Schreib was…', chatEmpty: 'Hier könnt ihr euch zwischen den Schüssen necken. Der Chat wird gelöscht, wenn der Raum schließt.',
  offline: 'Gegner getrennt. Warte, bis er zurückkommt…', rematchWaiting: 'Warte auf {name} für die Revanche',
  resumeTitle: '⏯ Eine Schlacht ist noch offen', resume: 'Weiter', delete: 'Löschen',
  // Aufstellen
  placeTitle: 'Stell deine Flotte auf', placeFor: 'Flotte von {name}', placeHint: 'Tippe auf ein Schiff und dann auf ein Feld, oder zieh es hin. Tippe auf ein gesetztes Schiff, um es zu drehen oder zu verschieben.',
  ships: { carrier: 'Flugzeugträger', battleship: 'Schlachtschiff', cruiser: 'Kreuzer', submarine: 'U-Boot', destroyer: 'Zerstörer' },
  rotate: '↻ Drehen {dir}', random: '🎲 Zufällig', clear: '🧹 Leeren', sail: '⚓ Leinen los!', placed: '{n} von 5 Schiffen',
  fleetSaved: 'Flotte bereit 🔒', waitingFleet: 'Warte, bis {name} die Flotte aufgestellt hat', tapToReveal: 'Tippen zum Ansehen', hoPass: 'Gib das Handy an', hoReady: 'Bereit, ich bin’s!',
  // Schlacht
  turnYou: 'Du bist dran!', turnYouSub: 'Schieß auf die Flotte von {name}', turnOther: '{name} ist dran', turnOtherSub: 'Du wirst ins Visier genommen…',
  notYourTurn: 'Warte, bis du dran bist: Jetzt schießt {name}.', extraGo: '{result} Schieß nochmal', waitingReply: 'Warte auf die Antwort…',
  fire: '🎯 Feuer!', enemyBoard: 'Flotte von {name}', myBoard: 'Meine Flotte', showFleet: 'tippen, um meine Flotte zu zeigen', hideFleet: 'tippen zum Verbergen',
  agua: 'Wasser', tocado: 'Treffer!', hundido: 'Versenkt!', sunkShip: '{ship} von {name} versenkt!', sunkMine: 'Dein {ship} wurde versenkt!',
  shotAt: '{name} schoss auf {cell}',
  hoResult: 'Ergebnis', hoContinue: 'Weiter',
  // Ergebnis
  winTitle: '{name} gewinnt!', youWin: 'Du hast gewonnen!', youLose: 'Versenkt… diesmal.', stats: '{shots} Schüsse · {acc} % Trefferquote', fleetsWere: 'Die Flotten waren',
  verified: 'geprüft ✅', notVerified: '⚠️ passt nicht (geschummelt?)', replayTitle: '🔎 Alle Schüsse ansehen', shotsOf: 'Schüsse von {name}',
  rematch: '🔁 Revanche', changeMode: 'Modus ändern', backMenu: 'Zurück zum Menü',
};

export const LOCALES = { es: ES, en: EN, pt: PT, de: DE };
